//
//  AIServiceTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import Foundation
import CoreMedia
@testable import SaneVideo

@Suite("AI Services Tests")
struct AIServiceTests {

    // MARK: - AIProvider Tests

    @Suite("AIProvider")
    struct AIProviderTests {

        @Test("Apple Foundation provider exists")
        func appleFoundationExists() {
            // Arrange & Act
            let provider = AIProvider.appleFoundation

            // Assert - provider exists and is the only option
            #expect(provider == .appleFoundation)
        }
    }

    // MARK: - AIError Tests

    @Suite("AIError")
    struct AIErrorTests {

        @Test("invalidResponse has description")
        func invalidResponseDescription() {
            // Arrange
            let error = AIError.invalidResponse

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.lowercased().contains("invalid") == true)
        }

        @Test("networkError wraps underlying error")
        func networkErrorWrapsError() {
            // Arrange
            let underlyingError = NSError(domain: "test", code: 500, userInfo: [NSLocalizedDescriptionKey: "connection failed"])
            let error = AIError.networkError(underlyingError)

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.contains("connection failed") == true)
        }

        @Test("apiError includes message")
        func apiErrorIncludesMessage() {
            // Arrange
            let error = AIError.apiError("Rate limit exceeded")

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.contains("Rate limit exceeded") == true)
        }

        @Test("All errors have unique descriptions")
        func allErrorsHaveUniqueDescriptions() {
            // Arrange
            let errors: [AIError] = [
                .invalidResponse,
                .networkError(NSError(domain: "test", code: 1)),
                .apiError("test error")
            ]

            // Act
            let descriptions = errors.compactMap { $0.errorDescription }

            // Assert
            #expect(descriptions.count == 3)
            let uniqueDescriptions = Set(descriptions)
            #expect(uniqueDescriptions.count == 3)
        }
    }

    // MARK: - AIGeneratedContent Tests

    @Suite("AIGeneratedContent")
    struct AIGeneratedContentTests {

        @Test("Stores title and description")
        func storesProperties() {
            // Arrange & Act
            let content = AIGeneratedContent(title: "Test Title", description: "Test Description")

            // Assert
            #expect(content.title == "Test Title")
            #expect(content.description == "Test Description")
        }

        @Test("Handles empty strings")
        func handlesEmptyStrings() {
            // Arrange & Act
            let content = AIGeneratedContent(title: "", description: "")

            // Assert
            #expect(content.title.isEmpty)
            #expect(content.description.isEmpty)
        }

        @Test("Handles unicode content")
        func handlesUnicode() {
            // Arrange & Act
            let content = AIGeneratedContent(
                title: "🎬 视频标题",
                description: "Beschreibung auf Deutsch с русским"
            )

            // Assert
            #expect(content.title.contains("🎬"))
            #expect(content.description.contains("Deutsch"))
        }
    }

    // MARK: - MagicFixAnalysis Tests

    @Suite("MagicFixAnalysis")
    struct MagicFixAnalysisTests {

        @Test("Segment stores all properties")
        func segmentStoresProperties() {
            // Arrange & Act
            let segment = MagicFixAnalysis.Segment(
                startTime: 10.5,
                endTime: 15.0,
                description: "Introduction",
                type: .topic
            )

            // Assert
            #expect(segment.startTime == 10.5)
            #expect(segment.endTime == 15.0)
            #expect(segment.description == "Introduction")
            #expect(segment.type == .topic)
        }

        @Test("SegmentType has all expected cases")
        func segmentTypeHasAllCases() {
            // Arrange & Act
            let types: [MagicFixAnalysis.Segment.SegmentType] = [.filler, .topic, .highlight, .silence]

            // Assert
            #expect(types.count == 4)
        }

        @Test("SegmentType rawValues are correct")
        func segmentTypeRawValues() {
            // Assert
            #expect(MagicFixAnalysis.Segment.SegmentType.filler.rawValue == "filler")
            #expect(MagicFixAnalysis.Segment.SegmentType.topic.rawValue == "topic")
            #expect(MagicFixAnalysis.Segment.SegmentType.highlight.rawValue == "highlight")
            #expect(MagicFixAnalysis.Segment.SegmentType.silence.rawValue == "silence")
        }

        @Test("MagicFixAnalysis stores segments")
        func storesSegments() {
            // Arrange
            let segments = [
                MagicFixAnalysis.Segment(startTime: 0, endTime: 5, description: "Intro", type: .topic),
                MagicFixAnalysis.Segment(startTime: 10, endTime: 11, description: "Um...", type: .filler)
            ]

            // Act
            let analysis = MagicFixAnalysis(segments: segments)

            // Assert
            #expect(analysis.segments.count == 2)
            #expect(analysis.segments[0].type == .topic)
            #expect(analysis.segments[1].type == .filler)
        }

        @Test("MagicFixAnalysis is Codable")
        func isCodable() throws {
            // Arrange
            let analysis = MagicFixAnalysis(segments: [
                MagicFixAnalysis.Segment(startTime: 0, endTime: 5, description: "Test", type: .highlight)
            ])

            // Act
            let data = try JSONEncoder().encode(analysis)
            let decoded = try JSONDecoder().decode(MagicFixAnalysis.self, from: data)

            // Assert
            #expect(decoded.segments.count == 1)
            #expect(decoded.segments[0].type == .highlight)
            #expect(decoded.segments[0].description == "Test")
        }

        @Test("Segment is Codable")
        func segmentIsCodable() throws {
            // Arrange
            let segment = MagicFixAnalysis.Segment(
                startTime: 12.5,
                endTime: 13.0,
                description: "Umm...",
                type: .filler
            )

            // Act
            let data = try JSONEncoder().encode(segment)
            let decoded = try JSONDecoder().decode(MagicFixAnalysis.Segment.self, from: data)

            // Assert
            #expect(decoded.startTime == 12.5)
            #expect(decoded.endTime == 13.0)
            #expect(decoded.type == .filler)
        }

        @Test("Empty segments array is valid")
        func emptySegmentsValid() {
            // Arrange & Act
            let analysis = MagicFixAnalysis(segments: [])

            // Assert
            #expect(analysis.segments.isEmpty)
        }
    }

    // MARK: - AIService Core Tests

    @Suite("AIService Core")
    @MainActor
    struct AIServiceCoreTests {

        @Test("Initializes with default provider")
        func initializesWithDefault() {
            // Arrange & Act
            let service = AIService()

            // Assert
            #expect(service.isGenerating == false)
        }

        @Test("Initializes with Apple Foundation provider")
        func initializesWithAppleFoundation() {
            // Arrange & Act
            let service = AIService(provider: .appleFoundation)

            // Assert
            #expect(service.isGenerating == false)
        }

        @Test("refineCaptions returns empty for empty input")
        func refineCaptionsReturnsEmptyForEmptyInput() async throws {
            // Arrange
            let service = AIService()

            // Act
            let result = try await service.refineCaptions([])

            // Assert
            #expect(result.isEmpty)
        }
    }

    // MARK: - Edge Cases

    @Suite("Edge Cases")
    struct EdgeCaseTests {

        @Test("MagicFixAnalysis handles many segments")
        func handlesManySegments() {
            // Arrange
            var segments: [MagicFixAnalysis.Segment] = []
            for i in 0..<100 {
                segments.append(MagicFixAnalysis.Segment(
                    startTime: Double(i),
                    endTime: Double(i) + 0.5,
                    description: "Segment \(i)",
                    type: i % 2 == 0 ? .topic : .filler
                ))
            }

            // Act
            let analysis = MagicFixAnalysis(segments: segments)

            // Assert
            #expect(analysis.segments.count == 100)
        }

        @Test("Segment with zero duration is valid")
        func zeroDurationSegmentValid() {
            // Arrange & Act
            let segment = MagicFixAnalysis.Segment(
                startTime: 5.0,
                endTime: 5.0,
                description: "Point in time",
                type: .highlight
            )

            // Assert
            #expect(segment.startTime == segment.endTime)
        }

        @Test("AIGeneratedContent handles long text")
        func handlesLongText() {
            // Arrange
            let longTitle = String(repeating: "A", count: 1000)
            let longDescription = String(repeating: "B", count: 5000)

            // Act
            let content = AIGeneratedContent(title: longTitle, description: longDescription)

            // Assert
            #expect(content.title.count == 1000)
            #expect(content.description.count == 5000)
        }
    }
}
