//
//  AIServiceTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import Foundation
import CoreMedia
@testable import SaneVideo

@Suite("AI Services Tests")
struct AIServiceTests {

    // MARK: - AIProvider Tests

    @Suite("AIProvider")
    struct AIProviderTests {

        @Test("Apple Foundation provider exists")
        func appleFoundationExists() {
            // Arrange & Act
            let provider = AIProvider.appleFoundation

            // Assert - provider exists and is the only option
            #expect(provider == .appleFoundation)
        }
    }

    // MARK: - AIError Tests

    @Suite("AIError")
    struct AIErrorTests {

        @Test("invalidResponse has description")
        func invalidResponseDescription() {
            // Arrange
            let error = AIError.invalidResponse

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.lowercased().contains("invalid") == true)
        }

        @Test("networkError wraps underlying error")
        func networkErrorWrapsError() {
            // Arrange
            let underlyingError = NSError(domain: "test", code: 500, userInfo: [NSLocalizedDescriptionKey: "connection failed"])
            let error = AIError.networkError(underlyingError)

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.contains("connection failed") == true)
        }

        @Test("apiError includes message")
        func apiErrorIncludesMessage() {
            // Arrange
            let error = AIError.apiError("Rate limit exceeded")

            // Assert
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.contains("Rate limit exceeded") == true)
        }

        @Test("All errors have unique descriptions")
        func allErrorsHaveUniqueDescriptions() {
            // Arrange
            let errors: [AIError] = [
                .invalidResponse,
                .networkError(NSError(domain: "test", code: 1)),
                .apiError("test error")
            ]

            // Act
            let descriptions = errors.compactMap { $0.errorDescription }

            // Assert
            #expect(descriptions.count == 3)
            let uniqueDescriptions = Set(descriptions)
            #expect(uniqueDescriptions.count == 3)
        }
    }

    // MARK: - AIGeneratedContent Tests

    @Suite("AIGeneratedContent")
    struct AIGeneratedContentTests {

        @Test("Stores title and description")
        func storesProperties() {
            // Arrange & Act
            let content = AIGeneratedContent(title: "Test Title", description: "Test Description")

            // Assert
            #expect(content.title == "Test Title")
            #expect(content.description == "Test Description")
        }

        @Test("Handles empty strings")
        func handlesEmptyStrings() {
            // Arrange & Act
            let content = AIGeneratedContent(title: "", description: "")

            // Assert
            #expect(content.title.isEmpty)
            #expect(content.description.isEmpty)
        }

        @Test("Handles unicode content")
        func handlesUnicode() {
            // Arrange & Act
            let content = AIGeneratedContent(
                title: "🎬 视频标题",
                description: "Beschreibung auf Deutsch с русским"
            )

            // Assert
            #expect(content.title.contains("🎬"))
            #expect(content.description.contains("Deutsch"))
        }
    }

    // MARK: - Commentary Workflow Tests

    @Suite("Commentary Workflow")
    struct CommentaryWorkflowTests {

        @Test("WorkflowBrief combines text and voice instructions")
        func workflowBriefCombinesPromptSources() {
            let brief = WorkflowBrief(
                workflow: .commentary,
                instructions: "Group the errors by concept.",
                voiceBriefSummary: "Keep the source timestamp visible.",
                maxMoments: 5
            )

            #expect(brief.hasContent)
            #expect(brief.combinedPrompt == "Group the errors by concept.\nKeep the source timestamp visible.")
        }

        @Test("CommentaryPlanItem mirrors commentary markers")
        func commentaryPlanItemFromMarkersPreservesOrder() {
            let markers = [
                CommentaryMarker(
                    concept: "Second",
                    title: "Second point",
                    startTime: 30,
                    endTime: 36,
                    scriptureReferences: "Acts 17:11",
                    sortOrder: 1
                ),
                CommentaryMarker(
                    concept: "First",
                    title: "First point",
                    startTime: 12,
                    endTime: 18,
                    scriptureReferences: "1 Timothy 5:21",
                    sortOrder: 0
                )
            ]

            let items = CommentaryPlanItem.fromMarkers(markers)

            #expect(items.count == 2)
            #expect(items[0].concept == "First")
            #expect(items[0].claim == "First point")
            #expect(items[0].supportingReferences == "1 Timothy 5:21")
            #expect(items[1].concept == "Second")
            #expect(items[1].startTime == 30)
        }

        @Test("Local SaneAI workflow parser converts workflow JSON into plan items")
        func localWorkflowParserBuildsPlanItems() throws {
            let response = """
            helper noise
            {
              "workflow": "meetingReview",
              "summary": "Capture the release hold.",
              "items": [
                {
                  "concept": "Hold The Release",
                  "claim": "Do not ship until timestamps are fixed.",
                  "supportingReferences": "PM review",
                  "sourceExcerpt": "Let's hold the release until the timestamps are fixed.",
                  "startTime": 42,
                  "endTime": 58,
                  "confidence": 0.91
                },
                {
                  "concept": "Fix Timestamps",
                  "claim": "Resolve the broken timestamp import path.",
                  "supportingReferences": "",
                  "sourceExcerpt": "The importer is still shifting everything by two hours.",
                  "startTime": 59,
                  "endTime": 74,
                  "confidence": 0.84
                }
              ]
            }
            trailing noise
            """

            let items = try LocalSaneAIWorkflowRunner.parsePlan(from: Data(response.utf8))

            #expect(items.count == 2)
            #expect(items[0].concept == "Hold The Release")
            #expect(items[0].claim.contains("Do not ship"))
            #expect(items[0].supportingReferences == "PM review")
            #expect(items[0].startTime == 42)
            #expect(items[1].concept == "Fix Timestamps")
            #expect(items[1].sourceExcerpt.contains("two hours"))
        }
    }

    // MARK: - MagicFixAnalysis Tests

    @Suite("MagicFixAnalysis")
    struct MagicFixAnalysisTests {

        @Test("Segment stores all properties")
        func segmentStoresProperties() {
            // Arrange & Act
            let segment = MagicFixAnalysis.Segment(
                startTime: 10.5,
                endTime: 15.0,
                description: "Introduction",
                type: .topic
            )

            // Assert
            #expect(segment.startTime == 10.5)
            #expect(segment.endTime == 15.0)
            #expect(segment.description == "Introduction")
            #expect(segment.type == .topic)
        }

        @Test("SegmentType has all expected cases")
        func segmentTypeHasAllCases() {
            // Arrange & Act
            let types: [MagicFixAnalysis.Segment.SegmentType] = [.filler, .topic, .highlight, .silence]

            // Assert
            let expectedTypes: Set<MagicFixAnalysis.Segment.SegmentType> = [.filler, .topic, .highlight, .silence]
            #expect(Set(types) == expectedTypes)
        }

        @Test("SegmentType rawValues are correct")
        func segmentTypeRawValues() {
            // Assert
            #expect(MagicFixAnalysis.Segment.SegmentType.filler.rawValue == "filler")
            #expect(MagicFixAnalysis.Segment.SegmentType.topic.rawValue == "topic")
            #expect(MagicFixAnalysis.Segment.SegmentType.highlight.rawValue == "highlight")
            #expect(MagicFixAnalysis.Segment.SegmentType.silence.rawValue == "silence")
        }

        @Test("MagicFixAnalysis stores segments")
        func storesSegments() {
            // Arrange
            let segments = [
                MagicFixAnalysis.Segment(startTime: 0, endTime: 5, description: "Intro", type: .topic),
                MagicFixAnalysis.Segment(startTime: 10, endTime: 11, description: "Um...", type: .filler)
            ]

            // Act
            let analysis = MagicFixAnalysis(segments: segments)

            // Assert
            #expect(analysis.segments.count == 2)
            #expect(analysis.segments[0].type == .topic)
            #expect(analysis.segments[1].type == .filler)
        }

        @Test("MagicFixAnalysis is Codable")
        func isCodable() throws {
            // Arrange
            let analysis = MagicFixAnalysis(segments: [
                MagicFixAnalysis.Segment(startTime: 0, endTime: 5, description: "Test", type: .highlight)
            ])

            // Act
            let data = try JSONEncoder().encode(analysis)
            let decoded = try JSONDecoder().decode(MagicFixAnalysis.self, from: data)

            // Assert
            #expect(decoded.segments.count == 1)
            #expect(decoded.segments[0].type == .highlight)
            #expect(decoded.segments[0].description == "Test")
        }

        @Test("Segment is Codable")
        func segmentIsCodable() throws {
            // Arrange
            let segment = MagicFixAnalysis.Segment(
                startTime: 12.5,
                endTime: 13.0,
                description: "Umm...",
                type: .filler
            )

            // Act
            let data = try JSONEncoder().encode(segment)
            let decoded = try JSONDecoder().decode(MagicFixAnalysis.Segment.self, from: data)

            // Assert
            #expect(decoded.startTime == 12.5)
            #expect(decoded.endTime == 13.0)
            #expect(decoded.type == .filler)
        }

        @Test("Empty segments array is valid")
        func emptySegmentsValid() {
            // Arrange & Act
            let analysis = MagicFixAnalysis(segments: [])

            // Assert
            #expect(analysis.segments.isEmpty)
        }
    }

    // MARK: - AIService Core Tests

    @Suite("AIService Core")
    @MainActor
    struct AIServiceCoreTests {

        @Test("Initializes with default provider")
        func initializesWithDefault() {
            // Arrange & Act
            let service = AIService()

            // Assert
            #expect(service.isGenerating == false)
        }

        @Test("Initializes with Apple Foundation provider")
        func initializesWithAppleFoundation() {
            // Arrange & Act
            let service = AIService(provider: .appleFoundation)

            // Assert
            #expect(service.isGenerating == false)
        }

        @Test("refineCaptions returns empty for empty input")
        func refineCaptionsReturnsEmptyForEmptyInput() async throws {
            // Arrange
            let service = AIService()

            // Act
            let result = try await service.refineCaptions([])

            // Assert
            #expect(result.isEmpty)
        }

        @Test("generateCommentaryPlan builds transcript-grounded concept cards")
        func generateCommentaryPlanBuildsDraft() async {
            let service = AIService()
            let captions = [
                Caption(
                    text: "They open by saying everyone should be impartial.",
                    startTime: CMTime(seconds: 0, preferredTimescale: 600),
                    endTime: CMTime(seconds: 3, preferredTimescale: 600)
                ),
                Caption(
                    text: "Later they argue Jake should not return to minister there.",
                    startTime: CMTime(seconds: 4, preferredTimescale: 600),
                    endTime: CMTime(seconds: 8, preferredTimescale: 600)
                )
            ]
            let brief = WorkflowBrief(
                workflow: .commentary,
                instructions: "be impartial, Jake should not return",
                maxMoments: 2
            )

            let items = await service.generateCommentaryPlan(captions: captions, brief: brief)

            #expect(items.count == 2)
            #expect(items[0].concept == "Be Impartial")
            #expect(items[0].claim.contains("impartial"))
            #expect(items[0].sourceTimestampRange == "00:00-00:03")
            #expect(items[1].concept == "Jake Should Not Return")
            #expect(items[1].claim.contains("Jake should not return"))
        }
    }

    // MARK: - Edge Cases

    @Suite("Edge Cases")
    struct EdgeCaseTests {

        @Test("MagicFixAnalysis handles many segments")
        func handlesManySegments() {
            // Arrange
            let segmentCount = 100
            var segments: [MagicFixAnalysis.Segment] = []
            for i in 0..<segmentCount {
                segments.append(MagicFixAnalysis.Segment(
                    startTime: Double(i),
                    endTime: Double(i) + 0.5,
                    description: "Segment \(i)",
                    type: i % 2 == 0 ? .topic : .filler
                ))
            }

            // Act
            let analysis = MagicFixAnalysis(segments: segments)

            // Assert
            #expect(analysis.segments.count == segmentCount)
        }

        @Test("Segment with zero duration is valid")
        func zeroDurationSegmentValid() {
            // Arrange & Act
            let segment = MagicFixAnalysis.Segment(
                startTime: 5.0,
                endTime: 5.0,
                description: "Point in time",
                type: .highlight
            )

            // Assert
            #expect(segment.startTime == segment.endTime)
        }

        @Test("AIGeneratedContent handles long text")
        func handlesLongText() {
            // Arrange
            let titleLength = 1_000
            let descriptionLength = 5_000
            let longTitle = String(repeating: "A", count: titleLength)
            let longDescription = String(repeating: "B", count: descriptionLength)

            // Act
            let content = AIGeneratedContent(title: longTitle, description: longDescription)

            // Assert
            #expect(content.title.count == titleLength)
            #expect(content.description.count == descriptionLength)
        }
    }
}
