//
//  BatchExportServiceTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import AVFoundation
import CoreMedia
@testable import SaneVideo

@Suite("Batch Export Service Tests")
struct BatchExportServiceTests {
    private final class ProgressRecorder: @unchecked Sendable {
        private let lock = NSLock()
        private var values: [Double] = []

        func append(_ value: Double) {
            lock.withLock {
                values.append(value)
            }
        }

        func snapshot() -> [Double] {
            lock.withLock {
                values
            }
        }
    }

    // MARK: - Test Setup

    var sut: BatchExportService {
        BatchExportService()
    }

    // MARK: - Initialization Tests

    @Test("Initial state is not exporting")
    func initialState() async throws {
        // Arrange & Act
        let service = sut

        // Assert - service should be created successfully
        _ = service  // Just verify it can be created
    }

    // MARK: - Export Directory Tests

    @Test("Export with empty candidates returns empty array")
    func exportEmptyCandidatesReturnsEmpty() async throws {
        // Arrange
        let service = sut
        let emptyCandidates: [ShortCandidate] = []
        let settings = RepurposingSettings()

        // Act
        let results = try await service.exportShorts(
            emptyCandidates,
            from: TestEnvironment.mockAssetURL,
            settings: settings,
            progressHandler: { _ in }
        )

        // Assert
        #expect(results.isEmpty)
    }

    // MARK: - Progress Handler Tests

    @Test("Progress handler is called during export")
    func progressHandlerIsCalled() async throws {
        // Arrange
        let service = sut
        let progressRecorder = ProgressRecorder()
        let settings = RepurposingSettings()

        // Create a minimal candidate (will fail due to no real video, but progress should be called)
        let candidate = ShortCandidate(
            timeRange: CMTimeRange(
                start: .zero,
                duration: CMTime(seconds: 1, preferredTimescale: 600)
            ),
            score: 0.5,
            highlights: []
        )

        // Act - will likely fail but should call progress
        do {
            _ = try await service.exportShorts(
                [candidate],
                from: TestEnvironment.mockAssetURL,
                settings: settings,
                progressHandler: { progress in
                    progressRecorder.append(progress)
                }
            )
        } catch {
            // Expected to fail with test asset
        }

        // Assert - progress handler should have been called at least once
        // (even if export failed)
        // Note: If asset doesn't exist, this might not call progress
        _ = progressRecorder.snapshot()
    }

    // MARK: - Cancellation Safety Tests

    @Test("Service handles rapid export calls")
    func handlesRapidExportCalls() async throws {
        // Arrange
        let service = sut
        let settings = RepurposingSettings()

        // Act - call multiple times in rapid succession (should not crash)
        async let export1 = service.exportShorts(
            [],
            from: TestEnvironment.mockAssetURL,
            settings: settings,
            progressHandler: { _ in }
        )
        async let export2 = service.exportShorts(
            [],
            from: TestEnvironment.mockAssetURL,
            settings: settings,
            progressHandler: { _ in }
        )

        // Assert - both should complete (one may throw alreadyExporting, that's expected)
        do {
            let (result1, result2) = try await (export1, export2)
            #expect(result1.isEmpty)
            #expect(result2.isEmpty)
        } catch let error as BatchExportError where error == .alreadyExporting {
            // This is expected when calling rapidly - actor prevents concurrent exports
        }
    }

    // MARK: - Error Tests

    @Test("BatchExportError has proper descriptions")
    func errorDescriptions() {
        // Arrange & Act
        let errors: [BatchExportError] = [
            .alreadyExporting,
            .outputDirectoryCreationFailed,
            .noVideoTrack,
            .compositionFailed,
            .exportSessionCreationFailed,
            .exportFailed,
            .exportCancelled
        ]

        // Assert - all errors should have descriptions
        for error in errors {
            #expect(error.errorDescription != nil)
            #expect(error.errorDescription?.isEmpty == false)
        }
    }

    @Test("Sync repair whole-track shift builds delayed audio filter")
    func syncRepairWholeTrackShiftBuildsDelayFilter() throws {
        let request = SyncRepairBuildRequest(
            inputPath: "/tmp/input.mp4",
            outputPath: "/tmp/output.mp4",
            audioTrackCount: 2,
            videoDuration: 12.0,
            primaryAudioDuration: 11.5,
            mode: .shiftWholeTrack,
            markerTime: nil,
            offsetSeconds: 1.5,
            tailTempo: 1.0
        )
        let arguments = try FFmpegService.buildSyncRepairArguments(request: request)

        let combined = arguments.joined(separator: " ")
        #expect(combined.contains("adelay=1500:all=1"))
        #expect(combined.contains("-c:v copy"))
        #expect(combined.contains("-map [a1]"))
    }

    @Test("Sync repair tail shift trims post-marker audio when moving earlier")
    func syncRepairTailShiftBuildsTrimmedPostFilter() throws {
        let request = SyncRepairBuildRequest(
            inputPath: "/tmp/input.mp4",
            outputPath: "/tmp/output.mp4",
            audioTrackCount: 1,
            videoDuration: 30.0,
            primaryAudioDuration: 29.0,
            mode: .shiftFromMarker,
            markerTime: 12.0,
            offsetSeconds: -1.25,
            tailTempo: 1.0
        )
        let arguments = try FFmpegService.buildSyncRepairArguments(request: request)

        let combined = arguments.joined(separator: " ")
        #expect(combined.contains("atrim=start=13.250"))
        #expect(combined.contains("concat=n=2:v=0:a=1"))
    }

    @Test("Sync repair trim mode copies streams to primary audio duration")
    func syncRepairTrimModeUsesPrimaryAudioDuration() throws {
        let request = SyncRepairBuildRequest(
            inputPath: "/tmp/input.mp4",
            outputPath: "/tmp/output.mp4",
            audioTrackCount: 1,
            videoDuration: 42.0,
            primaryAudioDuration: 39.25,
            mode: .trimVideoToPrimaryAudio,
            markerTime: nil,
            offsetSeconds: 0,
            tailTempo: 1.0
        )
        let arguments = try FFmpegService.buildSyncRepairArguments(request: request)

        #expect(arguments.contains("-c"))
        #expect(arguments.contains("copy"))
        #expect(arguments.contains("39.250"))
    }

    // MARK: - Helper Methods

    private func createTestVideo() -> URL {
        let testAsset = TestEnvironment.mockAssetURL
        if FileManager.default.fileExists(atPath: testAsset.path) {
            return testAsset
        }

        let tempDir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        let url = tempDir.appendingPathComponent("test_video.mp4")
        FileManager.default.createFile(atPath: url.path, contents: Data(), attributes: nil)
        return url
    }
}
