//
//  BatchExportServiceTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import AVFoundation
@testable import SaneVideo

@Suite("Batch Export Service Tests")
struct BatchExportServiceTests {

    // MARK: - Test Setup

    var sut: BatchExportService {
        BatchExportService()
    }

    // MARK: - Initialization Tests

    @Test("Initial state is not exporting")
    func initialState() async throws {
        // Arrange & Act
        let service = sut

        // Assert
        #expect(service != nil)
    }

    // MARK: - Export Directory Tests

    @Test("Export with empty candidates returns empty array")
    func exportEmptyCandidatesReturnsEmpty() async throws {
        // Arrange
        let service = sut
        let emptyCandidates: [ShortCandidate] = []

        // Act
        let results = try await service.exportShorts(
            candidates: emptyCandidates,
            sourceURL: TestEnvironment.mockAssetURL,
            progressHandler: { _ in }
        )

        // Assert
        #expect(results.isEmpty)
    }

    // MARK: - Progress Handler Tests

    @Test("Progress handler is called during export")
    func progressHandlerIsCalled() async throws {
        // Arrange
        let service = sut
        var progressValues: [Double] = []

        // Create a minimal candidate (will fail due to no real video, but progress should be called)
        let candidate = ShortCandidate(
            startTime: .zero,
            duration: CMTime(seconds: 1, preferredTimescale: 600),
            score: 0.5,
            highlights: []
        )

        // Act - will likely fail but should call progress
        do {
            _ = try await service.exportShorts(
                candidates: [candidate],
                sourceURL: TestEnvironment.mockAssetURL,
                progressHandler: { progress in
                    progressValues.append(progress)
                }
            )
        } catch {
            // Expected to fail with test asset
        }

        // Assert - progress handler should have been called at least once
        // (even if export failed)
        // Note: If asset doesn't exist, this might not call progress
    }

    // MARK: - Cancellation Safety Tests

    @Test("Service handles rapid export calls")
    func handlesRapidExportCalls() async throws {
        // Arrange
        let service = sut

        // Act - call multiple times in rapid succession (should not crash)
        async let export1 = service.exportShorts(
            candidates: [],
            sourceURL: TestEnvironment.mockAssetURL,
            progressHandler: { _ in }
        )
        async let export2 = service.exportShorts(
            candidates: [],
            sourceURL: TestEnvironment.mockAssetURL,
            progressHandler: { _ in }
        )

        // Assert - both should complete without crash
        let (result1, result2) = try await (export1, export2)
        #expect(result1.isEmpty)
        #expect(result2.isEmpty)
    }

    // MARK: - Helper Methods

    private func createTestVideo() -> URL {
        let testAsset = TestEnvironment.mockAssetURL
        if FileManager.default.fileExists(atPath: testAsset.path) {
            return testAsset
        }

        let tempDir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        let url = tempDir.appendingPathComponent("test_video.mp4")
        FileManager.default.createFile(atPath: url.path, contents: Data(), attributes: nil)
        return url
    }
}
