//
//  DiskSpaceMonitorTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
@testable import SaneVideo

@Suite("Disk Space Monitor Tests")
@MainActor
struct DiskSpaceMonitorTests {

    // MARK: - Test Setup

    var sut: DiskSpaceMonitor {
        DiskSpaceMonitor()
    }

    // MARK: - Initialization Tests

    @Test("Initial state has no monitoring task")
    func initialState() async throws {
        // Arrange & Act
        let monitor = sut

        // Assert
        #expect(monitor != nil)
    }

    @Test("Callback can be set")
    func callbackCanBeSet() async throws {
        // Arrange
        let monitor = sut
        var callbackInvoked = false

        // Act
        monitor.onLowDiskSpace = { _ in
            callbackInvoked = true
        }

        // Assert
        #expect(monitor.onLowDiskSpace != nil)
    }

    // MARK: - Start/Stop Lifecycle Tests
    // Note: DiskSpaceMonitor.monitoringTask is private, so we test through observable behavior.
    // For lifecycle tests, completion without crash/hang IS the assertion.

    @Test("Start and stop complete without error")
    func startAndStopLifecycle() async throws {
        // Arrange
        let monitor = sut
        var callbackInvoked = false
        monitor.onLowDiskSpace = { _ in callbackInvoked = true }

        // Act - start monitoring
        monitor.start()
        try await Task.sleep(nanoseconds: 100_000_000) // 100ms for task to spin up

        // Assert - verifyDiskSpace should not throw during monitoring
        // If it throws, the test fails; if it completes, the test passes
        try monitor.verifyDiskSpace()

        // Cleanup
        monitor.stop()
    }

    @Test("Double stop is idempotent")
    func doubleStopIsIdempotent() async throws {
        // Arrange
        let monitor = sut
        monitor.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Act
        monitor.stop()
        monitor.stop() // Second stop should be no-op

        // Assert - verifyDiskSpace should not throw after double stop
        try monitor.verifyDiskSpace()
    }

    @Test("Start after stop restarts cleanly")
    func startAfterStopRestarts() async throws {
        // Arrange
        let monitor = sut
        monitor.start()
        try await Task.sleep(nanoseconds: 50_000_000)
        monitor.stop()

        // Act - restart
        monitor.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - verifyDiskSpace should not throw after restart
        try monitor.verifyDiskSpace()

        // Cleanup
        monitor.stop()
    }

    // MARK: - Verify Disk Space Tests

    @Test("Verify disk space succeeds with sufficient space")
    func verifyDiskSpaceSucceeds() async throws {
        // Arrange
        let monitor = sut

        // Act & Assert - should not throw on a normal system
        try monitor.verifyDiskSpace()
    }

    @Test("Verify disk space is nonisolated")
    func verifyDiskSpaceIsNonisolated() async throws {
        // Arrange
        let monitor = sut

        // Act - call from async context (tests nonisolated attribute)
        let result = await Task.detached {
            do {
                try monitor.verifyDiskSpace()
                return true
            } catch {
                return false
            }
        }.value

        // Assert - should complete without actor isolation issues
        #expect(result == true)
    }

    // MARK: - Deallocation Tests
    // Note: This tests deinit behavior - completion without crash IS the assertion.

    @Test("Monitor cleans up on deallocation")
    func monitorCleansUpOnDeallocation() async throws {
        // Arrange
        var monitor: DiskSpaceMonitor? = DiskSpaceMonitor()
        monitor?.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Act - deallocate
        monitor = nil

        // Assert - deinit should cancel task without crash
        // After deallocation, the system should be stable
        try await Task.sleep(nanoseconds: 50_000_000)

        // Verify system is still functional by creating a new monitor
        // If verifyDiskSpace throws, the test fails
        let newMonitor = DiskSpaceMonitor()
        try newMonitor.verifyDiskSpace()
    }
}
