//
//  DiskSpaceMonitorTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
@testable import SaneVideo

@Suite("Disk Space Monitor Tests")
@MainActor
struct DiskSpaceMonitorTests {

    // MARK: - Test Setup

    var sut: DiskSpaceMonitor {
        DiskSpaceMonitor()
    }

    // MARK: - Initialization Tests

    @Test("Initial state has no monitoring task")
    func initialState() async throws {
        // Arrange & Act
        let monitor = sut

        // Assert
        #expect(monitor != nil)
    }

    @Test("Callback can be set")
    func callbackCanBeSet() async throws {
        // Arrange
        let monitor = sut
        var callbackInvoked = false

        // Act
        monitor.onLowDiskSpace = { _ in
            callbackInvoked = true
        }

        // Assert
        #expect(monitor.onLowDiskSpace != nil)
    }

    // MARK: - Start/Stop Tests

    @Test("Start begins monitoring")
    func startBeginsMonitoring() async throws {
        // Arrange
        let monitor = sut

        // Act
        monitor.start()

        // Give time for task to start
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - monitor should be running (no crash, no immediate error)
        // We can't easily inspect the private task, but we can stop it
        monitor.stop()
    }

    @Test("Stop halts monitoring")
    func stopHaltsMonitoring() async throws {
        // Arrange
        let monitor = sut
        monitor.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Act
        monitor.stop()

        // Assert - should not crash, task should be cancelled
        // Give time for cancellation to propagate
        try await Task.sleep(nanoseconds: 50_000_000)
    }

    @Test("Double stop is safe")
    func doubleStopIsSafe() async throws {
        // Arrange
        let monitor = sut
        monitor.start()

        // Act
        monitor.stop()
        monitor.stop() // Should not crash

        // Assert - no crash
    }

    @Test("Start after stop restarts monitoring")
    func startAfterStopRestarts() async throws {
        // Arrange
        let monitor = sut
        monitor.start()
        monitor.stop()

        // Act
        monitor.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - should be running again
        monitor.stop()
    }

    // MARK: - Verify Disk Space Tests

    @Test("Verify disk space succeeds with sufficient space")
    func verifyDiskSpaceSucceeds() async throws {
        // Arrange
        let monitor = sut

        // Act & Assert - should not throw on a normal system
        try monitor.verifyDiskSpace()
    }

    @Test("Verify disk space is nonisolated")
    func verifyDiskSpaceIsNonisolated() async throws {
        // Arrange
        let monitor = sut

        // Act - call from async context (tests nonisolated attribute)
        let result = await Task.detached {
            do {
                try monitor.verifyDiskSpace()
                return true
            } catch {
                return false
            }
        }.value

        // Assert - should complete without actor isolation issues
        #expect(result == true)
    }

    // MARK: - Deallocation Tests

    @Test("Monitor stops on deallocation")
    func monitorStopsOnDeallocation() async throws {
        // Arrange
        var monitor: DiskSpaceMonitor? = DiskSpaceMonitor()
        monitor?.start()
        try await Task.sleep(nanoseconds: 50_000_000)

        // Act
        monitor = nil

        // Assert - should not crash, task should be cancelled in deinit
        try await Task.sleep(nanoseconds: 50_000_000)
    }
}
