//
//  MagicFixServiceTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import Foundation
import CoreMedia
@testable import SaneVideo

@Suite("MagicFixService Tests")
struct MagicFixServiceTests {

    // MARK: - Calculate Keep Ranges Tests

    @Suite("Calculate Keep Ranges")
    struct CalculateKeepRangesTests {

        @Test("No removals returns full duration as keep range")
        func noRemovalsReturnsFull() {
            // Arrange
            let removals: [CMTimeRange] = []
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 1)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 60)
        }

        @Test("Single removal at start")
        func singleRemovalAtStart() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 0, preferredTimescale: 600),
                    end: CMTime(seconds: 5, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 1)
            #expect(keepRanges[0].start.seconds == 5)
            #expect(keepRanges[0].end.seconds == 60)
        }

        @Test("Single removal at end")
        func singleRemovalAtEnd() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 55, preferredTimescale: 600),
                    end: CMTime(seconds: 60, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 1)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 55)
        }

        @Test("Single removal in middle")
        func singleRemovalInMiddle() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 20, preferredTimescale: 600),
                    end: CMTime(seconds: 30, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 2)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 20)
            #expect(keepRanges[1].start.seconds == 30)
            #expect(keepRanges[1].end.seconds == 60)
        }

        @Test("Multiple non-overlapping removals")
        func multipleNonOverlappingRemovals() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 15, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 30, preferredTimescale: 600),
                    end: CMTime(seconds: 35, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 3)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 10)
            #expect(keepRanges[1].start.seconds == 15)
            #expect(keepRanges[1].end.seconds == 30)
            #expect(keepRanges[2].start.seconds == 35)
            #expect(keepRanges[2].end.seconds == 60)
        }

        @Test("Overlapping removals are consolidated")
        func overlappingRemovalsConsolidated() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 20, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 15, preferredTimescale: 600),
                    end: CMTime(seconds: 25, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 2)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 10)
            #expect(keepRanges[1].start.seconds == 25)
            #expect(keepRanges[1].end.seconds == 60)
        }

        @Test("Adjacent removals are consolidated")
        func adjacentRemovalsConsolidated() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 20, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 20, preferredTimescale: 600),
                    end: CMTime(seconds: 30, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 2)
            #expect(keepRanges[0].end.seconds == 10)
            #expect(keepRanges[1].start.seconds == 30)
        }

        @Test("Removal covering full duration returns empty")
        func fullRemovalReturnsEmpty() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 0, preferredTimescale: 600),
                    end: CMTime(seconds: 60, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.isEmpty)
        }

        @Test("Unsorted removals are handled correctly")
        func unsortedRemovalsHandled() {
            // Arrange - removals not in order
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 30, preferredTimescale: 600),
                    end: CMTime(seconds: 35, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 15, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert - should still work correctly
            #expect(keepRanges.count == 3)
        }
    }

    // MARK: - Calculate Removed Ranges Tests

    @Suite("Calculate Removed Ranges")
    struct CalculateRemovedRangesTests {

        @Test("No keep ranges means everything removed")
        func noKeepRangesMeansFullRemoval() {
            // Arrange
            let keepRanges: [CMTimeRange] = []
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.count == 1)
            #expect(removedRanges[0].start.seconds == 0)
            #expect(removedRanges[0].end.seconds == 60)
        }

        @Test("Full keep range means nothing removed")
        func fullKeepRangeMeansNoRemoval() {
            // Arrange
            let keepRanges = [
                CMTimeRange(
                    start: CMTime(seconds: 0, preferredTimescale: 600),
                    end: CMTime(seconds: 60, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.isEmpty)
        }

        @Test("Gap at start is removed")
        func gapAtStartRemoved() {
            // Arrange
            let keepRanges = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 60, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.count == 1)
            #expect(removedRanges[0].start.seconds == 0)
            #expect(removedRanges[0].end.seconds == 10)
        }

        @Test("Gap at end is removed")
        func gapAtEndRemoved() {
            // Arrange
            let keepRanges = [
                CMTimeRange(
                    start: CMTime(seconds: 0, preferredTimescale: 600),
                    end: CMTime(seconds: 50, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.count == 1)
            #expect(removedRanges[0].start.seconds == 50)
            #expect(removedRanges[0].end.seconds == 60)
        }

        @Test("Gap in middle is removed")
        func gapInMiddleRemoved() {
            // Arrange
            let keepRanges = [
                CMTimeRange(
                    start: CMTime(seconds: 0, preferredTimescale: 600),
                    end: CMTime(seconds: 20, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 40, preferredTimescale: 600),
                    end: CMTime(seconds: 60, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.count == 1)
            #expect(removedRanges[0].start.seconds == 20)
            #expect(removedRanges[0].end.seconds == 40)
        }

        @Test("Multiple gaps are all removed")
        func multipleGapsRemoved() {
            // Arrange
            let keepRanges = [
                CMTimeRange(
                    start: CMTime(seconds: 5, preferredTimescale: 600),
                    end: CMTime(seconds: 15, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 25, preferredTimescale: 600),
                    end: CMTime(seconds: 35, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 45, preferredTimescale: 600),
                    end: CMTime(seconds: 55, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let removedRanges = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert
            #expect(removedRanges.count == 4)
            // Gap at start: 0-5
            #expect(removedRanges[0].start.seconds == 0)
            #expect(removedRanges[0].end.seconds == 5)
            // Gap between first and second: 15-25
            #expect(removedRanges[1].start.seconds == 15)
            #expect(removedRanges[1].end.seconds == 25)
            // Gap between second and third: 35-45
            #expect(removedRanges[2].start.seconds == 35)
            #expect(removedRanges[2].end.seconds == 45)
            // Gap at end: 55-60
            #expect(removedRanges[3].start.seconds == 55)
            #expect(removedRanges[3].end.seconds == 60)
        }
    }

    // MARK: - Roundtrip Tests

    @Suite("Roundtrip Tests")
    struct RoundtripTests {

        @Test("Keep to remove to keep is consistent")
        func keepToRemoveToKeepRoundtrip() {
            // Arrange
            let originalRemovals = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 20, preferredTimescale: 600)
                ),
                CMTimeRange(
                    start: CMTime(seconds: 40, preferredTimescale: 600),
                    end: CMTime(seconds: 50, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: originalRemovals, duration: duration)
            let recoveredRemovals = MagicFixService.calculateRemovedRanges(from: keepRanges, duration: duration)

            // Assert - recovered removals should match original
            #expect(recoveredRemovals.count == originalRemovals.count)
            for (recovered, original) in zip(recoveredRemovals, originalRemovals) {
                #expect(abs(recovered.start.seconds - original.start.seconds) < 0.001)
                #expect(abs(recovered.end.seconds - original.end.seconds) < 0.001)
            }
        }
    }

    // MARK: - Edge Cases

    @Suite("Edge Cases")
    struct EdgeCaseTests {

        @Test("Zero duration handled gracefully")
        func zeroDurationHandled() {
            // Arrange
            let removals: [CMTimeRange] = []
            let duration = CMTime.zero

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert - should not crash
            #expect(keepRanges.isEmpty)
        }

        @Test("Very small removal ranges")
        func verySmallRemovalRanges() {
            // Arrange - 100ms removal
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 10, preferredTimescale: 600),
                    end: CMTime(seconds: 10.1, preferredTimescale: 600)
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert
            #expect(keepRanges.count == 2)
        }

        @Test("Many small removals")
        func manySmallRemovals() {
            // Arrange - 10 small removals
            var removals: [CMTimeRange] = []
            for i in 0..<10 {
                let start = Double(i * 6)
                removals.append(CMTimeRange(
                    start: CMTime(seconds: start, preferredTimescale: 600),
                    end: CMTime(seconds: start + 1, preferredTimescale: 600)
                ))
            }
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert - should have 10 keep ranges (between each removal) + 1 at end
            #expect(keepRanges.count == 10)
        }

        @Test("Removal extending beyond duration is clipped")
        func removalBeyondDurationClipped() {
            // Arrange
            let removals = [
                CMTimeRange(
                    start: CMTime(seconds: 50, preferredTimescale: 600),
                    end: CMTime(seconds: 100, preferredTimescale: 600)  // Beyond 60s duration
                )
            ]
            let duration = CMTime(seconds: 60, preferredTimescale: 600)

            // Act
            let keepRanges = MagicFixService.calculateKeepRanges(removals: removals, duration: duration)

            // Assert - should keep 0-50
            #expect(keepRanges.count == 1)
            #expect(keepRanges[0].start.seconds == 0)
            #expect(keepRanges[0].end.seconds == 50)
        }
    }

    // MARK: - MagicFixOptions Tests

    @Suite("MagicFixOptions")
    struct MagicFixOptionsTests {

        @Test("Default options have expected values")
        func defaultOptions() {
            // Arrange & Act
            let options = MagicFixOptions()

            // Assert - check defaults match expected values
            #expect(options.removeSilence == true)
            #expect(options.removeFillers == true)
            #expect(options.generateCaptions == true)
            #expect(options.enhanceAudio == true)
            #expect(options.autoEnhance == false)
            #expect(options.silenceThreshold == -45.0)
            #expect(options.minSilenceDuration == 0.3)
        }

        @Test("Minimal preset has expected values")
        func minimalPreset() {
            // Arrange & Act
            let options = MagicFixOptions.minimal

            // Assert
            #expect(options.removeSilence == true)
            #expect(options.removeFillers == false)
            #expect(options.generateCaptions == false)
            #expect(options.enhanceAudio == false)
            #expect(options.presetName == "Minimal Fix")
        }

        @Test("Pro Clean preset has expected values")
        func proCleanPreset() {
            // Arrange & Act
            let options = MagicFixOptions.proClean

            // Assert - 5 core cleanup features (2025-12-31 simplification)
            #expect(options.removeSilence == true)
            #expect(options.removeFillers == true)
            #expect(options.generateCaptions == true)
            #expect(options.enhanceAudio == true)
            #expect(options.smoothJumpCuts == true)
            // autoEnhance and findHighlights moved to canonical UI locations
            #expect(options.autoEnhance == false)
            #expect(options.findHighlights == false)
            #expect(options.presetName == "Pro Clean-up")
        }

        @Test("Social Media preset has expected values")
        func socialMediaPreset() {
            // Arrange & Act
            let options = MagicFixOptions.socialMedia

            // Assert
            #expect(options.smartCrop == true)
            #expect(options.autoFraming == true)
            #expect(options.presetName == "Social Media Ready")
        }

        @Test("Options isEmpty returns false when options selected")
        func isEmptyWhenOptionsSelected() {
            // Arrange
            let options = MagicFixOptions()

            // Assert
            #expect(options.isEmpty == false)
        }

        @Test("Options summary lists selected features")
        func summaryListsFeatures() {
            // Arrange
            let options = MagicFixOptions.minimal

            // Assert - minimal only has silence
            #expect(options.summary.contains("Silence"))
        }
    }
}
