//
//  MediaAssetManagerTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Foundation
@testable import SaneVideo
import Testing

@Suite("MediaAssetManager Tests")
struct MediaAssetManagerTests {
    // MARK: - MediaAssetReference Tests

    @Suite("MediaAssetReference")
    struct MediaAssetReferenceTests {
        @Test("Creates reference with all properties")
        func createWithAllProperties() {
            // Arrange & Act
            let expectedFileSize: Int64 = 1024
            let reference = MediaAssetReference(
                originalFilename: "video.mp4",
                relativePath: "Media/123/video.mp4",
                fileSize: expectedFileSize,
                checksum: "abc123"
            )

            // Assert
            #expect(reference.originalFilename == "video.mp4")
            #expect(reference.relativePath == "Media/123/video.mp4")
            #expect(reference.fileSize == expectedFileSize)
            #expect(reference.checksum == "abc123")
        }

        @Test("Creates reference with minimal properties")
        func createWithMinimalProperties() {
            // Arrange & Act
            let reference = MediaAssetReference(
                originalFilename: "audio.m4a",
                relativePath: "Media/audio.m4a"
            )

            // Assert
            #expect(reference.originalFilename == "audio.m4a")
            #expect(reference.relativePath == "Media/audio.m4a")
            #expect(reference.fileSize == nil)
            #expect(reference.checksum == nil)
        }

        @Test("Equatable conformance works correctly")
        func equatableConformance() {
            // Arrange
            let ref1 = MediaAssetReference(
                originalFilename: "video.mp4",
                relativePath: "Media/video.mp4",
                fileSize: 1024,
                checksum: "abc"
            )
            let ref2 = MediaAssetReference(
                originalFilename: "video.mp4",
                relativePath: "Media/video.mp4",
                fileSize: 1024,
                checksum: "abc"
            )
            let ref3 = MediaAssetReference(
                originalFilename: "other.mp4",
                relativePath: "Media/other.mp4",
                fileSize: 2048,
                checksum: "xyz"
            )

            // Assert
            #expect(ref1 == ref2)
            #expect(ref1 != ref3)
        }

        @Test("Codable conformance for encoding")
        func codableEncoding() throws {
            // Arrange
            let reference = MediaAssetReference(
                originalFilename: "test.mp4",
                relativePath: "Media/test.mp4",
                fileSize: 512,
                checksum: "hash123"
            )

            // Act
            let data = try JSONEncoder().encode(reference)
            let decoded = try JSONDecoder().decode(MediaAssetReference.self, from: data)

            // Assert
            #expect(decoded == reference)
        }

        @Test("Codable handles nil optional properties")
        func codableWithNils() throws {
            // Arrange
            let reference = MediaAssetReference(
                originalFilename: "test.mp4",
                relativePath: "Media/test.mp4"
            )

            // Act
            let data = try JSONEncoder().encode(reference)
            let decoded = try JSONDecoder().decode(MediaAssetReference.self, from: data)

            // Assert
            #expect(decoded.fileSize == nil)
            #expect(decoded.checksum == nil)
        }
    }

    // MARK: - Path Conversion Tests

    @Suite("Path Conversion")
    struct PathConversionTests {
        @Test("Relative path from file within project directory")
        func relativePathWithinProject() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/Users/test/Projects/MyProject")
            let fileURL = URL(fileURLWithPath: "/Users/test/Projects/MyProject/Media/video.mp4")

            // Act
            let relativePath = await manager.relativePath(from: fileURL, projectDir: projectDir)

            // Assert
            #expect(relativePath == "Media/video.mp4")
        }

        @Test("Relative path from nested subdirectory")
        func relativePathFromNestedSubdir() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/Users/test/Projects/MyProject")
            let fileURL = URL(fileURLWithPath: "/Users/test/Projects/MyProject/Assets/Raw/clip001.mp4")

            // Act
            let relativePath = await manager.relativePath(from: fileURL, projectDir: projectDir)

            // Assert
            #expect(relativePath == "Assets/Raw/clip001.mp4")
        }

        @Test("Relative path from external file uses Media prefix")
        func relativePathFromExternalFile() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/Users/test/Projects/MyProject")
            let externalURL = URL(fileURLWithPath: "/Users/test/Downloads/external_video.mp4")

            // Act
            let relativePath = await manager.relativePath(from: externalURL, projectDir: projectDir)

            // Assert
            #expect(relativePath == "Media/external_video.mp4")
        }

        @Test("Relative path handles special characters in filename")
        func relativePathWithSpecialCharacters() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/Users/test/Projects/MyProject")
            let fileURL = URL(fileURLWithPath: "/Users/test/Downloads/video with spaces (1).mp4")
            let expectedRelativePath = "Media/video with spaces (1).mp4"

            // Act
            let relativePath = await manager.relativePath(from: fileURL, projectDir: projectDir)

            // Assert
            #expect(relativePath == expectedRelativePath)
        }

        @Test("Relative path from project root file")
        func relativePathFromProjectRoot() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/Users/test/Projects/MyProject")
            let fileURL = URL(fileURLWithPath: "/Users/test/Projects/MyProject/main.mp4")

            // Act
            let relativePath = await manager.relativePath(from: fileURL, projectDir: projectDir)

            // Assert
            #expect(relativePath == "main.mp4")
        }
    }

    // MARK: - Asset Resolution Tests

    @Suite("Asset Resolution")
    struct AssetResolutionTests {
        @Test("Resolve asset from project directory")
        func resolveFromProjectDir() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("MediaAssetTest_\(UUID().uuidString)")
            let projectDir = tempDir.appendingPathComponent("Project")
            let mediaDir = projectDir.appendingPathComponent("Media")

            try FileManager.default.createDirectory(at: mediaDir, withIntermediateDirectories: true)
            let testFile = mediaDir.appendingPathComponent("test.mp4")
            try "test content".write(to: testFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let resolved = await manager.resolveAsset(relativePath: "Media/test.mp4", projectDir: projectDir)

            // Assert
            #expect(resolved != nil)
            #expect(resolved?.lastPathComponent == "test.mp4")
        }

        @Test("Resolve asset returns nil for missing file")
        func resolveReturnNilForMissing() async {
            // Arrange
            let manager = MediaAssetManager()
            let projectDir = URL(fileURLWithPath: "/nonexistent/project")

            // Act
            let resolved = await manager.resolveAsset(relativePath: "Media/missing.mp4", projectDir: projectDir)

            // Assert
            #expect(resolved == nil)
        }

        @Test("Resolve asset from nested path")
        func resolveFromNestedPath() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("MediaAssetTest_\(UUID().uuidString)")
            let projectDir = tempDir.appendingPathComponent("Project")
            let nestedDir = projectDir.appendingPathComponent("Assets/Raw/2024")

            try FileManager.default.createDirectory(at: nestedDir, withIntermediateDirectories: true)
            let testFile = nestedDir.appendingPathComponent("clip.mp4")
            try "content".write(to: testFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let resolved = await manager.resolveAsset(
                relativePath: "Assets/Raw/2024/clip.mp4",
                projectDir: projectDir
            )

            // Assert
            #expect(resolved != nil)
            #expect(resolved?.lastPathComponent == "clip.mp4")
        }
    }

    // MARK: - Asset Reference Creation Tests

    @Suite("Asset Reference Creation")
    struct AssetReferenceCreationTests {
        @Test("Create asset reference captures file size")
        func createReferenceWithFileSize() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("MediaAssetTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let testFile = tempDir.appendingPathComponent("video.mp4")
            let testData = Data(repeating: 0xAB, count: 1024)
            try testData.write(to: testFile)
            let expectedFileSize = Int64(testData.count)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(
                from: testFile,
                projectId: UUID()
            )

            // Assert
            #expect(reference.fileSize == expectedFileSize)
            #expect(reference.originalFilename == "video.mp4")
        }

        @Test("Create asset reference computes checksum")
        func createReferenceWithChecksum() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("MediaAssetTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let testFile = tempDir.appendingPathComponent("video.mp4")
            try "test content for hashing".write(to: testFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(
                from: testFile,
                projectId: UUID()
            )

            // Assert
            let expectedChecksumLength = 64
            #expect(reference.checksum != nil)
            #expect(reference.checksum?.isEmpty == false)
            #expect(reference.checksum?.count == expectedChecksumLength) // SHA256 hex = 64 chars
        }

        @Test("Create asset reference uses project ID in path")
        func createReferenceWithProjectId() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("MediaAssetTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let testFile = tempDir.appendingPathComponent("video.mp4")
            try "content".write(to: testFile, atomically: true, encoding: .utf8)

            let projectId = UUID()

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(
                from: testFile,
                projectId: projectId
            )

            // Assert
            #expect(reference.relativePath.contains(projectId.uuidString))
            #expect(reference.relativePath.hasPrefix("Media/"))
        }

        @Test("Create asset reference throws for nonexistent file")
        func createReferenceThrowsForMissingFile() async {
            // Arrange
            let manager = MediaAssetManager()
            let missingFile = URL(fileURLWithPath: "/nonexistent/file.mp4")

            // Act & Assert
            await #expect(throws: Error.self) {
                try await manager.createAssetReference(from: missingFile, projectId: UUID())
            }
        }
    }

    // MARK: - iCloud Availability Tests

    @Suite("iCloud Availability")
    struct ICloudAvailabilityTests {
        @Test("isICloudAvailable returns a definitive boolean result")
        func isICloudAvailableReturnsBool() async {
            // Arrange
            let manager = MediaAssetManager()

            // Act
            let available = await manager.isICloudAvailable

            // Assert - result is deterministic (either true or false, not some intermediate)
            #expect(available == true || available == false, "iCloud availability should be a definitive true or false")
        }
    }

    // MARK: - Error Type Tests

    @Suite("MediaAssetError")
    struct MediaAssetErrorTests {
        @Test("iCloudNotAvailable has description")
        func iCloudNotAvailableDescription() {
            // Arrange & Act
            let error = MediaAssetError.iCloudNotAvailable

            // Assert
            #expect(error.errorDescription?.isEmpty == false)
            #expect(error.errorDescription?.contains("iCloud") == true)
        }

        @Test("downloadTimeout has description")
        func downloadTimeoutDescription() {
            // Arrange & Act
            let error = MediaAssetError.downloadTimeout

            // Assert
            #expect(error.errorDescription?.isEmpty == false)
            #expect(error.errorDescription?.lowercased().contains("timed") == true)
        }

        @Test("checksumMismatch has description")
        func checksumMismatchDescription() {
            // Arrange & Act
            let error = MediaAssetError.checksumMismatch

            // Assert
            #expect(error.errorDescription?.isEmpty == false)
            #expect(error.errorDescription?.lowercased().contains("integrity") == true ||
                error.errorDescription?.lowercased().contains("corrupt") == true)
        }

        @Test("fileNotFound has description")
        func fileNotFoundDescription() {
            // Arrange & Act
            let error = MediaAssetError.fileNotFound

            // Assert
            #expect(error.errorDescription?.isEmpty == false)
            #expect(error.errorDescription?.lowercased().contains("found") == true)
        }

        @Test("copyFailed has description")
        func copyFailedDescription() {
            // Arrange & Act
            let error = MediaAssetError.copyFailed

            // Assert
            #expect(error.errorDescription?.isEmpty == false)
            #expect(error.errorDescription?.lowercased().contains("copy") == true)
        }

        @Test("All errors are distinct")
        func allErrorsAreDistinct() {
            // Arrange
            let errors: [MediaAssetError] = [
                .iCloudNotAvailable,
                .downloadTimeout,
                .checksumMismatch,
                .fileNotFound,
                .copyFailed,
            ]

            // Act & Assert
            let descriptions = errors.compactMap(\.errorDescription)
            let uniqueDescriptions = Set(descriptions)

            #expect(uniqueDescriptions.count == errors.count)
        }
    }

    // MARK: - Checksum Consistency Tests

    @Suite("Checksum Consistency")
    struct ChecksumConsistencyTests {
        @Test("Same content produces same checksum")
        func sameContentSameChecksum() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("ChecksumTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let content = "identical content for both files"
            let file1 = tempDir.appendingPathComponent("file1.txt")
            let file2 = tempDir.appendingPathComponent("file2.txt")

            try content.write(to: file1, atomically: true, encoding: .utf8)
            try content.write(to: file2, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let ref1 = try await manager.createAssetReference(from: file1, projectId: UUID())
            let ref2 = try await manager.createAssetReference(from: file2, projectId: UUID())

            // Assert
            #expect(ref1.checksum == ref2.checksum)
        }

        @Test("Different content produces different checksum")
        func differentContentDifferentChecksum() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("ChecksumTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let file1 = tempDir.appendingPathComponent("file1.txt")
            let file2 = tempDir.appendingPathComponent("file2.txt")

            try "content A".write(to: file1, atomically: true, encoding: .utf8)
            try "content B".write(to: file2, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let ref1 = try await manager.createAssetReference(from: file1, projectId: UUID())
            let ref2 = try await manager.createAssetReference(from: file2, projectId: UUID())

            // Assert
            #expect(ref1.checksum != ref2.checksum)
        }

        @Test("Empty file has valid checksum")
        func emptyFileHasChecksum() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("ChecksumTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
            let expectedChecksumLength = 64

            let emptyFile = tempDir.appendingPathComponent("empty.txt")
            try Data().write(to: emptyFile)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: emptyFile, projectId: UUID())

            // Assert
            #expect(reference.checksum != nil)
            #expect(reference.checksum?.count == expectedChecksumLength)
        }

        @Test("Large file computes checksum correctly")
        func largeFileChecksum() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("ChecksumTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            // 1MB of data
            let expectedSize = 1024 * 1024
            let expectedChecksumLength = 64
            let largeFile = tempDir.appendingPathComponent("large.bin")
            let largeData = Data(repeating: 0x42, count: expectedSize)
            try largeData.write(to: largeFile)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: largeFile, projectId: UUID())

            // Assert
            #expect(reference.checksum != nil)
            #expect(reference.checksum?.count == expectedChecksumLength)
            #expect(reference.fileSize == Int64(expectedSize))
        }
    }

    // MARK: - Edge Case Tests

    @Suite("Edge Cases")
    struct EdgeCaseTests {
        @Test("Handles file with no extension")
        func fileWithNoExtension() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("EdgeCaseTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let noExtFile = tempDir.appendingPathComponent("noextension")
            try "content".write(to: noExtFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: noExtFile, projectId: UUID())

            // Assert
            #expect(reference.originalFilename == "noextension")
        }

        @Test("Handles file with multiple extensions")
        func fileWithMultipleExtensions() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("EdgeCaseTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let multiExtFile = tempDir.appendingPathComponent("archive.tar.gz")
            try "content".write(to: multiExtFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: multiExtFile, projectId: UUID())

            // Assert
            #expect(reference.originalFilename == "archive.tar.gz")
        }

        @Test("Handles Unicode filename")
        func unicodeFilename() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("EdgeCaseTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let unicodeFile = tempDir.appendingPathComponent("日本語ファイル.mp4")
            try "content".write(to: unicodeFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: unicodeFile, projectId: UUID())

            // Assert
            #expect(reference.originalFilename == "日本語ファイル.mp4")
        }

        @Test("Handles very long filename")
        func veryLongFilename() async throws {
            // Arrange
            let manager = MediaAssetManager()
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("EdgeCaseTest_\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let longName = String(repeating: "a", count: 200) + ".mp4"
            let longFile = tempDir.appendingPathComponent(longName)
            try "content".write(to: longFile, atomically: true, encoding: .utf8)

            defer {
                try? FileManager.default.removeItem(at: tempDir)
            }

            // Act
            let reference = try await manager.createAssetReference(from: longFile, projectId: UUID())

            // Assert
            #expect(reference.originalFilename == longName)
        }
    }
}
