//
//  RecordingEngineTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import AVFoundation
@testable import SaneVideo

@Suite("Recording Engine Tests")
@MainActor
struct RecordingEngineTests {

    // MARK: - Test Setup

    var sut: RecordingEngine {
        RecordingEngine()
    }

    // MARK: - Initial State Tests

    @Test("Initial state has correct defaults")
    func initialState() async throws {
        // Arrange
        let engine = sut

        // Act - access state via RecordingActor
        let isRecording = await engine.isRecording
        let isPaused = await engine.isPaused
        let currentSource = await engine.currentSource

        // Assert
        #expect(isRecording == false)
        #expect(isPaused == false)
        #expect(currentSource == .camera)
    }

    @Test("Disk space monitor is initialized")
    func diskSpaceMonitorInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.diskSpaceMonitor != nil)
    }

    @Test("Screen preview layer is initialized")
    func screenPreviewLayerInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.screenPreviewLayer != nil)
        #expect(engine.screenPreviewLayer.videoGravity == .resizeAspectFill)
    }

    // MARK: - Recording Lifecycle Tests

    @Test("Start recording sets isRecording flag")
    func startRecordingSetsFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == true)
    }

    @Test("Stop recording clears isRecording flag")
    func stopRecordingClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        _ = await engine.stopRecording()

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == false)
    }

    @Test("Pause sets isPaused flag")
    func pauseSetsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        await engine.pause()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == true)
    }

    @Test("Resume clears isPaused flag")
    func resumeClearsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        await engine.pause()

        // Act
        await engine.resume()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == false)
    }

    // MARK: - Mic Muting Tests

    @Test("Set muted updates isMicMuted")
    func setMutedUpdatesFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.setMuted(true)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == true)
    }

    @Test("Unmute clears isMicMuted")
    func unmuteClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.setMuted(true)

        // Act
        await engine.setMuted(false)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == false)
    }

    // MARK: - Callback Tests

    @Test("Error callback can be set")
    func errorCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut
        var errorReceived = false

        // Act
        engine.onError = { _ in
            errorReceived = true
        }

        // Assert
        #expect(engine.onError != nil)
    }

    @Test("Presenter overlay callback can be set")
    func presenterOverlayCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onPresenterOverlayChanged = { _ in }

        // Assert
        #expect(engine.onPresenterOverlayChanged != nil)
    }

    @Test("Content selected callback can be set")
    func contentSelectedCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onContentSelected = { }

        // Assert
        #expect(engine.onContentSelected != nil)
    }

    // MARK: - Double Stop Prevention Tests

    @Test("Double stop is prevented")
    func doubleStopPrevented() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - stop twice quickly
        async let stop1 = engine.stopRecording()
        async let stop2 = engine.stopRecording()
        _ = await (stop1, stop2)

        // Assert
        let isRecording = await engine.isRecording
        let isStopping = await engine.isStopping
        #expect(isRecording == false)
        #expect(isStopping == false)
    }

    // MARK: - Time Coordinator Tests

    @Test("Time coordinator is initialized")
    func timeCoordinatorInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert - access via actor isolation
        let coordinator = await engine.timeCoordinator
        #expect(coordinator != nil)
    }

    // MARK: - Audio Level Subject Tests

    @Test("Audio level subject is available")
    func audioLevelSubjectAvailable() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.audioLevelSubject != nil)
    }

    // MARK: - Guard Condition Tests

    @Test("Cannot start recording when already recording")
    func cannotStartWhenRecording() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let wasRecording = await engine.isRecording
        #expect(wasRecording == true)

        // Act - try to start again
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - should still be recording with original source
        let stillRecording = await engine.isRecording
        let source = await engine.currentSource
        #expect(stillRecording == true)
        #expect(source == .camera) // Original source preserved

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Stop returns nil when not recording")
    func stopReturnsNilWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let isRecording = await engine.isRecording
        #expect(isRecording == false)

        // Act
        let result = await engine.stopRecording()

        // Assert
        #expect(result == nil)
    }

    @Test("Pause does nothing when not recording")
    func pauseIgnoredWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let wasRecording = await engine.isRecording
        #expect(wasRecording == false)

        // Act
        await engine.pause()

        // Assert - isPaused should still be false
        let isPaused = await engine.isPaused
        #expect(isPaused == false)
    }

    @Test("Resume does nothing when not paused")
    func resumeIgnoredWhenNotPaused() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let isPausedBefore = await engine.isPaused
        #expect(isPausedBefore == false)

        // Act
        await engine.resume()

        // Assert - no change
        let isPausedAfter = await engine.isPaused
        #expect(isPausedAfter == false)

        // Cleanup
        _ = await engine.stopRecording()
    }

    // MARK: - Source Tests

    @Test("Can start with camera source")
    func canStartWithCamera() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let source = await engine.currentSource
        #expect(source == .camera)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Can start with screen source")
    func canStartWithScreen() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let source = await engine.currentSource
        #expect(source == .screen)

        // Cleanup
        _ = await engine.stopRecording()
    }

    // MARK: - isStopping Flag Tests

    @Test("isStopping prevents restart during stop")
    func isStoppingPreventsRestart() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - start stop and immediately try to start again
        async let stopTask = engine.stopRecording()
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay
        await engine.startRecording(initialSource: .camera)
        _ = await stopTask

        // Assert - should not be recording (start was blocked by isStopping)
        let isRecording = await engine.isRecording
        let isStopping = await engine.isStopping
        #expect(isStopping == false) // Should be cleared after stop completes
    }

    // MARK: - TestEnvironment Mode Tests

    @Test("Test mode generates mock file URL")
    func testModeGeneratesMockURL() async throws {
        // Note: This tests the TestEnvironment.isTesting path
        // When isTesting is true, a mock URL is generated instead of real recording

        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let url = await engine.stopRecording()

        // Assert - in test mode, should return a URL
        // (actual file may or may not exist depending on TestEnvironment)
        if TestEnvironment.isTesting {
            #expect(url != nil)
        }
    }

    // MARK: - Source Switching Edge Case Tests

    @Test("Cannot switch source when not recording")
    func cannotSwitchWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let isRecording = await engine.isRecording
        #expect(isRecording == false)

        // Act - try to switch source when not recording
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - should still be on default source (no change)
        let source = await engine.currentSource
        #expect(source == .camera) // Default source
    }

    @Test("Cannot switch to same source")
    func cannotSwitchToSameSource() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let initialSource = await engine.currentSource
        #expect(initialSource == .camera)

        // Act - try to switch to same source
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - isSwitching should NOT be set (request was ignored)
        let isSwitching = await engine.isSwitching
        let source = await engine.currentSource
        #expect(isSwitching == false)
        #expect(source == .camera)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Switch source from camera to screen")
    func switchFromCameraToScreen() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - switch to screen
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 200_000_000) // Allow time for switch

        // Assert - pendingSource should be set or switch completed
        let pendingSource = await engine.pendingSource
        let currentSource = await engine.currentSource
        // Either switch is complete (currentSource == .screen) or in progress (pendingSource == .screen)
        let switchInitiated = (currentSource == .screen) || (pendingSource == .screen)
        #expect(switchInitiated == true)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Switch source from screen to camera")
    func switchFromScreenToCamera() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - switch to camera
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 200_000_000) // Allow time for switch

        // Assert - pendingSource should be set or switch completed
        let pendingSource = await engine.pendingSource
        let currentSource = await engine.currentSource
        // Either switch is complete (currentSource == .camera) or in progress (pendingSource == .camera)
        let switchInitiated = (currentSource == .camera) || (pendingSource == .camera)
        #expect(switchInitiated == true)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Concurrent switch requests are blocked")
    func concurrentSwitchRequestsBlocked() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - initiate first switch
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay

        // Try to initiate second switch while first is in progress
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - second switch should be blocked, pendingSource should be .screen (first request)
        let pendingSource = await engine.pendingSource
        if pendingSource != nil {
            #expect(pendingSource == .screen) // First switch should win
        }

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Cannot switch source while stopping")
    func cannotSwitchWhileStopping() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - start stop and immediately try to switch
        async let stopTask = engine.stopRecording()
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay
        engine.switchSource(source: .screen)
        _ = await stopTask

        // Assert - should not be switching, stop should complete normally
        let isSwitching = await engine.isSwitching
        let isRecording = await engine.isRecording
        #expect(isSwitching == false)
        #expect(isRecording == false)
    }
}
