//
//  RecordingEngineTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import AVFoundation
@testable import SaneVideo

@Suite("Recording Engine Tests")
@MainActor
struct RecordingEngineTests {

    // MARK: - Test Setup

    var sut: RecordingEngine {
        RecordingEngine()
    }

    // MARK: - Initial State Tests

    @Test("Initial state has correct defaults")
    func initialState() async throws {
        // Arrange
        let engine = sut

        // Act - access state via RecordingActor
        let isRecording = await engine.isRecording
        let isPaused = await engine.isPaused
        let currentSource = await engine.currentSource

        // Assert
        #expect(isRecording == false)
        #expect(isPaused == false)
        #expect(currentSource == .camera)
    }

    @Test("Disk space monitor is initialized")
    func diskSpaceMonitorInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.diskSpaceMonitor != nil)
    }

    @Test("Screen preview layer is initialized")
    func screenPreviewLayerInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.screenPreviewLayer != nil)
        #expect(engine.screenPreviewLayer.videoGravity == .resizeAspectFill)
    }

    // MARK: - Recording Lifecycle Tests

    @Test("Start recording sets isRecording flag")
    func startRecordingSetsFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == true)
    }

    @Test("Stop recording clears isRecording flag")
    func stopRecordingClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        _ = await engine.stopRecording()

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == false)
    }

    @Test("Pause sets isPaused flag")
    func pauseSetsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        await engine.pause()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == true)
    }

    @Test("Resume clears isPaused flag")
    func resumeClearsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        await engine.pause()

        // Act
        await engine.resume()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == false)
    }

    // MARK: - Mic Muting Tests

    @Test("Set muted updates isMicMuted")
    func setMutedUpdatesFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.setMuted(true)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == true)
    }

    @Test("Unmute clears isMicMuted")
    func unmuteClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.setMuted(true)

        // Act
        await engine.setMuted(false)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == false)
    }

    // MARK: - Callback Tests

    @Test("Error callback can be set")
    func errorCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut
        var errorReceived = false

        // Act
        engine.onError = { _ in
            errorReceived = true
        }

        // Assert
        #expect(engine.onError != nil)
    }

    @Test("Presenter overlay callback can be set")
    func presenterOverlayCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onPresenterOverlayChanged = { _ in }

        // Assert
        #expect(engine.onPresenterOverlayChanged != nil)
    }

    @Test("Content selected callback can be set")
    func contentSelectedCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onContentSelected = { }

        // Assert
        #expect(engine.onContentSelected != nil)
    }

    // MARK: - Double Stop Prevention Tests

    @Test("Double stop is prevented")
    func doubleStopPrevented() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - stop twice quickly
        async let stop1 = engine.stopRecording()
        async let stop2 = engine.stopRecording()
        _ = await (stop1, stop2)

        // Assert
        let isRecording = await engine.isRecording
        let isStopping = await engine.isStopping
        #expect(isRecording == false)
        #expect(isStopping == false)
    }

    // MARK: - Time Coordinator Tests

    @Test("Time coordinator is initialized")
    func timeCoordinatorInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert - access via actor isolation
        let coordinator = await engine.timeCoordinator
        #expect(coordinator != nil)
    }

    // MARK: - Audio Level Subject Tests

    @Test("Audio level subject is available")
    func audioLevelSubjectAvailable() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.audioLevelSubject != nil)
    }
}
