//
//  RecordingEngineTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import AVFoundation
import AudioToolbox
@testable import SaneVideo
import Testing

@Suite("Recording Engine Tests")
@MainActor
struct RecordingEngineTests {
    // MARK: - Test Setup

    var sut: RecordingEngine {
        RecordingEngine()
    }

    // MARK: - Initial State Tests

    @Test("Initial state has correct defaults")
    func initialState() async throws {
        // Arrange
        let engine = sut

        // Act - access state via RecordingActor
        let isRecording = await engine.isRecording
        let isPaused = await engine.isPaused
        let currentSource = await engine.currentSource

        // Assert
        #expect(isRecording == false)
        #expect(isPaused == false)
        #expect(currentSource == .camera)
    }

    @Test("Disk space monitor can verify space on init")
    func diskSpaceMonitorInitialized() async throws {
        // Arrange
        let engine = sut

        // Act & Assert - monitor should allow space verification immediately
        try engine.diskSpaceMonitor.verifyDiskSpace()
    }

    @Test("Screen preview layer has correct video gravity")
    func screenPreviewLayerInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert - verify the configured gravity, not just existence
        #expect(engine.screenPreviewLayer.videoGravity == .resizeAspectFill)
    }

    // MARK: - Recording Lifecycle Tests

    @Test("Start recording sets isRecording flag")
    func startRecordingSetsFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == true)
    }

    @Test("Stop recording clears isRecording flag")
    func stopRecordingClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        _ = await engine.stopRecording()

        // Assert
        let isRecording = await engine.isRecording
        #expect(isRecording == false)
    }

    @Test("Pause sets isPaused flag")
    func pauseSetsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act
        await engine.pause()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == true)
    }

    @Test("Resume clears isPaused flag")
    func resumeClearsPausedFlag() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        await engine.pause()

        // Act
        await engine.resume()

        // Assert
        let isPaused = await engine.isPaused
        #expect(isPaused == false)
    }

    // MARK: - Mic Muting Tests

    @Test("Set muted updates isMicMuted")
    func setMutedUpdatesFlag() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.setMuted(true)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == true)
    }

    @Test("Unmute clears isMicMuted")
    func unmuteClearsFlag() async throws {
        // Arrange
        let engine = sut
        await engine.setMuted(true)

        // Act
        await engine.setMuted(false)

        // Assert
        let isMuted = await engine.isMicMuted
        #expect(isMuted == false)
    }

    // MARK: - Callback Tests

    @Test("Error callback can be set")
    func errorCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut
        var errorReceived = false

        // Act
        engine.onError = { _ in
            errorReceived = true
        }

        // Assert
        #expect(engine.onError != nil)
    }

    @Test("Presenter overlay callback can be set")
    func presenterOverlayCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onPresenterOverlayChanged = { _ in }

        // Assert
        #expect(engine.onPresenterOverlayChanged != nil)
    }

    @Test("Content selected callback can be set")
    func contentSelectedCallbackCanBeSet() async throws {
        // Arrange
        let engine = sut

        // Act
        engine.onContentSelected = {}

        // Assert
        #expect(engine.onContentSelected != nil)
    }

    // MARK: - Double Stop Prevention Tests

    @Test("Double stop is prevented")
    func doubleStopPrevented() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - stop twice quickly
        async let stop1 = engine.stopRecording()
        async let stop2 = engine.stopRecording()
        _ = await (stop1, stop2)

        // Assert
        let isRecording = await engine.isRecording
        let isStopping = await engine.isStopping
        #expect(isRecording == false)
        #expect(isStopping == false)
    }

    // MARK: - Time Coordinator Tests

    @Test("Time coordinator is initialized")
    func timeCoordinatorInitialized() async throws {
        // Arrange & Act
        let engine = sut

        // Assert - access via actor isolation
        let coordinator = await engine.timeCoordinator
        #expect(coordinator != nil)
    }

    @Test("Recording start resets time coordinator timing state")
    func startRecordingResetsTimeCoordinatorState() async throws {
        let engine = sut
        let coordinator = await engine.timeCoordinator
        coordinator.startTime = CMTime(seconds: 9, preferredTimescale: 600)
        coordinator.timeOffset = CMTime(seconds: 2, preferredTimescale: 600)
        coordinator.startTimeNeedsRecalibration = true

        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        #expect(coordinator.startTime == .zero)
        #expect(coordinator.timeOffset == .zero)
        #expect(coordinator.startTimeNeedsRecalibration == false)

        _ = await engine.stopRecording()
    }

    // MARK: - Audio Level Subject Tests

    @Test("Audio level subject is available")
    func audioLevelSubjectAvailable() async throws {
        // Arrange & Act
        let engine = sut

        // Assert
        #expect(engine.audioLevelSubject != nil)
    }

    // MARK: - Guard Condition Tests

    @Test("Cannot start recording when already recording")
    func cannotStartWhenRecording() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let wasRecording = await engine.isRecording
        #expect(wasRecording == true)

        // Act - try to start again
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - should still be recording with original source
        let stillRecording = await engine.isRecording
        let source = await engine.currentSource
        #expect(stillRecording == true)
        #expect(source == .camera) // Original source preserved

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Screen recording without camera overlay skips camera start")
    func screenRecordingWithoutCameraOverlaySkipsCameraStart() async throws {
        let cameraService = CameraServiceProtocolMock()
        let screenRecorder = ScreenRecorderCallCountingMock()
        let audioService = MockAudioService(
            permissionManager: ServiceContainer.shared.permissionManager
        )
        let engine = RecordingEngine(
            cameraService: cameraService,
            audioService: audioService,
            screenRecorder: screenRecorder
        )

        await engine.startRecording(initialSource: .screen, includeCameraOverlay: false)
        try await Task.sleep(nanoseconds: 150_000_000)

        let isRecording = await engine.isRecording
        #expect(cameraService.startCallCount == 0)
        #expect(isRecording == true)

        _ = await engine.stopRecording()
    }

    @Test("Microphone readiness helper times out when mic never becomes live")
    func microphoneReadinessTimesOut() async throws {
        let audioService = DelayedStartAudioService(
            permissionManager: ServiceContainer.shared.permissionManager,
            startDelayNanoseconds: nil
        )
        let engine = RecordingEngine(
            cameraService: CameraServiceProtocolMock(),
            audioService: audioService,
            screenRecorder: ScreenRecorderCallCountingMock()
        )

        await MainActor.run {
            audioService.start()
        }

        let ready = await engine.waitForMicrophoneCaptureToStart(
            timeoutNanoseconds: 120_000_000,
            pollNanoseconds: 20_000_000,
            allowTestBypass: false
        )

        #expect(ready == false)
    }

    @Test("Microphone readiness helper succeeds when mic becomes live shortly after start")
    func microphoneReadinessSucceedsAfterDelayedStart() async throws {
        let audioService = DelayedStartAudioService(
            permissionManager: ServiceContainer.shared.permissionManager,
            startDelayNanoseconds: 40_000_000
        )
        let engine = RecordingEngine(
            cameraService: CameraServiceProtocolMock(),
            audioService: audioService,
            screenRecorder: ScreenRecorderCallCountingMock()
        )

        await MainActor.run {
            audioService.start()
        }

        let ready = await engine.waitForMicrophoneCaptureToStart(
            timeoutNanoseconds: 300_000_000,
            pollNanoseconds: 20_000_000,
            allowTestBypass: false
        )

        #expect(ready == true)
    }

    @Test("Stop returns nil when not recording")
    func stopReturnsNilWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let isRecording = await engine.isRecording
        #expect(isRecording == false)

        // Act
        let result = await engine.stopRecording()

        // Assert
        #expect(result == nil)
    }

    @Test("Pause does nothing when not recording")
    func pauseIgnoredWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let wasRecording = await engine.isRecording
        #expect(wasRecording == false)

        // Act
        await engine.pause()

        // Assert - isPaused should still be false
        let isPaused = await engine.isPaused
        #expect(isPaused == false)
    }

    @Test("Resume does nothing when not paused")
    func resumeIgnoredWhenNotPaused() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let isPausedBefore = await engine.isPaused
        #expect(isPausedBefore == false)

        // Act
        await engine.resume()

        // Assert - no change
        let isPausedAfter = await engine.isPaused
        #expect(isPausedAfter == false)

        // Cleanup
        _ = await engine.stopRecording()
    }

    // MARK: - Source Tests

    @Test("Can start with camera source")
    func canStartWithCamera() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let source = await engine.currentSource
        #expect(source == .camera)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Can start with screen source")
    func canStartWithScreen() async throws {
        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Assert
        let source = await engine.currentSource
        #expect(source == .screen)

        // Cleanup
        _ = await engine.stopRecording()
    }

    // MARK: - isStopping Flag Tests

    @Test("isStopping prevents restart during stop")
    func isStoppingPreventsRestart() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - start stop and immediately try to start again
        async let stopTask = engine.stopRecording()
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay
        await engine.startRecording(initialSource: .camera)
        _ = await stopTask

        // Assert - should not be recording (start was blocked by isStopping)
        let isRecording = await engine.isRecording
        let isStopping = await engine.isStopping
        #expect(isStopping == false) // Should be cleared after stop completes
    }

    // MARK: - TestEnvironment Mode Tests

    @Test("Test mode generates mock file URL")
    func modeGeneratesMockURL() async throws {
        // Note: This tests the TestEnvironment.isTesting path
        // When isTesting is true, a mock URL is generated instead of real recording

        // Arrange
        let engine = sut

        // Act
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let url = await engine.stopRecording()

        // Assert - in test mode, should return a URL
        // (actual file may or may not exist depending on TestEnvironment)
        if TestEnvironment.isTesting {
            #expect(url != nil)
        }
    }

    // MARK: - Source Switching Edge Case Tests

    @Test("Cannot switch source when not recording")
    func cannotSwitchWhenNotRecording() async throws {
        // Arrange
        let engine = sut
        let isRecording = await engine.isRecording
        #expect(isRecording == false)

        // Act - try to switch source when not recording
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - should still be on default source (no change)
        let source = await engine.currentSource
        #expect(source == .camera) // Default source
    }

    @Test("Cannot switch to same source")
    func cannotSwitchToSameSource() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)
        let initialSource = await engine.currentSource
        #expect(initialSource == .camera)

        // Act - try to switch to same source
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - isSwitching should NOT be set (request was ignored)
        let isSwitching = await engine.isSwitching
        let source = await engine.currentSource
        #expect(isSwitching == false)
        #expect(source == .camera)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Switch source from camera to screen")
    func switchFromCameraToScreen() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - switch to screen
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 200_000_000) // Allow time for switch

        // Assert - pendingSource should be set or switch completed
        let pendingSource = await engine.pendingSource
        let currentSource = await engine.currentSource
        // Either switch is complete (currentSource == .screen) or in progress (pendingSource == .screen)
        let switchInitiated = (currentSource == .screen) || (pendingSource == .screen)
        #expect(switchInitiated == true)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Switch source from screen to camera")
    func switchFromScreenToCamera() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - switch to camera
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 200_000_000) // Allow time for switch

        // Assert - pendingSource should be set or switch completed
        let pendingSource = await engine.pendingSource
        let currentSource = await engine.currentSource
        // Either switch is complete (currentSource == .camera) or in progress (pendingSource == .camera)
        let switchInitiated = (currentSource == .camera) || (pendingSource == .camera)
        #expect(switchInitiated == true)

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Pending camera frames do not complete screen to camera switch early")
    func pendingCameraFramesDoNotCompleteScreenToCameraSwitchEarly() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .screen)
        try await Task.sleep(nanoseconds: 50_000_000)

        await configureSwitchState(
            engine,
            current: .screen,
            pending: .camera,
            needsRecalibration: true
        )

        let coordinator = await engine.timeCoordinator

        let sampleBuffer = try makeVideoSampleBuffer(
            presentationTime: CMTime(value: 600, timescale: 600)
        )

        await engine.processSample(sampleBuffer, source: .camera)

        let currentSource = await engine.currentSource
        let pendingSource = await engine.pendingSource
        #expect(currentSource == .screen)
        #expect(pendingSource == .camera)
        #expect(coordinator.startTimeNeedsRecalibration == true)

        _ = await engine.stopRecording()
    }

    @Test("Pending screen frames still complete camera to screen switch")
    func pendingScreenFramesStillCompleteCameraToScreenSwitch() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 50_000_000)

        await configureSwitchState(
            engine,
            current: .camera,
            pending: .screen,
            needsRecalibration: true
        )

        let sampleBuffer = try makeVideoSampleBuffer(
            presentationTime: CMTime(value: 900, timescale: 600)
        )

        await engine.processSample(sampleBuffer, source: .screen)

        let currentSource = await engine.currentSource
        let pendingSource = await engine.pendingSource
        #expect(currentSource == .screen)
        #expect(pendingSource == nil)

        _ = await engine.stopRecording()
    }

    @Test("Screen to camera handoff uses latest written mic audio time")
    func screenToCameraHandoffUsesLatestWrittenMicAudioTime() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .screen)

        let writer = await makeActiveVideoWriterMock()
        await configureWriterState(engine, writer: writer, current: .camera)

        let coordinator = await engine.timeCoordinator
        let firstVideo = coordinator.processSampleTime(CMTime(seconds: 10, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(firstVideo.presentationTime)
        let secondVideo = coordinator.processSampleTime(CMTime(seconds: 11, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(secondVideo.presentationTime)
        coordinator.beginSourceSwitchRecalibration()

        let audioSample = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 11.8, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(audioSample)

        let cameraSample = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 12.0, preferredTimescale: 600)
        )
        await engine.processSample(cameraSample, source: .camera)

        #expect(await micWriteCallCount(writer) == 1)
        #expect(await videoWriteCallCount(writer) == 1)
        if let writtenTime = await lastWrittenVideoTime(writer) {
            #expect(abs(writtenTime - 11.9) < 0.001)
        } else {
            Issue.record("Expected the first post-switch camera frame to be written")
        }
        #expect(coordinator.startTimeNeedsRecalibration == false)

        _ = await engine.stopRecording()
    }

    @Test("Dropped first post-switch camera frame keeps recalibration armed")
    func droppedFirstPostSwitchCameraFrameKeepsRecalibrationArmed() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .screen)

        let writer = await makeActiveVideoWriterMock()
        let videoWriteAttempts = AttemptCounter()
        await makeFirstVideoWriteFail(writer, attempts: videoWriteAttempts)

        await configureWriterState(engine, writer: writer, current: .camera)

        let coordinator = await engine.timeCoordinator
        let firstVideo = coordinator.processSampleTime(CMTime(seconds: 10, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(firstVideo.presentationTime)
        let secondVideo = coordinator.processSampleTime(CMTime(seconds: 11, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(secondVideo.presentationTime)
        coordinator.beginSourceSwitchRecalibration()

        let droppedCameraSample = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 12.0, preferredTimescale: 600)
        )
        await engine.processSample(droppedCameraSample, source: .camera)
        #expect(coordinator.startTimeNeedsRecalibration == true)

        let audioSample = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 12.4, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(audioSample)

        let nextCameraSample = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 12.6, preferredTimescale: 600)
        )
        await engine.processSample(nextCameraSample, source: .camera)

        #expect(await videoWriteCallCount(writer) == 2)
        if let writtenTime = await lastWrittenVideoTime(writer) {
            #expect(abs(writtenTime - 12.5) < 0.001)
        } else {
            Issue.record("Expected the second post-switch camera frame to be written")
        }
        #expect(coordinator.startTimeNeedsRecalibration == false)

        _ = await engine.stopRecording()
    }

    @Test("Large video-only recalibration does not push microphone audio backwards")
    func largeVideoOnlyRecalibrationDoesNotPushMicrophoneAudioBackwards() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .screen)

        let writer = await makeActiveVideoWriterMock()
        let micPTSRecorder = MonotonicPTSRecorder()
        await configureWriterState(engine, writer: writer, current: .camera)
        await installMicMonotonicHandler(writer, recorder: micPTSRecorder)

        let coordinator = await engine.timeCoordinator
        let firstVideo = coordinator.processSampleTime(CMTime(seconds: 4679.9, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(firstVideo.presentationTime)
        let secondVideo = coordinator.processSampleTime(CMTime(seconds: 4680.0, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(secondVideo.presentationTime)

        let micBeforeSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 4680.34, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micBeforeSwitch)
        #expect(await micWriteCallCount(writer) == 1)

        coordinator.beginSourceSwitchRecalibration()

        let postSwitchVideo = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 4704.83, preferredTimescale: 600)
        )
        await engine.processSample(postSwitchVideo, source: .camera)

        #expect(coordinator.timeOffset.seconds > 20.0)

        let micAfterSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 4680.50, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micAfterSwitch)

        #expect(await micWriteCallCount(writer) == 2)
        if let writtenPTS = await lastWrittenMicTime(writer) {
            #expect(abs(writtenPTS - 4680.50) < 0.001)
        } else {
            Issue.record("Expected a post-switch microphone sample to be written")
        }
        #expect(micPTSRecorder.lastAccepted != nil)
        if let lastAcceptedMicPTS = micPTSRecorder.lastAccepted {
            #expect(abs(lastAcceptedMicPTS - 4680.50) < 0.001)
        }

        _ = await engine.stopRecording()
    }

    @Test("Repeated long-session source switches keep microphone monotonic and video contiguous")
    func repeatedLongSessionSourceSwitchesKeepTracksAligned() async throws {
        let engine = sut
        await engine.startRecording(initialSource: .screen)

        let writer = await makeActiveVideoWriterMock()
        let micPTSRecorder = MonotonicPTSRecorder()
        await configureWriterState(engine, writer: writer, current: .screen)
        await installMicMonotonicHandler(writer, recorder: micPTSRecorder)

        let coordinator = await engine.timeCoordinator

        let openingVideo = coordinator.processSampleTime(CMTime(seconds: 1799.90, preferredTimescale: 600))
        coordinator.recordWrittenPresentationTime(openingVideo.presentationTime)
        let latestPreSwitchVideo = coordinator.processSampleTime(
            CMTime(seconds: 1800.00, preferredTimescale: 600)
        )
        coordinator.recordWrittenPresentationTime(latestPreSwitchVideo.presentationTime)

        let micBeforeFirstSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 1800.35, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micBeforeFirstSwitch)
        #expect(await micWriteCallCount(writer) == 1)

        coordinator.beginSourceSwitchRecalibration()
        await configureWriterState(engine, writer: writer, current: .camera)
        let firstPostSwitchCamera = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 1826.20, preferredTimescale: 600)
        )
        await engine.processSample(firstPostSwitchCamera, source: .camera)

        if let firstSwitchVideoPTS = await lastWrittenVideoTime(writer) {
            #expect(abs(firstSwitchVideoPTS - 1800.45) < 0.001)
        } else {
            Issue.record("Expected first post-switch camera frame to be written")
        }

        let micAfterFirstSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 1800.62, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micAfterFirstSwitch)

        coordinator.beginSourceSwitchRecalibration()
        await configureWriterState(engine, writer: writer, current: .screen)
        let firstPostSwitchScreen = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 1854.80, preferredTimescale: 600)
        )
        await engine.processSample(firstPostSwitchScreen, source: .screen)

        if let secondSwitchVideoPTS = await lastWrittenVideoTime(writer) {
            #expect(abs(secondSwitchVideoPTS - 1800.72) < 0.001)
        } else {
            Issue.record("Expected first post-switch screen frame to be written")
        }

        let micAfterSecondSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 1800.88, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micAfterSecondSwitch)

        coordinator.beginSourceSwitchRecalibration()
        await configureWriterState(engine, writer: writer, current: .camera)
        let secondPostSwitchCamera = try makeVideoSampleBuffer(
            presentationTime: CMTime(seconds: 1889.33, preferredTimescale: 600)
        )
        await engine.processSample(secondPostSwitchCamera, source: .camera)

        if let thirdSwitchVideoPTS = await lastWrittenVideoTime(writer) {
            #expect(abs(thirdSwitchVideoPTS - 1800.98) < 0.001)
        } else {
            Issue.record("Expected second post-switch camera frame to be written")
        }

        let micAfterThirdSwitch = try makeAudioSampleBuffer(
            presentationTime: CMTime(seconds: 1801.05, preferredTimescale: 48_000)
        )
        await engine.processAudioSample(micAfterThirdSwitch)

        #expect(await micWriteCallCount(writer) == 4)
        if let lastAcceptedMicPTS = micPTSRecorder.lastAccepted {
            #expect(abs(lastAcceptedMicPTS - 1801.05) < 0.001)
        } else {
            Issue.record("Expected monotonic microphone timestamps to be recorded across switches")
        }
        #expect(coordinator.startTimeNeedsRecalibration == false)

        _ = await engine.stopRecording()
    }

    @Test("Concurrent switch requests are blocked")
    func concurrentSwitchRequestsBlocked() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - initiate first switch
        engine.switchSource(source: .screen)
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay

        // Try to initiate second switch while first is in progress
        engine.switchSource(source: .camera)
        try await Task.sleep(nanoseconds: 50_000_000)

        // Assert - second switch should be blocked, pendingSource should be .screen (first request)
        let pendingSource = await engine.pendingSource
        if pendingSource != nil {
            #expect(pendingSource == .screen) // First switch should win
        }

        // Cleanup
        _ = await engine.stopRecording()
    }

    @Test("Cannot switch source while stopping")
    func cannotSwitchWhileStopping() async throws {
        // Arrange
        let engine = sut
        await engine.startRecording(initialSource: .camera)
        try await Task.sleep(nanoseconds: 150_000_000)

        // Act - start stop and immediately try to switch
        async let stopTask = engine.stopRecording()
        try await Task.sleep(nanoseconds: 10_000_000) // Small delay
        engine.switchSource(source: .screen)
        _ = await stopTask

        // Assert - should not be switching, stop should complete normally
        let isSwitching = await engine.isSwitching
        let isRecording = await engine.isRecording
        #expect(isSwitching == false)
        #expect(isRecording == false)
    }
}

private final class ScreenRecorderCallCountingMock: ScreenRecorder {
    private(set) var startCallCount = 0

    override func start(outputURL: URL? = nil) async throws {
        startCallCount += 1
    }

    override func stop() async {}

    override func teardown() {}
}

private final class DelayedStartAudioService: AudioService {
    private let startDelayNanoseconds: UInt64?

    init(permissionManager: PermissionManager, startDelayNanoseconds: UInt64?) {
        self.startDelayNanoseconds = startDelayNanoseconds
        super.init(permissionManager: permissionManager)
    }

    override func start() {
        guard let startDelayNanoseconds else { return }

        Task { @MainActor in
            if startDelayNanoseconds > 0 {
                try? await Task.sleep(nanoseconds: startDelayNanoseconds)
            }
            self.isRunning = true
        }
    }

    override func stop() {
        isRunning = false
    }

    override func checkPermission() {}

    override func requestPermission() {}
}

@RecordingActor
private func configureSwitchState(
    _ engine: RecordingEngine,
    current: RecordingSource,
    pending: RecordingSource,
    needsRecalibration: Bool
) {
    engine.currentSource = current
    engine.pendingSource = pending
    engine.isSwitching = true
    engine.timeCoordinator.startTimeNeedsRecalibration = needsRecalibration
}

@RecordingActor
private func configureWriterState(
    _ engine: RecordingEngine,
    writer: VideoWriterProtocol,
    current: RecordingSource,
    pending: RecordingSource? = nil,
    isSwitching: Bool = false
) {
    engine.videoWriter = writer
    engine.currentSource = current
    engine.pendingSource = pending
    engine.isSwitching = isSwitching
    engine.timeCoordinator.driftTracker = writer.driftTracker
}

private final class AttemptCounter: @unchecked Sendable {
    var value = 0
}

@RecordingActor
private func makeActiveVideoWriterMock() -> VideoWriterProtocolMock {
    let writer = VideoWriterProtocolMock()
    writer.isWriting = true
    writer.isReadyForData = true
    writer.driftTracker = DriftTracker()
    return writer
}

@RecordingActor
private func makeFirstVideoWriteFail(
    _ writer: VideoWriterProtocolMock,
    attempts: AttemptCounter
) {
    writer.writeVideoHandler = { _, _, _ in
        attempts.value += 1
        return attempts.value > 1
    }
}

@RecordingActor
private func micWriteCallCount(_ writer: VideoWriterProtocolMock) -> Int {
    writer.writeMicAudioCallCount
}

@RecordingActor
private func installMicMonotonicHandler(
    _ writer: VideoWriterProtocolMock,
    recorder: MonotonicPTSRecorder
) {
    writer.writeMicAudioHandler = { sampleBuffer in
        let pts = CMSampleBufferGetPresentationTimeStamp(sampleBuffer).seconds
        return recorder.record(pts)
    }
}

@RecordingActor
private func videoWriteCallCount(_ writer: VideoWriterProtocolMock) -> Int {
    writer.writeVideoCallCount
}

@RecordingActor
private func lastWrittenVideoTime(_ writer: VideoWriterProtocolMock) -> Double? {
    writer.writeVideoArgValues.last?.presentationTime.seconds
}

@RecordingActor
private func lastWrittenMicTime(_ writer: VideoWriterProtocolMock) -> Double? {
    writer.writeMicAudioArgValues.last.map { CMSampleBufferGetPresentationTimeStamp($0).seconds }
}

private final class MonotonicPTSRecorder: @unchecked Sendable {
    private let lock = NSLock()
    private var acceptedPTS: [Double] = []

    func record(_ pts: Double) -> Bool {
        lock.withLock {
            if let last = acceptedPTS.last, pts <= last {
                return false
            }
            acceptedPTS.append(pts)
            return true
        }
    }

    var lastAccepted: Double? {
        lock.withLock { acceptedPTS.last }
    }
}

private func makeVideoSampleBuffer(presentationTime: CMTime) throws -> CMSampleBuffer {
    let attributes: [CFString: Any] = [
        kCVPixelBufferCGImageCompatibilityKey: true,
        kCVPixelBufferCGBitmapContextCompatibilityKey: true
    ]

    var pixelBuffer: CVPixelBuffer?
    let pixelStatus = CVPixelBufferCreate(
        kCFAllocatorDefault,
        4,
        4,
        kCVPixelFormatType_32BGRA,
        attributes as CFDictionary,
        &pixelBuffer
    )
    guard pixelStatus == kCVReturnSuccess, let pixelBuffer else {
        throw NSError(domain: "RecordingEngineTests", code: Int(pixelStatus))
    }

    var formatDescription: CMVideoFormatDescription?
    let formatStatus = CMVideoFormatDescriptionCreateForImageBuffer(
        allocator: kCFAllocatorDefault,
        imageBuffer: pixelBuffer,
        formatDescriptionOut: &formatDescription
    )
    guard formatStatus == noErr, let formatDescription else {
        throw NSError(domain: "RecordingEngineTests", code: Int(formatStatus))
    }

    var timing = CMSampleTimingInfo(
        duration: CMTime(value: 1, timescale: 30),
        presentationTimeStamp: presentationTime,
        decodeTimeStamp: presentationTime
    )

    var sampleBuffer: CMSampleBuffer?
    let sampleStatus = CMSampleBufferCreateReadyWithImageBuffer(
        allocator: kCFAllocatorDefault,
        imageBuffer: pixelBuffer,
        formatDescription: formatDescription,
        sampleTiming: &timing,
        sampleBufferOut: &sampleBuffer
    )
    guard sampleStatus == noErr, let sampleBuffer else {
        throw NSError(domain: "RecordingEngineTests", code: Int(sampleStatus))
    }

    return sampleBuffer
}

private func makeAudioSampleBuffer(presentationTime: CMTime) throws -> CMSampleBuffer {
    var asbd = AudioStreamBasicDescription(
        mSampleRate: 48_000,
        mFormatID: kAudioFormatLinearPCM,
        mFormatFlags: kLinearPCMFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked,
        mBytesPerPacket: 2,
        mFramesPerPacket: 1,
        mBytesPerFrame: 2,
        mChannelsPerFrame: 1,
        mBitsPerChannel: 16,
        mReserved: 0
    )

    var formatDescription: CMAudioFormatDescription?
    let formatStatus = CMAudioFormatDescriptionCreate(
        allocator: kCFAllocatorDefault,
        asbd: &asbd,
        layoutSize: 0,
        layout: nil,
        magicCookieSize: 0,
        magicCookie: nil,
        extensions: nil,
        formatDescriptionOut: &formatDescription
    )
    guard formatStatus == noErr, let formatDescription else {
        throw NSError(domain: "RecordingEngineTests", code: Int(formatStatus))
    }

    var blockBuffer: CMBlockBuffer?
    let blockStatus = CMBlockBufferCreateWithMemoryBlock(
        allocator: kCFAllocatorDefault,
        memoryBlock: nil,
        blockLength: 2,
        blockAllocator: nil,
        customBlockSource: nil,
        offsetToData: 0,
        dataLength: 2,
        flags: 0,
        blockBufferOut: &blockBuffer
    )
    guard blockStatus == kCMBlockBufferNoErr, let blockBuffer else {
        throw NSError(domain: "RecordingEngineTests", code: Int(blockStatus))
    }

    var silence = [UInt8](repeating: 0, count: 2)
    let replaceStatus = CMBlockBufferReplaceDataBytes(
        with: &silence,
        blockBuffer: blockBuffer,
        offsetIntoDestination: 0,
        dataLength: silence.count
    )
    guard replaceStatus == kCMBlockBufferNoErr else {
        throw NSError(domain: "RecordingEngineTests", code: Int(replaceStatus))
    }

    var timing = CMSampleTimingInfo(
        duration: CMTime(value: 1, timescale: 48_000),
        presentationTimeStamp: presentationTime,
        decodeTimeStamp: .invalid
    )
    var sampleSize = 2
    var sampleBuffer: CMSampleBuffer?
    let sampleStatus = CMSampleBufferCreateReady(
        allocator: kCFAllocatorDefault,
        dataBuffer: blockBuffer,
        formatDescription: formatDescription,
        sampleCount: 1,
        sampleTimingEntryCount: 1,
        sampleTimingArray: &timing,
        sampleSizeEntryCount: 1,
        sampleSizeArray: &sampleSize,
        sampleBufferOut: &sampleBuffer
    )
    guard sampleStatus == noErr, let sampleBuffer else {
        throw NSError(domain: "RecordingEngineTests", code: Int(sampleStatus))
    }

    return sampleBuffer
}
