//
//  SmartFillerDetectorTests.swift
//  SaneVideoTests
//
//  Generated by SaneMaster.rb test generator
//  Follow AAA pattern: Arrange-Act-Assert
//

import Testing
import Foundation
@testable import SaneVideo

@Suite("SmartFillerDetector Tests")
struct SmartFillerDetectorTests {

    // MARK: - Definite Filler Detection Tests

    @Suite("Definite Fillers")
    struct DefiniteFillerTests {

        @Test("Detects 'um' as filler")
        func detectsUm() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "So", start: 0, end: 0.5, probability: 0.9),
                CaptionWord(text: "um", start: 0.5, end: 0.7, probability: 0.9),
                CaptionWord(text: "hello", start: 0.7, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(1))  // "um" is at index 1
        }

        @Test("Detects 'uh' as filler")
        func detectsUh() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "uh", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "yes", start: 0.3, end: 0.6, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))  // "uh" is at index 0
        }

        @Test("Detects 'uhh' as filler")
        func detectsUhh() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "uhh", start: 0, end: 0.5, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.count == 1)
            #expect(fillers.contains(0))
        }

        @Test("Detects 'umm' as filler")
        func detectsUmm() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "umm", start: 0, end: 0.5, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
        }

        @Test("Detects 'er' as filler")
        func detectsEr() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "er", start: 0, end: 0.3, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
        }

        @Test("Detects 'hmm' as filler")
        func detectsHmm() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "hmm", start: 0, end: 0.5, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
        }

        @Test("Detects 'mhm' as filler")
        func detectsMhm() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "mhm", start: 0, end: 0.3, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
        }

        @Test("Detects multiple definite fillers")
        func detectsMultipleFillers() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "um", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "so", start: 0.3, end: 0.5, probability: 0.9),
                CaptionWord(text: "uh", start: 0.5, end: 0.7, probability: 0.9),
                CaptionWord(text: "yeah", start: 0.7, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))  // "um"
            #expect(fillers.contains(2))  // "uh"
        }

        @Test("Case insensitive detection")
        func caseInsensitive() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "UM", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "Uh", start: 0.3, end: 0.5, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
            #expect(fillers.contains(1))
        }
    }

    // MARK: - Non-Filler Detection Tests

    @Suite("Non-Fillers")
    struct NonFillerTests {

        @Test("Does not detect regular words as fillers")
        func noFalsePositives() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "Hello", start: 0, end: 0.5, probability: 0.9),
                CaptionWord(text: "world", start: 0.5, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.isEmpty)
        }

        @Test("Does not detect similar words as fillers")
        func noSimilarWordFalsePositives() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "umbrella", start: 0, end: 0.5, probability: 0.9),
                CaptionWord(text: "hammer", start: 0.5, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.isEmpty)
        }

        @Test("Empty words array returns empty")
        func emptyWordsReturnsEmpty() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words: [CaptionWord] = []

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.isEmpty)
        }
    }

    // MARK: - Text-Based Detection Tests

    @Suite("Text Detection")
    struct TextDetectionTests {

        @Test("Detects fillers in raw text")
        func detectsInText() async {
            // Arrange
            let detector = SmartFillerDetector()
            let text = "So um I was thinking uh about this"

            // Act
            let fillers = await detector.detectFillers(in: text)

            // Assert
            #expect(fillers.count >= 2)  // At least "um" and "uh"
            let fillerWords = fillers.map { $0.word }
            #expect(fillerWords.contains("um"))
            #expect(fillerWords.contains("uh"))
        }

        @Test("Returns ranges for filler positions")
        func returnsRanges() async {
            // Arrange
            let detector = SmartFillerDetector()
            let text = "Hello um world"

            // Act
            let fillers = await detector.detectFillers(in: text)

            // Assert
            for filler in fillers {
                let extractedWord = String(text[filler.range])
                #expect(extractedWord.lowercased() == filler.word)
            }
        }

        @Test("Empty text returns empty")
        func emptyTextReturnsEmpty() async {
            // Arrange
            let detector = SmartFillerDetector()
            let text = ""

            // Act
            let fillers = await detector.detectFillers(in: text)

            // Assert
            #expect(fillers.isEmpty)
        }
    }

    // MARK: - Confidence Score Tests

    @Suite("Filler Confidence")
    struct ConfidenceTests {

        @Test("Definite filler has high confidence")
        func definiteFillerHighConfidence() async {
            // Arrange
            let detector = SmartFillerDetector()

            // Act
            let confidence = await detector.fillerConfidence(for: "um", in: "I was um thinking")

            // Assert
            #expect(confidence >= 0.9)
        }

        @Test("Non-filler has zero confidence")
        func nonFillerZeroConfidence() async {
            // Arrange
            let detector = SmartFillerDetector()

            // Act
            let confidence = await detector.fillerConfidence(for: "hello", in: "hello world")

            // Assert
            #expect(confidence == 0.0)
        }

        @Test("Confidence is between 0 and 1")
        func confidenceInRange() async {
            // Arrange
            let detector = SmartFillerDetector()
            let testWords = ["um", "like", "hello", "actually", "basically"]

            // Act & Assert
            for word in testWords {
                let confidence = await detector.fillerConfidence(for: word, in: "Testing \(word) in context")
                #expect(confidence >= 0.0)
                #expect(confidence <= 1.0)
            }
        }

        @Test("Contextual filler has medium confidence")
        func contextualFillerMediumConfidence() async {
            // Arrange
            let detector = SmartFillerDetector()

            // Act
            let confidence = await detector.fillerConfidence(for: "like", in: "It was like totally cool")

            // Assert - contextual fillers should have lower confidence than definite ones
            #expect(confidence > 0.0)
            #expect(confidence < 0.95)
        }
    }

    // MARK: - Edge Cases

    @Suite("Edge Cases")
    struct EdgeCaseTests {

        @Test("Handles punctuation around fillers")
        func handlesPunctuation() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "um,", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "uh.", start: 0.3, end: 0.5, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert - should still detect despite punctuation
            #expect(fillers.contains(0))
            #expect(fillers.contains(1))
        }

        @Test("Handles single word input")
        func handlesSingleWord() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [CaptionWord(text: "um", start: 0, end: 0.5, probability: 0.9)]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.count == 1)
        }

        @Test("Handles long sentence")
        func handlesLongSentence() async {
            // Arrange
            let detector = SmartFillerDetector()
            var words: [CaptionWord] = []
            let sentence = "The quick brown fox um jumps uh over the lazy dog and um that is all"
            var time = 0.0

            for word in sentence.split(separator: " ") {
                words.append(CaptionWord(text: String(word), start: time, end: time + 0.3, probability: 0.9))
                time += 0.3
            }

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert - should find "um" and "uh"
            #expect(fillers.count >= 2)
        }

        @Test("Handles mixed case and punctuation in text")
        func handlesMixedCasePunctuation() async {
            // Arrange
            let detector = SmartFillerDetector()
            let text = "So, UM... I was, uh, thinking."

            // Act
            let fillers = await detector.detectFillers(in: text)

            // Assert
            let fillerWords = fillers.map { $0.word.lowercased() }
            #expect(fillerWords.contains("um"))
            #expect(fillerWords.contains("uh"))
        }

        @Test("Handles hyphenated fillers")
        func handlesHyphenatedFillers() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "uh-huh", start: 0, end: 0.5, probability: 0.9),
                CaptionWord(text: "mm-hmm", start: 0.5, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.count == 2)
        }
    }

    // MARK: - Contextual Filler Tests

    @Suite("Contextual Fillers")
    struct ContextualFillerTests {

        @Test("'like' at sentence start is filler")
        func likeAtStartIsFiller() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "Like", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "I", start: 0.3, end: 0.4, probability: 0.9),
                CaptionWord(text: "was", start: 0.4, end: 0.6, probability: 0.9),
                CaptionWord(text: "thinking", start: 0.6, end: 1.0, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert - "like" at start should be detected
            #expect(fillers.contains(0))
        }

        @Test("'well' at sentence start is filler")
        func wellAtStartIsFiller() async {
            // Arrange
            let detector = SmartFillerDetector()
            let words = [
                CaptionWord(text: "Well", start: 0, end: 0.3, probability: 0.9),
                CaptionWord(text: "I", start: 0.3, end: 0.4, probability: 0.9),
                CaptionWord(text: "think", start: 0.4, end: 0.7, probability: 0.9)
            ]

            // Act
            let fillers = await detector.detectFillers(in: words)

            // Assert
            #expect(fillers.contains(0))
        }
    }
}
