# frozen_string_literal: true

module SaneMasterModules
  # Generates hook stubs from detected intervention patterns
  module HookGenerator
    extend self

    HOOKS_DIR = File.expand_path('Scripts/sanemaster/hooks', Dir.pwd)
    SETTINGS_PATH = File.expand_path('.claude/settings.json', Dir.pwd)

    HOOK_TEMPLATES = {
      screenshot_check: {
        trigger: 'PreToolUse',
        tools: %w[Read Bash],
        description: 'Remind to check screenshot location',
        logic: 'Check if tool involves screenshots and remind about ~/.claude/screenshots/'
      },
      sop_reminder: {
        trigger: 'PreToolUse',
        tools: %w[Edit Write],
        description: 'Remind to check SOP before edits',
        logic: 'Periodic reminder to check SOP rules before making changes'
      },
      memory_check: {
        trigger: 'PreToolUse',
        tools: %w[Edit Bash],
        description: 'Remind to check memory for past patterns',
        logic: 'Remind to check Memory MCP for relevant past learnings'
      },
      path_verification: {
        trigger: 'PreToolUse',
        tools: %w[Read Write Edit],
        description: 'Verify paths before file operations',
        logic: 'Check that file paths are valid and within project'
      },
      build_verification: {
        trigger: 'PostToolUse',
        tools: %w[Bash],
        description: 'Verify build output matches launch path',
        logic: 'After build, check that built binary path matches expected launch path'
      }
    }.freeze

    def generate(pattern_name, options = {})
      pattern = pattern_name.to_sym
      template = HOOK_TEMPLATES[pattern]

      unless template
        puts "Unknown pattern: #{pattern_name}"
        puts "Available patterns: #{HOOK_TEMPLATES.keys.join(', ')}"
        return false
      end

      if options[:dry_run]
        show_preview(pattern_name, template)
      else
        create_hook(pattern_name, template, options)
      end
    end

    def list_patterns
      puts 'Available hook patterns:'
      puts ''
      HOOK_TEMPLATES.each do |name, template|
        puts "  #{name}"
        puts "    Trigger: #{template[:trigger]} on #{template[:tools].join(', ')}"
        puts "    Purpose: #{template[:description]}"
        puts ''
      end
    end

    private

    def show_preview(name, template)
      puts "Hook Preview: #{name}"
      puts '=' * 50
      puts ''
      puts "File: #{HOOKS_DIR}/#{name}.rb"
      puts "Trigger: #{template[:trigger]}"
      puts "Tools: #{template[:tools].join(', ')}"
      puts ''
      puts 'Generated code:'
      puts '-' * 50
      puts generate_hook_code(name, template)
      puts '-' * 50
      puts ''
      puts 'Settings.json addition:'
      puts generate_settings_snippet(name, template)
      puts ''
      puts 'Run without --dry-run to create the hook.'
    end

    def create_hook(name, template, options)
      hook_path = File.join(HOOKS_DIR, "#{name}.rb")

      if File.exist?(hook_path) && !options[:force]
        puts "Hook already exists: #{hook_path}"
        puts 'Use --force to overwrite.'
        return false
      end

      # Create hook file
      File.write(hook_path, generate_hook_code(name, template))
      File.chmod(0o755, hook_path)
      puts "Created hook: #{hook_path}"

      # Update settings.json
      if options[:auto_register]
        register_hook(name, template)
      else
        puts ''
        puts 'To register this hook, add to .claude/settings.json:'
        puts generate_settings_snippet(name, template)
      end

      true
    end

    def generate_hook_code(name, template)
      <<~RUBY
        #!/usr/bin/env ruby
        # frozen_string_literal: true

        # Hook: #{name}
        # Purpose: #{template[:description]}
        # Trigger: #{template[:trigger]}
        # Generated by: ./Scripts/SaneMaster.rb generate_hook #{name}

        require 'json'

        # Read hook input from stdin
        input = JSON.parse($stdin.read)
        tool_name = input['tool_name']

        # #{template[:logic]}
        #
        # Exit codes:
        #   0 = Allow (continue)
        #   1 = Block (with message)
        #
        # Output format for messages:
        #   puts JSON.generate({ warning: "message" })  # Show warning, continue
        #   puts JSON.generate({ error: "message" })    # Show error, block

        case tool_name
        #{template[:tools].map { |t| "when '#{t}'\n  # Add your logic here\n  # Example: puts JSON.generate({ warning: 'Remember to check X' })" }.join("\n")}
        end

        # Default: allow
        exit 0
      RUBY
    end

    def generate_settings_snippet(name, template)
      trigger_key = template[:trigger] == 'PreToolUse' ? 'PreToolUse' : 'PostToolUse'
      tools = template[:tools]

      snippet = tools.map do |tool|
        <<~JSON
          {
            "matcher": "#{tool}",
            "hooks": [
              {
                "type": "command",
                "command": "ruby Scripts/sanemaster/hooks/#{name}.rb",
                "timeout": 5000
              }
            ]
          }
        JSON
      end

      "// Add to hooks.#{trigger_key}:\n#{snippet.join("\n")}"
    end

    def register_hook(name, template)
      return unless File.exist?(SETTINGS_PATH)

      settings = JSON.parse(File.read(SETTINGS_PATH))
      hooks = settings['hooks'] ||= {}
      trigger_key = template[:trigger]
      hooks[trigger_key] ||= []

      template[:tools].each do |tool|
        # Check if already registered
        existing = hooks[trigger_key].find { |h| h['matcher'] == tool }
        if existing
          existing['hooks'] ||= []
          unless existing['hooks'].any? { |h| h['command']&.include?(name.to_s) }
            existing['hooks'] << {
              'type' => 'command',
              'command' => "ruby Scripts/sanemaster/hooks/#{name}.rb",
              'timeout' => 5000
            }
          end
        else
          hooks[trigger_key] << {
            'matcher' => tool,
            'hooks' => [{
              'type' => 'command',
              'command' => "ruby Scripts/sanemaster/hooks/#{name}.rb",
              'timeout' => 5000
            }]
          }
        end
      end

      File.write(SETTINGS_PATH, JSON.pretty_generate(settings))
      puts 'Registered hook in settings.json'
    end
  end
end
