///
/// @Generated by Mockolo
///



import AVFoundation
import Combine
import Foundation
@testable import SaneVideo


class ExportServiceProtocolMock: ExportServiceProtocol {
    init() { }
    init(progress: Double = 0.0, isExporting: Bool = false) {
        self.progress = progress
        self.isExporting = isExporting
    }



    var progress: Double = 0.0


    var isExporting: Bool = false

    private(set) var exportCallCount = 0
    var exportArgValues = [(project: VideoProject, settings: SaneExportSettings, outputURL: URL)]()
    var exportHandler: ((VideoProject, SaneExportSettings, URL, @escaping @Sendable (Double) -> Void) async throws -> URL)?
    func export(project: VideoProject, settings: SaneExportSettings, outputURL: URL, progressHandler: @escaping @Sendable (Double) -> Void) async throws -> URL {
        exportCallCount += 1
        exportArgValues.append((project, settings, outputURL))
        if let exportHandler = exportHandler {
            return try await exportHandler(project, settings, outputURL, progressHandler)
        }
        return URL(fileURLWithPath: "")
    }

    private(set) var cancelExportCallCount = 0
    var cancelExportHandler: (() -> ())?
    func cancelExport() {
        cancelExportCallCount += 1
        if let cancelExportHandler = cancelExportHandler {
            cancelExportHandler()
        }

    }
}

final class ProjectStoreProtocolMock: ProjectStoreProtocol, @unchecked Sendable {
    init() { }


    private let loadProjectsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> [VideoProject]>())
    var loadProjectsCallCount: Int {
        return loadProjectsState.withLock(\.callCount)
    }
    var loadProjectsHandler: (@Sendable () async throws -> [VideoProject])? {
        get { loadProjectsState.withLock(\.handler) }
        set { loadProjectsState.withLock { $0.handler = newValue } }
    }
    func loadProjects() async throws -> [VideoProject] {
        let loadProjectsHandler = loadProjectsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let loadProjectsHandler = loadProjectsHandler {
            return try await loadProjectsHandler()
        }
        return [VideoProject]()
    }

    private let saveProjectState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) async throws -> ()>())
    var saveProjectCallCount: Int {
        return saveProjectState.withLock(\.callCount)
    }
    var saveProjectArgValues: [VideoProject] {
        return saveProjectState.withLock(\.argValues).map(\.value)
    }
    var saveProjectHandler: (@Sendable (VideoProject) async throws -> ())? {
        get { saveProjectState.withLock(\.handler) }
        set { saveProjectState.withLock { $0.handler = newValue } }
    }
    func saveProject(_ project: VideoProject) async throws {
        warnIfNotSendable(project)
        let saveProjectHandler = saveProjectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((project)))
            return state.handler
        }
        if let saveProjectHandler = saveProjectHandler {
            try await saveProjectHandler(project)
        }

    }

    private let deleteProjectState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) async throws -> ()>())
    var deleteProjectCallCount: Int {
        return deleteProjectState.withLock(\.callCount)
    }
    var deleteProjectArgValues: [VideoProject] {
        return deleteProjectState.withLock(\.argValues).map(\.value)
    }
    var deleteProjectHandler: (@Sendable (VideoProject) async throws -> ())? {
        get { deleteProjectState.withLock(\.handler) }
        set { deleteProjectState.withLock { $0.handler = newValue } }
    }
    func deleteProject(_ project: VideoProject) async throws {
        warnIfNotSendable(project)
        let deleteProjectHandler = deleteProjectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((project)))
            return state.handler
        }
        if let deleteProjectHandler = deleteProjectHandler {
            try await deleteProjectHandler(project)
        }

    }

    private let recentProjectsState = MockoloMutex(MockoloHandlerState<Int, @Sendable (Int) async throws -> [VideoProject]>())
    var recentProjectsCallCount: Int {
        return recentProjectsState.withLock(\.callCount)
    }
    var recentProjectsArgValues: [Int] {
        return recentProjectsState.withLock(\.argValues).map(\.value)
    }
    var recentProjectsHandler: (@Sendable (Int) async throws -> [VideoProject])? {
        get { recentProjectsState.withLock(\.handler) }
        set { recentProjectsState.withLock { $0.handler = newValue } }
    }
    func recentProjects(limit: Int) async throws -> [VideoProject] {
        warnIfNotSendable(limit)
        let recentProjectsHandler = recentProjectsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((limit)))
            return state.handler
        }
        if let recentProjectsHandler = recentProjectsHandler {
            return try await recentProjectsHandler(limit)
        }
        return [VideoProject]()
    }

    private let fileURLState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) -> URL>())
    var fileURLCallCount: Int {
        return fileURLState.withLock(\.callCount)
    }
    var fileURLArgValues: [VideoProject] {
        return fileURLState.withLock(\.argValues).map(\.value)
    }
    var fileURLHandler: (@Sendable (VideoProject) -> URL)? {
        get { fileURLState.withLock(\.handler) }
        set { fileURLState.withLock { $0.handler = newValue } }
    }
    func fileURL(for project: VideoProject) -> URL {
        warnIfNotSendable(project)
        let fileURLHandler = fileURLState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((project)))
            return state.handler
        }
        if let fileURLHandler = fileURLHandler {
            return fileURLHandler(project)
        }
        return URL(fileURLWithPath: "")
    }
}

final class CameraServiceProtocolMock: CameraServiceProtocol, @unchecked Sendable {
    init() { }
    init(isActive: Bool = false, hasVideoSignal: Bool = false, permissionGranted: Bool = false, lastError: AppError? = nil, session: AVCaptureSession? = nil) {
        self.isActive = isActive
        self.hasVideoSignal = hasVideoSignal
        self.permissionGranted = permissionGranted
        self.lastError = lastError
        self.session = session
    }



    var isActive: Bool = false


    var hasVideoSignal: Bool = false


    var permissionGranted: Bool = false


    var lastError: AppError? = nil


    var session: AVCaptureSession? = nil

    var isActivePublisher: AnyPublisher<Bool, Never> { return self.isActivePublisherSubject.eraseToAnyPublisher() }
    private(set) var isActivePublisherSubject = PassthroughSubject<Bool, Never>()

    var sessionPublisher: AnyPublisher<AVCaptureSession?, Never> { return self.sessionPublisherSubject.eraseToAnyPublisher() }
    private(set) var sessionPublisherSubject = PassthroughSubject<AVCaptureSession?, Never>()


    // CRITICAL: Must be nonisolated(unsafe) to allow access from RecordingEngine's @RecordingActor context
    // PassthroughSubject is thread-safe internally, so this is safe
    // Initialized directly to avoid race condition in lazy initialization
    nonisolated(unsafe) private(set) var sampleBufferSubject = PassthroughSubject<CMSampleBuffer, Never>()

    private let startState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> ()>())
    var startCallCount: Int {
        return startState.withLock(\.callCount)
    }
    var startHandler: (@Sendable () async throws -> ())? {
        get { startState.withLock(\.handler) }
        set { startState.withLock { $0.handler = newValue } }
    }
    func start() async throws {
        let startHandler = startState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let startHandler = startHandler {
            try await startHandler()
        }

    }

    private let stopState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> ()>())
    var stopCallCount: Int {
        return stopState.withLock(\.callCount)
    }
    var stopHandler: (@Sendable () -> ())? {
        get { stopState.withLock(\.handler) }
        set { stopState.withLock { $0.handler = newValue } }
    }
    func stop() {
        let stopHandler = stopState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let stopHandler = stopHandler {
            stopHandler()
        }

    }

    private let toggleState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> ()>())
    var toggleCallCount: Int {
        return toggleState.withLock(\.callCount)
    }
    var toggleHandler: (@Sendable () -> ())? {
        get { toggleState.withLock(\.handler) }
        set { toggleState.withLock { $0.handler = newValue } }
    }
    func toggle() {
        let toggleHandler = toggleState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let toggleHandler = toggleHandler {
            toggleHandler()
        }

    }

    private let requestPermissionAgainState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> ()>())
    var requestPermissionAgainCallCount: Int {
        return requestPermissionAgainState.withLock(\.callCount)
    }
    var requestPermissionAgainHandler: (@Sendable () -> ())? {
        get { requestPermissionAgainState.withLock(\.handler) }
        set { requestPermissionAgainState.withLock { $0.handler = newValue } }
    }
    func requestPermissionAgain() {
        let requestPermissionAgainHandler = requestPermissionAgainState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestPermissionAgainHandler = requestPermissionAgainHandler {
            requestPermissionAgainHandler()
        }

    }

    private let restartSessionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> ()>())
    var restartSessionCallCount: Int {
        return restartSessionState.withLock(\.callCount)
    }
    var restartSessionHandler: (@Sendable () -> ())? {
        get { restartSessionState.withLock(\.handler) }
        set { restartSessionState.withLock { $0.handler = newValue } }
    }
    func restartSession() {
        let restartSessionHandler = restartSessionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let restartSessionHandler = restartSessionHandler {
            restartSessionHandler()
        }

    }
}

fileprivate func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

fileprivate func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {
}

/// Will be replaced to `Synchronization.Mutex` in future.
fileprivate final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        self.value = initialValue
    }
#if compiler(>=6.0)
    borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#else
    func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#endif
}

fileprivate struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

fileprivate struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler? = nil
    var callCount: Int = 0
}
