///
/// @Generated by Mockolo
///

import AppKit
import AVFoundation
import Combine
import CoreImage
import CoreMedia
import Foundation
@testable import SaneVideo
import ScreenCaptureKit
import Vision

final class ExportServiceProtocolMock: ExportServiceProtocol, @unchecked Sendable {
    init() {}
    init(progress: Double = 0.0, isExporting: Bool = false) {
        self.progress = progress
        self.isExporting = isExporting
    }

    var progress: Double = 0.0

    var isExporting: Bool = false

    private let exportState = MockoloMutex(MockoloHandlerState<(project: VideoProject, settings: SaneExportSettings, outputURL: URL), @Sendable (VideoProject, SaneExportSettings, URL, @escaping @Sendable (Double) -> Void) async throws -> URL>())
    var exportCallCount: Int {
        return exportState.withLock(\.callCount)
    }

    var exportArgValues: [(project: VideoProject, settings: SaneExportSettings, outputURL: URL)] {
        return exportState.withLock(\.argValues).map(\.value)
    }

    var exportHandler: (@Sendable (VideoProject, SaneExportSettings, URL, @escaping @Sendable (Double) -> Void) async throws -> URL)? {
        get { exportState.withLock(\.handler) }
        set { exportState.withLock { $0.handler = newValue } }
    }

    func export(project: VideoProject, settings: SaneExportSettings, outputURL: URL, progressHandler: @escaping @Sendable (Double) -> Void) async throws -> URL {
        warnIfNotSendable(project, settings, outputURL)
        let exportHandler = exportState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((project, settings, outputURL)))
            return state.handler
        }
        if let exportHandler = exportHandler {
            return try await exportHandler(project, settings, outputURL, progressHandler)
        }
        return URL(fileURLWithPath: "")
    }

    private let cancelExportState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var cancelExportCallCount: Int {
        return cancelExportState.withLock(\.callCount)
    }

    var cancelExportHandler: (@Sendable () -> Void)? {
        get { cancelExportState.withLock(\.handler) }
        set { cancelExportState.withLock { $0.handler = newValue } }
    }

    func cancelExport() {
        let cancelExportHandler = cancelExportState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cancelExportHandler = cancelExportHandler {
            cancelExportHandler()
        }
    }
}

final class ProjectStoreProtocolMock: ProjectStoreProtocol, @unchecked Sendable {
    init() {}

    private let loadProjectsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> [VideoProject]>())
    var loadProjectsCallCount: Int {
        return loadProjectsState.withLock(\.callCount)
    }

    var loadProjectsHandler: (@Sendable () async throws -> [VideoProject])? {
        get { loadProjectsState.withLock(\.handler) }
        set { loadProjectsState.withLock { $0.handler = newValue } }
    }

    func loadProjects() async throws -> [VideoProject] {
        let loadProjectsHandler = loadProjectsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let loadProjectsHandler = loadProjectsHandler {
            return try await loadProjectsHandler()
        }
        return [VideoProject]()
    }

    private let saveProjectState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) async throws -> Void>())
    var saveProjectCallCount: Int {
        return saveProjectState.withLock(\.callCount)
    }

    var saveProjectArgValues: [VideoProject] {
        return saveProjectState.withLock(\.argValues).map(\.value)
    }

    var saveProjectHandler: (@Sendable (VideoProject) async throws -> Void)? {
        get { saveProjectState.withLock(\.handler) }
        set { saveProjectState.withLock { $0.handler = newValue } }
    }

    func saveProject(_ project: VideoProject) async throws {
        warnIfNotSendable(project)
        let saveProjectHandler = saveProjectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(project))
            return state.handler
        }
        if let saveProjectHandler = saveProjectHandler {
            try await saveProjectHandler(project)
        }
    }

    private let deleteProjectState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) async throws -> Void>())
    var deleteProjectCallCount: Int {
        return deleteProjectState.withLock(\.callCount)
    }

    var deleteProjectArgValues: [VideoProject] {
        return deleteProjectState.withLock(\.argValues).map(\.value)
    }

    var deleteProjectHandler: (@Sendable (VideoProject) async throws -> Void)? {
        get { deleteProjectState.withLock(\.handler) }
        set { deleteProjectState.withLock { $0.handler = newValue } }
    }

    func deleteProject(_ project: VideoProject) async throws {
        warnIfNotSendable(project)
        let deleteProjectHandler = deleteProjectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(project))
            return state.handler
        }
        if let deleteProjectHandler = deleteProjectHandler {
            try await deleteProjectHandler(project)
        }
    }

    private let recentProjectsState = MockoloMutex(MockoloHandlerState<Int, @Sendable (Int) async throws -> [VideoProject]>())
    var recentProjectsCallCount: Int {
        return recentProjectsState.withLock(\.callCount)
    }

    var recentProjectsArgValues: [Int] {
        return recentProjectsState.withLock(\.argValues).map(\.value)
    }

    var recentProjectsHandler: (@Sendable (Int) async throws -> [VideoProject])? {
        get { recentProjectsState.withLock(\.handler) }
        set { recentProjectsState.withLock { $0.handler = newValue } }
    }

    func recentProjects(limit: Int) async throws -> [VideoProject] {
        warnIfNotSendable(limit)
        let recentProjectsHandler = recentProjectsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(limit))
            return state.handler
        }
        if let recentProjectsHandler = recentProjectsHandler {
            return try await recentProjectsHandler(limit)
        }
        return [VideoProject]()
    }

    private let fileURLState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) -> URL>())
    var fileURLCallCount: Int {
        return fileURLState.withLock(\.callCount)
    }

    var fileURLArgValues: [VideoProject] {
        return fileURLState.withLock(\.argValues).map(\.value)
    }

    var fileURLHandler: (@Sendable (VideoProject) -> URL)? {
        get { fileURLState.withLock(\.handler) }
        set { fileURLState.withLock { $0.handler = newValue } }
    }

    func fileURL(for project: VideoProject) -> URL {
        warnIfNotSendable(project)
        let fileURLHandler = fileURLState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(project))
            return state.handler
        }
        if let fileURLHandler = fileURLHandler {
            return fileURLHandler(project)
        }
        return URL(fileURLWithPath: "")
    }
}

actor WaveformServiceProtocolMock: WaveformServiceProtocol {
    init() {}

    private(set) var waveformCallCount = 0
    var waveformArgValues = [VideoClip]()
    var waveformHandler: ((VideoClip) async -> [Float]?)?
    func waveform(for clip: VideoClip) async -> [Float]? {
        waveformCallCount += 1
        waveformArgValues.append(clip)
        if let waveformHandler = waveformHandler {
            return await waveformHandler(clip)
        }
        return nil
    }

    private(set) var cancelLoadCallCount = 0
    var cancelLoadArgValues = [VideoClip]()
    var cancelLoadHandler: ((VideoClip) -> Void)?
    func cancelLoad(for clip: VideoClip) {
        cancelLoadCallCount += 1
        cancelLoadArgValues.append(clip)
        if let cancelLoadHandler = cancelLoadHandler {
            cancelLoadHandler(clip)
        }
    }

    private(set) var clearCacheCallCount = 0
    var clearCacheHandler: (() -> Void)?
    func clearCache() {
        clearCacheCallCount += 1
        if let clearCacheHandler = clearCacheHandler {
            clearCacheHandler()
        }
    }
}

final class CameraServiceProtocolMock: CameraServiceProtocol, @unchecked Sendable {
    init() {}
    init(isActive: Bool = false, hasVideoSignal: Bool = false, permissionGranted: Bool = false, lastError: AppError? = nil, session: AVCaptureSession? = nil) {
        self.isActive = isActive
        self.hasVideoSignal = hasVideoSignal
        self.permissionGranted = permissionGranted
        self.lastError = lastError
        self.session = session
    }

    var isActive: Bool = false

    var hasVideoSignal: Bool = false {
        didSet { hasVideoSignalPublisherSubject.send(hasVideoSignal) }
    }

    var permissionGranted: Bool = false

    var lastError: AppError? {
        didSet { lastErrorPublisherSubject.send(lastError) }
    }

    var session: AVCaptureSession?

    var isActivePublisher: AnyPublisher<Bool, Never> { return isActivePublisherSubject.eraseToAnyPublisher() }
    private(set) var isActivePublisherSubject = PassthroughSubject<Bool, Never>()

    var hasVideoSignalPublisher: AnyPublisher<Bool, Never> { return hasVideoSignalPublisherSubject.eraseToAnyPublisher() }
    private(set) var hasVideoSignalPublisherSubject = PassthroughSubject<Bool, Never>()

    var lastErrorPublisher: AnyPublisher<AppError?, Never> { return lastErrorPublisherSubject.eraseToAnyPublisher() }
    private(set) var lastErrorPublisherSubject = PassthroughSubject<AppError?, Never>()

    var sessionPublisher: AnyPublisher<AVCaptureSession?, Never> { return sessionPublisherSubject.eraseToAnyPublisher() }
    private(set) var sessionPublisherSubject = PassthroughSubject<AVCaptureSession?, Never>()

    private nonisolated(unsafe) var _sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> = PassthroughSubject()
    nonisolated var sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> {
        get { return _sampleBufferSubject }
        set { _sampleBufferSubject = newValue }
    }

    private let startState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> Void>())
    var startCallCount: Int {
        return startState.withLock(\.callCount)
    }

    var startHandler: (@Sendable () async throws -> Void)? {
        get { startState.withLock(\.handler) }
        set { startState.withLock { $0.handler = newValue } }
    }

    func start() async throws {
        let startHandler = startState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let startHandler = startHandler {
            try await startHandler()
        }
    }

    private let stopState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var stopCallCount: Int {
        return stopState.withLock(\.callCount)
    }

    var stopHandler: (@Sendable () -> Void)? {
        get { stopState.withLock(\.handler) }
        set { stopState.withLock { $0.handler = newValue } }
    }

    func stop() {
        let stopHandler = stopState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let stopHandler = stopHandler {
            stopHandler()
        }
    }

    private let toggleState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var toggleCallCount: Int {
        return toggleState.withLock(\.callCount)
    }

    var toggleHandler: (@Sendable () -> Void)? {
        get { toggleState.withLock(\.handler) }
        set { toggleState.withLock { $0.handler = newValue } }
    }

    func toggle() {
        let toggleHandler = toggleState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let toggleHandler = toggleHandler {
            toggleHandler()
        }
    }

    private let requestPermissionAgainState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var requestPermissionAgainCallCount: Int {
        return requestPermissionAgainState.withLock(\.callCount)
    }

    var requestPermissionAgainHandler: (@Sendable () -> Void)? {
        get { requestPermissionAgainState.withLock(\.handler) }
        set { requestPermissionAgainState.withLock { $0.handler = newValue } }
    }

    func requestPermissionAgain() {
        let requestPermissionAgainHandler = requestPermissionAgainState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestPermissionAgainHandler = requestPermissionAgainHandler {
            requestPermissionAgainHandler()
        }
    }

    private let restartSessionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var restartSessionCallCount: Int {
        return restartSessionState.withLock(\.callCount)
    }

    var restartSessionHandler: (@Sendable () -> Void)? {
        get { restartSessionState.withLock(\.handler) }
        set { restartSessionState.withLock { $0.handler = newValue } }
    }

    func restartSession() {
        let restartSessionHandler = restartSessionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let restartSessionHandler = restartSessionHandler {
            restartSessionHandler()
        }
    }
}

final class ProjectFileManagerProtocolMock: ProjectFileManagerProtocol, @unchecked Sendable {
    init() {}

    private let loadClipState = MockoloMutex(MockoloHandlerState<URL, @Sendable (URL) async throws -> VideoClip>())
    var loadClipCallCount: Int {
        return loadClipState.withLock(\.callCount)
    }

    var loadClipArgValues: [URL] {
        return loadClipState.withLock(\.argValues).map(\.value)
    }

    var loadClipHandler: (@Sendable (URL) async throws -> VideoClip)? {
        get { loadClipState.withLock(\.handler) }
        set { loadClipState.withLock { $0.handler = newValue } }
    }

    func loadClip(from url: URL) async throws -> VideoClip {
        warnIfNotSendable(url)
        let loadClipHandler = loadClipState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(url))
            return state.handler
        }
        if let loadClipHandler = loadClipHandler {
            return try await loadClipHandler(url)
        }
        fatalError("loadClipHandler returns can't have a default value thus its handler must be set")
    }

    private let createBookmarkState = MockoloMutex(MockoloHandlerState<URL, @Sendable (URL) throws -> Data>())
    var createBookmarkCallCount: Int {
        return createBookmarkState.withLock(\.callCount)
    }

    var createBookmarkArgValues: [URL] {
        return createBookmarkState.withLock(\.argValues).map(\.value)
    }

    var createBookmarkHandler: (@Sendable (URL) throws -> Data)? {
        get { createBookmarkState.withLock(\.handler) }
        set { createBookmarkState.withLock { $0.handler = newValue } }
    }

    func createBookmark(for url: URL) throws -> Data {
        warnIfNotSendable(url)
        let createBookmarkHandler = createBookmarkState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(url))
            return state.handler
        }
        if let createBookmarkHandler = createBookmarkHandler {
            return try createBookmarkHandler(url)
        }
        return Data()
    }

    private let resolveBookmarkState = MockoloMutex(MockoloHandlerState<Data, @Sendable (Data) throws -> (URL, Bool)>())
    var resolveBookmarkCallCount: Int {
        return resolveBookmarkState.withLock(\.callCount)
    }

    var resolveBookmarkArgValues: [Data] {
        return resolveBookmarkState.withLock(\.argValues).map(\.value)
    }

    var resolveBookmarkHandler: (@Sendable (Data) throws -> (URL, Bool))? {
        get { resolveBookmarkState.withLock(\.handler) }
        set { resolveBookmarkState.withLock { $0.handler = newValue } }
    }

    func resolveBookmark(data: Data) throws -> (URL, Bool) {
        warnIfNotSendable(data)
        let resolveBookmarkHandler = resolveBookmarkState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(data))
            return state.handler
        }
        if let resolveBookmarkHandler = resolveBookmarkHandler {
            return try resolveBookmarkHandler(data)
        }
        return (URL(fileURLWithPath: ""), false)
    }

    private let deleteFileState = MockoloMutex(MockoloHandlerState<URL, @Sendable (URL) async throws -> Void>())
    var deleteFileCallCount: Int {
        return deleteFileState.withLock(\.callCount)
    }

    var deleteFileArgValues: [URL] {
        return deleteFileState.withLock(\.argValues).map(\.value)
    }

    var deleteFileHandler: (@Sendable (URL) async throws -> Void)? {
        get { deleteFileState.withLock(\.handler) }
        set { deleteFileState.withLock { $0.handler = newValue } }
    }

    func deleteFile(at url: URL) async throws {
        warnIfNotSendable(url)
        let deleteFileHandler = deleteFileState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(url))
            return state.handler
        }
        if let deleteFileHandler = deleteFileHandler {
            try await deleteFileHandler(url)
        }
    }

    private let hydrateProjectState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) -> (VideoProject, Bool)>())
    var hydrateProjectCallCount: Int {
        return hydrateProjectState.withLock(\.callCount)
    }

    var hydrateProjectArgValues: [VideoProject] {
        return hydrateProjectState.withLock(\.argValues).map(\.value)
    }

    var hydrateProjectHandler: (@Sendable (VideoProject) -> (VideoProject, Bool))? {
        get { hydrateProjectState.withLock(\.handler) }
        set { hydrateProjectState.withLock { $0.handler = newValue } }
    }

    func hydrateProject(_ project: VideoProject) -> (VideoProject, Bool) {
        warnIfNotSendable(project)
        let hydrateProjectHandler = hydrateProjectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(project))
            return state.handler
        }
        if let hydrateProjectHandler = hydrateProjectHandler {
            return hydrateProjectHandler(project)
        }
        fatalError("hydrateProjectHandler returns can't have a default value thus its handler must be set")
    }

    private let enterSecurityScopeState = MockoloMutex(MockoloHandlerState<VideoProject, @Sendable (VideoProject) -> ProjectFileManager.SecurityScopeSession>())
    var enterSecurityScopeCallCount: Int {
        return enterSecurityScopeState.withLock(\.callCount)
    }

    var enterSecurityScopeArgValues: [VideoProject] {
        return enterSecurityScopeState.withLock(\.argValues).map(\.value)
    }

    var enterSecurityScopeHandler: (@Sendable (VideoProject) -> ProjectFileManager.SecurityScopeSession)? {
        get { enterSecurityScopeState.withLock(\.handler) }
        set { enterSecurityScopeState.withLock { $0.handler = newValue } }
    }

    func enterSecurityScope(for project: VideoProject) -> ProjectFileManager.SecurityScopeSession {
        warnIfNotSendable(project)
        let enterSecurityScopeHandler = enterSecurityScopeState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(project))
            return state.handler
        }
        if let enterSecurityScopeHandler = enterSecurityScopeHandler {
            return enterSecurityScopeHandler(project)
        }
        fatalError("enterSecurityScopeHandler returns can't have a default value thus its handler must be set")
    }
}

final class PermissionManagerProtocolMock: PermissionManagerProtocol, @unchecked Sendable {
    init() {}
    init(cameraStatus: PermissionStatus, microphoneStatus: PermissionStatus, screenRecordingStatus: PermissionStatus) {
        _cameraStatus = cameraStatus
        _microphoneStatus = microphoneStatus
        _screenRecordingStatus = screenRecordingStatus
    }

    private var _cameraStatus: PermissionStatus!
    var cameraStatus: PermissionStatus {
        get { return _cameraStatus }
        set { _cameraStatus = newValue }
    }

    private var _microphoneStatus: PermissionStatus!
    var microphoneStatus: PermissionStatus {
        get { return _microphoneStatus }
        set { _microphoneStatus = newValue }
    }

    private var _screenRecordingStatus: PermissionStatus!
    var screenRecordingStatus: PermissionStatus {
        get { return _screenRecordingStatus }
        set { _screenRecordingStatus = newValue }
    }

    var cameraStatusPublisher: AnyPublisher<PermissionStatus, Never> { return cameraStatusPublisherSubject.eraseToAnyPublisher() }
    private(set) var cameraStatusPublisherSubject = PassthroughSubject<PermissionStatus, Never>()

    var microphoneStatusPublisher: AnyPublisher<PermissionStatus, Never> { return microphoneStatusPublisherSubject.eraseToAnyPublisher() }
    private(set) var microphoneStatusPublisherSubject = PassthroughSubject<PermissionStatus, Never>()

    var screenRecordingStatusPublisher: AnyPublisher<PermissionStatus, Never> { return screenRecordingStatusPublisherSubject.eraseToAnyPublisher() }
    private(set) var screenRecordingStatusPublisherSubject = PassthroughSubject<PermissionStatus, Never>()

    private let checkAllPermissionsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var checkAllPermissionsCallCount: Int {
        return checkAllPermissionsState.withLock(\.callCount)
    }

    var checkAllPermissionsHandler: (@Sendable () -> Void)? {
        get { checkAllPermissionsState.withLock(\.handler) }
        set { checkAllPermissionsState.withLock { $0.handler = newValue } }
    }

    func checkAllPermissions() {
        let checkAllPermissionsHandler = checkAllPermissionsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let checkAllPermissionsHandler = checkAllPermissionsHandler {
            checkAllPermissionsHandler()
        }
    }

    private let checkCameraPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var checkCameraPermissionCallCount: Int {
        return checkCameraPermissionState.withLock(\.callCount)
    }

    var checkCameraPermissionHandler: (@Sendable () -> Void)? {
        get { checkCameraPermissionState.withLock(\.handler) }
        set { checkCameraPermissionState.withLock { $0.handler = newValue } }
    }

    func checkCameraPermission() {
        let checkCameraPermissionHandler = checkCameraPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let checkCameraPermissionHandler = checkCameraPermissionHandler {
            checkCameraPermissionHandler()
        }
    }

    private let checkMicrophonePermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var checkMicrophonePermissionCallCount: Int {
        return checkMicrophonePermissionState.withLock(\.callCount)
    }

    var checkMicrophonePermissionHandler: (@Sendable () -> Void)? {
        get { checkMicrophonePermissionState.withLock(\.handler) }
        set { checkMicrophonePermissionState.withLock { $0.handler = newValue } }
    }

    func checkMicrophonePermission() {
        let checkMicrophonePermissionHandler = checkMicrophonePermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let checkMicrophonePermissionHandler = checkMicrophonePermissionHandler {
            checkMicrophonePermissionHandler()
        }
    }

    private let checkScreenRecordingPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var checkScreenRecordingPermissionCallCount: Int {
        return checkScreenRecordingPermissionState.withLock(\.callCount)
    }

    var checkScreenRecordingPermissionHandler: (@Sendable () -> Void)? {
        get { checkScreenRecordingPermissionState.withLock(\.handler) }
        set { checkScreenRecordingPermissionState.withLock { $0.handler = newValue } }
    }

    func checkScreenRecordingPermission() {
        let checkScreenRecordingPermissionHandler = checkScreenRecordingPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let checkScreenRecordingPermissionHandler = checkScreenRecordingPermissionHandler {
            checkScreenRecordingPermissionHandler()
        }
    }

    private let requestCameraPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> Bool>())
    var requestCameraPermissionCallCount: Int {
        return requestCameraPermissionState.withLock(\.callCount)
    }

    var requestCameraPermissionHandler: (@Sendable () async -> Bool)? {
        get { requestCameraPermissionState.withLock(\.handler) }
        set { requestCameraPermissionState.withLock { $0.handler = newValue } }
    }

    func requestCameraPermission() async -> Bool {
        let requestCameraPermissionHandler = requestCameraPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestCameraPermissionHandler = requestCameraPermissionHandler {
            return await requestCameraPermissionHandler()
        }
        return false
    }

    private let requestMicrophonePermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> Bool>())
    var requestMicrophonePermissionCallCount: Int {
        return requestMicrophonePermissionState.withLock(\.callCount)
    }

    var requestMicrophonePermissionHandler: (@Sendable () async -> Bool)? {
        get { requestMicrophonePermissionState.withLock(\.handler) }
        set { requestMicrophonePermissionState.withLock { $0.handler = newValue } }
    }

    func requestMicrophonePermission() async -> Bool {
        let requestMicrophonePermissionHandler = requestMicrophonePermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestMicrophonePermissionHandler = requestMicrophonePermissionHandler {
            return await requestMicrophonePermissionHandler()
        }
        return false
    }

    private let requestScreenRecordingPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var requestScreenRecordingPermissionCallCount: Int {
        return requestScreenRecordingPermissionState.withLock(\.callCount)
    }

    var requestScreenRecordingPermissionHandler: (@Sendable () -> Void)? {
        get { requestScreenRecordingPermissionState.withLock(\.handler) }
        set { requestScreenRecordingPermissionState.withLock { $0.handler = newValue } }
    }

    func requestScreenRecordingPermission() {
        let requestScreenRecordingPermissionHandler = requestScreenRecordingPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestScreenRecordingPermissionHandler = requestScreenRecordingPermissionHandler {
            requestScreenRecordingPermissionHandler()
        }
    }

    private let requestAllPermissionsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [String: Bool]>())
    var requestAllPermissionsCallCount: Int {
        return requestAllPermissionsState.withLock(\.callCount)
    }

    var requestAllPermissionsHandler: (@Sendable () async -> [String: Bool])? {
        get { requestAllPermissionsState.withLock(\.handler) }
        set { requestAllPermissionsState.withLock { $0.handler = newValue } }
    }

    func requestAllPermissions() async -> [String: Bool] {
        let requestAllPermissionsHandler = requestAllPermissionsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestAllPermissionsHandler = requestAllPermissionsHandler {
            return await requestAllPermissionsHandler()
        }
        return [String: Bool]()
    }

    private let openSystemSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var openSystemSettingsCallCount: Int {
        return openSystemSettingsState.withLock(\.callCount)
    }

    var openSystemSettingsHandler: (@Sendable () -> Void)? {
        get { openSystemSettingsState.withLock(\.handler) }
        set { openSystemSettingsState.withLock { $0.handler = newValue } }
    }

    func openSystemSettings() {
        let openSystemSettingsHandler = openSystemSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let openSystemSettingsHandler = openSystemSettingsHandler {
            openSystemSettingsHandler()
        }
    }

    private let openCameraSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var openCameraSettingsCallCount: Int {
        return openCameraSettingsState.withLock(\.callCount)
    }

    var openCameraSettingsHandler: (@Sendable () -> Void)? {
        get { openCameraSettingsState.withLock(\.handler) }
        set { openCameraSettingsState.withLock { $0.handler = newValue } }
    }

    func openCameraSettings() {
        let openCameraSettingsHandler = openCameraSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let openCameraSettingsHandler = openCameraSettingsHandler {
            openCameraSettingsHandler()
        }
    }

    private let openMicrophoneSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var openMicrophoneSettingsCallCount: Int {
        return openMicrophoneSettingsState.withLock(\.callCount)
    }

    var openMicrophoneSettingsHandler: (@Sendable () -> Void)? {
        get { openMicrophoneSettingsState.withLock(\.handler) }
        set { openMicrophoneSettingsState.withLock { $0.handler = newValue } }
    }

    func openMicrophoneSettings() {
        let openMicrophoneSettingsHandler = openMicrophoneSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let openMicrophoneSettingsHandler = openMicrophoneSettingsHandler {
            openMicrophoneSettingsHandler()
        }
    }

    private let openScreenRecordingSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var openScreenRecordingSettingsCallCount: Int {
        return openScreenRecordingSettingsState.withLock(\.callCount)
    }

    var openScreenRecordingSettingsHandler: (@Sendable () -> Void)? {
        get { openScreenRecordingSettingsState.withLock(\.handler) }
        set { openScreenRecordingSettingsState.withLock { $0.handler = newValue } }
    }

    func openScreenRecordingSettings() {
        let openScreenRecordingSettingsHandler = openScreenRecordingSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let openScreenRecordingSettingsHandler = openScreenRecordingSettingsHandler {
            openScreenRecordingSettingsHandler()
        }
    }

    private let verifyPermissionsForRecordingState = MockoloMutex(MockoloHandlerState<(requiresCamera: Bool, requiresMicrophone: Bool, requiresScreenRecording: Bool), @Sendable (Bool, Bool, Bool) -> Bool>())
    var verifyPermissionsForRecordingCallCount: Int {
        return verifyPermissionsForRecordingState.withLock(\.callCount)
    }

    var verifyPermissionsForRecordingArgValues: [(requiresCamera: Bool, requiresMicrophone: Bool, requiresScreenRecording: Bool)] {
        return verifyPermissionsForRecordingState.withLock(\.argValues).map(\.value)
    }

    var verifyPermissionsForRecordingHandler: (@Sendable (Bool, Bool, Bool) -> Bool)? {
        get { verifyPermissionsForRecordingState.withLock(\.handler) }
        set { verifyPermissionsForRecordingState.withLock { $0.handler = newValue } }
    }

    func verifyPermissionsForRecording(requiresCamera: Bool, requiresMicrophone: Bool, requiresScreenRecording: Bool) -> Bool {
        warnIfNotSendable(requiresCamera, requiresMicrophone, requiresScreenRecording)
        let verifyPermissionsForRecordingHandler = verifyPermissionsForRecordingState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((requiresCamera, requiresMicrophone, requiresScreenRecording)))
            return state.handler
        }
        if let verifyPermissionsForRecordingHandler = verifyPermissionsForRecordingHandler {
            return verifyPermissionsForRecordingHandler(requiresCamera, requiresMicrophone, requiresScreenRecording)
        }
        return false
    }
}

final class VideoWriterProtocolMock: VideoWriterProtocol, @unchecked Sendable {
    init() {}
    init(isWriting: Bool = false, error: Error? = nil, isReadyForData: Bool = false) {
        self.isWriting = isWriting
        self.error = error
        self.isReadyForData = isReadyForData
    }

    var isWriting: Bool = false

    var error: Error?

    var isReadyForData: Bool = false

    var driftTracker: DriftTracker?

    private let startState = MockoloMutex(MockoloHandlerState<(URL, Double), @Sendable (URL, Double) throws -> Void>())
    var startCallCount: Int {
        return startState.withLock(\.callCount)
    }

    var startArgValues: [(URL, Double)] {
        return startState.withLock(\.argValues).map(\.value)
    }

    var startHandler: (@Sendable (URL, Double) throws -> Void)? {
        get { startState.withLock(\.handler) }
        set { startState.withLock { $0.handler = newValue } }
    }

    func start(outputURL: URL, targetFrameRate: Double) throws {
        warnIfNotSendable(outputURL)
        let startHandler = startState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((outputURL, targetFrameRate)))
            return state.handler
        }
        if let startHandler = startHandler {
            try startHandler(outputURL, targetFrameRate)
        }
    }

    private let startSessionState = MockoloMutex(MockoloHandlerState<CMTime, @Sendable (CMTime) -> Void>())
    var startSessionCallCount: Int {
        return startSessionState.withLock(\.callCount)
    }

    var startSessionArgValues: [CMTime] {
        return startSessionState.withLock(\.argValues).map(\.value)
    }

    var startSessionHandler: (@Sendable (CMTime) -> Void)? {
        get { startSessionState.withLock(\.handler) }
        set { startSessionState.withLock { $0.handler = newValue } }
    }

    func startSession(at sourceTime: CMTime) {
        warnIfNotSendable(sourceTime)
        let startSessionHandler = startSessionState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(sourceTime))
            return state.handler
        }
        if let startSessionHandler = startSessionHandler {
            startSessionHandler(sourceTime)
        }
    }

    private let finishState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> URL?>())
    var finishCallCount: Int {
        return finishState.withLock(\.callCount)
    }

    var finishHandler: (@Sendable () async -> URL?)? {
        get { finishState.withLock(\.handler) }
        set { finishState.withLock { $0.handler = newValue } }
    }

    func finish() async -> URL? {
        let finishHandler = finishState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let finishHandler = finishHandler {
            return await finishHandler()
        }
        return nil
    }

    private let writeVideoState = MockoloMutex(MockoloHandlerState<(sampleBuffer: CMSampleBuffer, presentationTime: CMTime, source: RecordingSource), @Sendable (CMSampleBuffer, CMTime, RecordingSource) -> Bool>())
    var writeVideoCallCount: Int {
        return writeVideoState.withLock(\.callCount)
    }

    var writeVideoArgValues: [(sampleBuffer: CMSampleBuffer, presentationTime: CMTime, source: RecordingSource)] {
        return writeVideoState.withLock(\.argValues).map(\.value)
    }

    var writeVideoHandler: (@Sendable (CMSampleBuffer, CMTime, RecordingSource) -> Bool)? {
        get { writeVideoState.withLock(\.handler) }
        set { writeVideoState.withLock { $0.handler = newValue } }
    }

    func writeVideo(sampleBuffer: CMSampleBuffer, presentationTime: CMTime, source: RecordingSource) -> Bool {
        warnIfNotSendable(sampleBuffer, presentationTime, source)
        let writeVideoHandler = writeVideoState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((sampleBuffer, presentationTime, source)))
            return state.handler
        }
        if let writeVideoHandler = writeVideoHandler {
            return writeVideoHandler(sampleBuffer, presentationTime, source)
        }
        return true
    }

    private let writeMicAudioState = MockoloMutex(MockoloHandlerState<CMSampleBuffer, @Sendable (CMSampleBuffer) -> Bool>())
    var writeMicAudioCallCount: Int {
        return writeMicAudioState.withLock(\.callCount)
    }

    var writeMicAudioArgValues: [CMSampleBuffer] {
        return writeMicAudioState.withLock(\.argValues).map(\.value)
    }

    var writeMicAudioHandler: (@Sendable (CMSampleBuffer) -> Bool)? {
        get { writeMicAudioState.withLock(\.handler) }
        set { writeMicAudioState.withLock { $0.handler = newValue } }
    }

    func writeMicAudio(sampleBuffer: CMSampleBuffer) -> Bool {
        warnIfNotSendable(sampleBuffer)
        let writeMicAudioHandler = writeMicAudioState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(sampleBuffer))
            return state.handler
        }
        if let writeMicAudioHandler = writeMicAudioHandler {
            return writeMicAudioHandler(sampleBuffer)
        }
        return true
    }

    private let writeSystemAudioState = MockoloMutex(MockoloHandlerState<CMSampleBuffer, @Sendable (CMSampleBuffer) -> Bool>())
    var writeSystemAudioCallCount: Int {
        return writeSystemAudioState.withLock(\.callCount)
    }

    var writeSystemAudioArgValues: [CMSampleBuffer] {
        return writeSystemAudioState.withLock(\.argValues).map(\.value)
    }

    var writeSystemAudioHandler: (@Sendable (CMSampleBuffer) -> Bool)? {
        get { writeSystemAudioState.withLock(\.handler) }
        set { writeSystemAudioState.withLock { $0.handler = newValue } }
    }

    func writeSystemAudio(sampleBuffer: CMSampleBuffer) -> Bool {
        warnIfNotSendable(sampleBuffer)
        let writeSystemAudioHandler = writeSystemAudioState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(sampleBuffer))
            return state.handler
        }
        if let writeSystemAudioHandler = writeSystemAudioHandler {
            return writeSystemAudioHandler(sampleBuffer)
        }
        return true
    }

    private let updateCameraFrameState = MockoloMutex(MockoloHandlerState<CVPixelBuffer?, @Sendable (CVPixelBuffer?) -> Void>())
    var updateCameraFrameCallCount: Int {
        return updateCameraFrameState.withLock(\.callCount)
    }

    var updateCameraFrameArgValues: [CVPixelBuffer?] {
        return updateCameraFrameState.withLock(\.argValues).map(\.value)
    }

    var updateCameraFrameHandler: (@Sendable (CVPixelBuffer?) -> Void)? {
        get { updateCameraFrameState.withLock(\.handler) }
        set { updateCameraFrameState.withLock { $0.handler = newValue } }
    }

    func updateCameraFrame(_ pixelBuffer: CVPixelBuffer?) {
        warnIfNotSendable(pixelBuffer)
        let updateCameraFrameHandler = updateCameraFrameState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(pixelBuffer))
            return state.handler
        }
        if let updateCameraFrameHandler = updateCameraFrameHandler {
            updateCameraFrameHandler(pixelBuffer)
        }
    }

    private let updatePiPFrameState = MockoloMutex(MockoloHandlerState<(frame: CGRect?, screenFrame: CGRect?), @Sendable (CGRect?, CGRect?) -> Void>())
    var updatePiPFrameCallCount: Int {
        return updatePiPFrameState.withLock(\.callCount)
    }

    var updatePiPFrameArgValues: [(frame: CGRect?, screenFrame: CGRect?)] {
        return updatePiPFrameState.withLock(\.argValues).map(\.value)
    }

    var updatePiPFrameHandler: (@Sendable (CGRect?, CGRect?) -> Void)? {
        get { updatePiPFrameState.withLock(\.handler) }
        set { updatePiPFrameState.withLock { $0.handler = newValue } }
    }

    func updatePiPFrame(_ frame: CGRect?, screenFrame: CGRect?) {
        warnIfNotSendable(frame, screenFrame)
        let updatePiPFrameHandler = updatePiPFrameState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((frame, screenFrame)))
            return state.handler
        }
        if let updatePiPFrameHandler = updatePiPFrameHandler {
            updatePiPFrameHandler(frame, screenFrame)
        }
    }
}

actor ThumbnailServiceProtocolMock: ThumbnailServiceProtocol {
    init() {}

    private(set) var thumbnailCallCount = 0
    var thumbnailArgValues = [(clip: VideoClip, time: CMTime, size: CGSize)]()
    var thumbnailHandler: ((VideoClip, CMTime, CGSize) async -> UncheckedBox<NSImage>?)?
    func thumbnail(for clip: VideoClip, time: CMTime, size: CGSize) async -> UncheckedBox<NSImage>? {
        thumbnailCallCount += 1
        thumbnailArgValues.append((clip, time, size))
        if let thumbnailHandler = thumbnailHandler {
            return await thumbnailHandler(clip, time, size)
        }
        return nil
    }

    private(set) var clearCacheCallCount = 0
    var clearCacheHandler: (() -> Void)?
    func clearCache() {
        clearCacheCallCount += 1
        if let clearCacheHandler = clearCacheHandler {
            clearCacheHandler()
        }
    }

    private(set) var generateBestThumbnailCallCount = 0
    var generateBestThumbnailArgValues = [(url: URL, strategy: ThumbnailScoringStrategy)]()
    var generateBestThumbnailHandler: ((URL, ThumbnailScoringStrategy) async throws -> UncheckedBox<NSImage>)?
    func generateBestThumbnail(for url: URL, strategy: ThumbnailScoringStrategy) async throws -> UncheckedBox<NSImage> {
        generateBestThumbnailCallCount += 1
        generateBestThumbnailArgValues.append((url, strategy))
        if let generateBestThumbnailHandler = generateBestThumbnailHandler {
            return try await generateBestThumbnailHandler(url, strategy)
        }
        fatalError("generateBestThumbnailHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var generateSmartThumbnailCallCount = 0
    var generateSmartThumbnailArgValues = [(url: URL, strategy: ThumbnailScoringStrategy)]()
    var generateSmartThumbnailHandler: ((URL, ThumbnailScoringStrategy) async throws -> URL)?
    func generateSmartThumbnail(for url: URL, strategy: ThumbnailScoringStrategy) async throws -> URL {
        generateSmartThumbnailCallCount += 1
        generateSmartThumbnailArgValues.append((url, strategy))
        if let generateSmartThumbnailHandler = generateSmartThumbnailHandler {
            return try await generateSmartThumbnailHandler(url, strategy)
        }
        return URL(fileURLWithPath: "")
    }
}

final class RealTimeAudioProcessorProtocolMock: RealTimeAudioProcessorProtocol, @unchecked Sendable {
    init() {}

    private let setupForPlayerItemState = MockoloMutex(MockoloHandlerState<(item: AVPlayerItem, clip: VideoClip, videoPlayer: AVPlayer), @Sendable (AVPlayerItem, VideoClip, AVPlayer) async throws -> Void>())
    var setupForPlayerItemCallCount: Int {
        return setupForPlayerItemState.withLock(\.callCount)
    }

    var setupForPlayerItemArgValues: [(item: AVPlayerItem, clip: VideoClip, videoPlayer: AVPlayer)] {
        return setupForPlayerItemState.withLock(\.argValues).map(\.value)
    }

    var setupForPlayerItemHandler: (@Sendable (AVPlayerItem, VideoClip, AVPlayer) async throws -> Void)? {
        get { setupForPlayerItemState.withLock(\.handler) }
        set { setupForPlayerItemState.withLock { $0.handler = newValue } }
    }

    func setupForPlayerItem(_ item: AVPlayerItem, clip: VideoClip, videoPlayer: AVPlayer) async throws {
        warnIfNotSendable(item, clip, videoPlayer)
        let setupForPlayerItemHandler = setupForPlayerItemState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((item, clip, videoPlayer)))
            return state.handler
        }
        if let setupForPlayerItemHandler = setupForPlayerItemHandler {
            try await setupForPlayerItemHandler(item, clip, videoPlayer)
        }
    }

    private let playState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var playCallCount: Int {
        return playState.withLock(\.callCount)
    }

    var playHandler: (@Sendable () -> Void)? {
        get { playState.withLock(\.handler) }
        set { playState.withLock { $0.handler = newValue } }
    }

    func play() {
        let playHandler = playState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let playHandler = playHandler {
            playHandler()
        }
    }

    private let pauseState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var pauseCallCount: Int {
        return pauseState.withLock(\.callCount)
    }

    var pauseHandler: (@Sendable () -> Void)? {
        get { pauseState.withLock(\.handler) }
        set { pauseState.withLock { $0.handler = newValue } }
    }

    func pause() {
        let pauseHandler = pauseState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let pauseHandler = pauseHandler {
            pauseHandler()
        }
    }

    private let seekState = MockoloMutex(MockoloHandlerState<CMTime, @Sendable (CMTime) -> Void>())
    var seekCallCount: Int {
        return seekState.withLock(\.callCount)
    }

    var seekArgValues: [CMTime] {
        return seekState.withLock(\.argValues).map(\.value)
    }

    var seekHandler: (@Sendable (CMTime) -> Void)? {
        get { seekState.withLock(\.handler) }
        set { seekState.withLock { $0.handler = newValue } }
    }

    func seek(to time: CMTime) {
        warnIfNotSendable(time)
        let seekHandler = seekState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(time))
            return state.handler
        }
        if let seekHandler = seekHandler {
            seekHandler(time)
        }
    }

    private let updateEffectsState = MockoloMutex(MockoloHandlerState<VideoClip, @Sendable (VideoClip) async throws -> Void>())
    var updateEffectsCallCount: Int {
        return updateEffectsState.withLock(\.callCount)
    }

    var updateEffectsArgValues: [VideoClip] {
        return updateEffectsState.withLock(\.argValues).map(\.value)
    }

    var updateEffectsHandler: (@Sendable (VideoClip) async throws -> Void)? {
        get { updateEffectsState.withLock(\.handler) }
        set { updateEffectsState.withLock { $0.handler = newValue } }
    }

    func updateEffects(for clip: VideoClip) async throws {
        warnIfNotSendable(clip)
        let updateEffectsHandler = updateEffectsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(clip))
            return state.handler
        }
        if let updateEffectsHandler = updateEffectsHandler {
            try await updateEffectsHandler(clip)
        }
    }

    private let cleanupState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var cleanupCallCount: Int {
        return cleanupState.withLock(\.callCount)
    }

    var cleanupHandler: (@Sendable () -> Void)? {
        get { cleanupState.withLock(\.handler) }
        set { cleanupState.withLock { $0.handler = newValue } }
    }

    func cleanup() {
        let cleanupHandler = cleanupState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cleanupHandler = cleanupHandler {
            cleanupHandler()
        }
    }
}

actor TranscriptionServiceProtocolMock: TranscriptionServiceProtocol {
    init() {}

    private(set) var checkAvailabilityCallCount = 0
    var checkAvailabilityHandler: (() async -> Bool)?
    func checkAvailability() async -> Bool {
        checkAvailabilityCallCount += 1
        if let checkAvailabilityHandler = checkAvailabilityHandler {
            return await checkAvailabilityHandler()
        }
        return false
    }

    private(set) var generateCaptionsCallCount = 0
    var generateCaptionsArgValues = [URL]()
    var generateCaptionsHandler: ((URL, (@Sendable (Int, Int, Int) -> Void)?) async throws -> [Caption])?
    func generateCaptions(for videoURL: URL, progressHandler: (@Sendable (Int, Int, Int) -> Void)?) async throws -> [Caption] {
        generateCaptionsCallCount += 1
        generateCaptionsArgValues.append(videoURL)
        if let generateCaptionsHandler = generateCaptionsHandler {
            return try await generateCaptionsHandler(videoURL, progressHandler)
        }
        return [Caption]()
    }

    private(set) var cancelCallCount = 0
    var cancelHandler: (() async -> Void)?
    func cancel() async {
        cancelCallCount += 1
        if let cancelHandler = cancelHandler {
            await cancelHandler()
        }
    }
}

final class AudioServiceProtocolMock: AudioServiceProtocol, @unchecked Sendable {
    init() {}
    init(isRunning: Bool = false, permissionGranted: Bool = false, currentMicID: String? = nil, availableMicrophones: [AVCaptureDevice] = [AVCaptureDevice]()) {
        self.isRunning = isRunning
        self.permissionGranted = permissionGranted
        self.currentMicID = currentMicID
        self.availableMicrophones = availableMicrophones
    }

    var isRunning: Bool = false

    var permissionGranted: Bool = false

    var currentMicID: String?

    var availableMicrophones: [AVCaptureDevice] = .init()

    private nonisolated(unsafe) var _sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> = PassthroughSubject()
    nonisolated var sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> {
        get { return _sampleBufferSubject }
        set { _sampleBufferSubject = newValue }
    }

    private nonisolated(unsafe) var _audioLevelSubject: PassthroughSubject<Float, Never> = PassthroughSubject()
    nonisolated var audioLevelSubject: PassthroughSubject<Float, Never> {
        get { return _audioLevelSubject }
        set { _audioLevelSubject = newValue }
    }

    private let refreshMicrophonesState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var refreshMicrophonesCallCount: Int {
        return refreshMicrophonesState.withLock(\.callCount)
    }

    var refreshMicrophonesHandler: (@Sendable () -> Void)? {
        get { refreshMicrophonesState.withLock(\.handler) }
        set { refreshMicrophonesState.withLock { $0.handler = newValue } }
    }

    func refreshMicrophones() {
        let refreshMicrophonesHandler = refreshMicrophonesState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshMicrophonesHandler = refreshMicrophonesHandler {
            refreshMicrophonesHandler()
        }
    }

    private let ensureMicrophonesDiscoveredState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var ensureMicrophonesDiscoveredCallCount: Int {
        return ensureMicrophonesDiscoveredState.withLock(\.callCount)
    }

    var ensureMicrophonesDiscoveredHandler: (@Sendable () -> Void)? {
        get { ensureMicrophonesDiscoveredState.withLock(\.handler) }
        set { ensureMicrophonesDiscoveredState.withLock { $0.handler = newValue } }
    }

    func ensureMicrophonesDiscovered() {
        let ensureMicrophonesDiscoveredHandler = ensureMicrophonesDiscoveredState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let ensureMicrophonesDiscoveredHandler = ensureMicrophonesDiscoveredHandler {
            ensureMicrophonesDiscoveredHandler()
        }
    }

    private let checkPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var checkPermissionCallCount: Int {
        return checkPermissionState.withLock(\.callCount)
    }

    var checkPermissionHandler: (@Sendable () -> Void)? {
        get { checkPermissionState.withLock(\.handler) }
        set { checkPermissionState.withLock { $0.handler = newValue } }
    }

    func checkPermission() {
        let checkPermissionHandler = checkPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let checkPermissionHandler = checkPermissionHandler {
            checkPermissionHandler()
        }
    }

    private let requestPermissionState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var requestPermissionCallCount: Int {
        return requestPermissionState.withLock(\.callCount)
    }

    var requestPermissionHandler: (@Sendable () -> Void)? {
        get { requestPermissionState.withLock(\.handler) }
        set { requestPermissionState.withLock { $0.handler = newValue } }
    }

    func requestPermission() {
        let requestPermissionHandler = requestPermissionState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let requestPermissionHandler = requestPermissionHandler {
            requestPermissionHandler()
        }
    }

    private let startState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var startCallCount: Int {
        return startState.withLock(\.callCount)
    }

    var startHandler: (@Sendable () -> Void)? {
        get { startState.withLock(\.handler) }
        set { startState.withLock { $0.handler = newValue } }
    }

    func start() {
        let startHandler = startState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let startHandler = startHandler {
            startHandler()
        }
    }

    private let stopState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var stopCallCount: Int {
        return stopState.withLock(\.callCount)
    }

    var stopHandler: (@Sendable () -> Void)? {
        get { stopState.withLock(\.handler) }
        set { stopState.withLock { $0.handler = newValue } }
    }

    func stop() {
        let stopHandler = stopState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let stopHandler = stopHandler {
            stopHandler()
        }
    }

    private let switchMicrophoneState = MockoloMutex(MockoloHandlerState<AVCaptureDevice, @Sendable (AVCaptureDevice) -> Void>())
    var switchMicrophoneCallCount: Int {
        return switchMicrophoneState.withLock(\.callCount)
    }

    var switchMicrophoneArgValues: [AVCaptureDevice] {
        return switchMicrophoneState.withLock(\.argValues).map(\.value)
    }

    var switchMicrophoneHandler: (@Sendable (AVCaptureDevice) -> Void)? {
        get { switchMicrophoneState.withLock(\.handler) }
        set { switchMicrophoneState.withLock { $0.handler = newValue } }
    }

    func switchMicrophone(to device: AVCaptureDevice) {
        warnIfNotSendable(device)
        let switchMicrophoneHandler = switchMicrophoneState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(device))
            return state.handler
        }
        if let switchMicrophoneHandler = switchMicrophoneHandler {
            switchMicrophoneHandler(device)
        }
    }
}

final class FaceTrackingServiceProtocolMock: FaceTrackingServiceProtocol, @unchecked Sendable {
    init() {}

    private let detectFacesState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> [CGRect]>())
    var detectFacesCallCount: Int {
        return detectFacesState.withLock(\.callCount)
    }

    var detectFacesArgValues: [CIImage] {
        return detectFacesState.withLock(\.argValues).map(\.value)
    }

    var detectFacesHandler: (@Sendable (CIImage) async throws -> [CGRect])? {
        get { detectFacesState.withLock(\.handler) }
        set { detectFacesState.withLock { $0.handler = newValue } }
    }

    func detectFaces(in image: CIImage) async throws -> [CGRect] {
        warnIfNotSendable(image)
        let detectFacesHandler = detectFacesState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectFacesHandler = detectFacesHandler {
            return try await detectFacesHandler(image)
        }
        return [CGRect]()
    }

    private let detectFacesWithLandmarksState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> [FaceDetection]>())
    var detectFacesWithLandmarksCallCount: Int {
        return detectFacesWithLandmarksState.withLock(\.callCount)
    }

    var detectFacesWithLandmarksArgValues: [CIImage] {
        return detectFacesWithLandmarksState.withLock(\.argValues).map(\.value)
    }

    var detectFacesWithLandmarksHandler: (@Sendable (CIImage) async throws -> [FaceDetection])? {
        get { detectFacesWithLandmarksState.withLock(\.handler) }
        set { detectFacesWithLandmarksState.withLock { $0.handler = newValue } }
    }

    func detectFacesWithLandmarks(in image: CIImage) async throws -> [FaceDetection] {
        warnIfNotSendable(image)
        let detectFacesWithLandmarksHandler = detectFacesWithLandmarksState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectFacesWithLandmarksHandler = detectFacesWithLandmarksHandler {
            return try await detectFacesWithLandmarksHandler(image)
        }
        return [FaceDetection]()
    }

    private let calculateAutoFrameRectState = MockoloMutex(MockoloHandlerState<(faces: [CGRect], imageSize: CGSize, targetAspectRatio: CGFloat, padding: CGFloat), @Sendable ([CGRect], CGSize, CGFloat, CGFloat) -> CGRect>())
    var calculateAutoFrameRectCallCount: Int {
        return calculateAutoFrameRectState.withLock(\.callCount)
    }

    var calculateAutoFrameRectArgValues: [(faces: [CGRect], imageSize: CGSize, targetAspectRatio: CGFloat, padding: CGFloat)] {
        return calculateAutoFrameRectState.withLock(\.argValues).map(\.value)
    }

    var calculateAutoFrameRectHandler: (@Sendable ([CGRect], CGSize, CGFloat, CGFloat) -> CGRect)? {
        get { calculateAutoFrameRectState.withLock(\.handler) }
        set { calculateAutoFrameRectState.withLock { $0.handler = newValue } }
    }

    func calculateAutoFrameRect(faces: [CGRect], imageSize: CGSize, targetAspectRatio: CGFloat, padding: CGFloat) -> CGRect {
        warnIfNotSendable(faces, imageSize, targetAspectRatio, padding)
        let calculateAutoFrameRectHandler = calculateAutoFrameRectState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((faces, imageSize, targetAspectRatio, padding)))
            return state.handler
        }
        if let calculateAutoFrameRectHandler = calculateAutoFrameRectHandler {
            return calculateAutoFrameRectHandler(faces, imageSize, targetAspectRatio, padding)
        }
        return .zero
    }

    private let analyzeVideoState = MockoloMutex(MockoloHandlerState<(videoURL: URL, sampleInterval: TimeInterval), @Sendable (URL, TimeInterval) async throws -> [CMTime: CGRect]>())
    var analyzeVideoCallCount: Int {
        return analyzeVideoState.withLock(\.callCount)
    }

    var analyzeVideoArgValues: [(videoURL: URL, sampleInterval: TimeInterval)] {
        return analyzeVideoState.withLock(\.argValues).map(\.value)
    }

    var analyzeVideoHandler: (@Sendable (URL, TimeInterval) async throws -> [CMTime: CGRect])? {
        get { analyzeVideoState.withLock(\.handler) }
        set { analyzeVideoState.withLock { $0.handler = newValue } }
    }

    func analyzeVideo(videoURL: URL, sampleInterval: TimeInterval) async throws -> [CMTime: CGRect] {
        warnIfNotSendable(videoURL, sampleInterval)
        let analyzeVideoHandler = analyzeVideoState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((videoURL, sampleInterval)))
            return state.handler
        }
        if let analyzeVideoHandler = analyzeVideoHandler {
            return try await analyzeVideoHandler(videoURL, sampleInterval)
        }
        return [CMTime: CGRect]()
    }
}

final class ScreenRecorderProtocolMock: ScreenRecorderProtocol, @unchecked Sendable {
    init() {}
    init(activeStream: SCStream? = nil, isStopping: Bool = false, baseFilter: SCContentFilter? = nil, recordingFrame: CGRect? = nil) {
        self.activeStream = activeStream
        self.isStopping = isStopping
        self.baseFilter = baseFilter
        self.recordingFrame = recordingFrame
    }

    private nonisolated(unsafe) var _sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> = PassthroughSubject()
    nonisolated var sampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> {
        get { return _sampleBufferSubject }
        set { _sampleBufferSubject = newValue }
    }

    private nonisolated(unsafe) var _audioSampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> = PassthroughSubject()
    nonisolated var audioSampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> {
        get { return _audioSampleBufferSubject }
        set { _audioSampleBufferSubject = newValue }
    }

    private nonisolated(unsafe) var _micSampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> = PassthroughSubject()
    nonisolated var micSampleBufferSubject: PassthroughSubject<CMSampleBuffer, Never> {
        get { return _micSampleBufferSubject }
        set { _micSampleBufferSubject = newValue }
    }

    var activeStream: SCStream?

    var isStopping: Bool = false

    var baseFilter: SCContentFilter?

    var recordingFrame: CGRect?

    private(set) var onStopSetCallCount = 0
    var onStop: ((Error?) -> Void)? { didSet { onStopSetCallCount += 1 } }

    private(set) var onPresenterOverlayChangedSetCallCount = 0
    var onPresenterOverlayChanged: ((Bool) -> Void)? { didSet { onPresenterOverlayChangedSetCallCount += 1 } }

    private(set) var onContentSelectedSetCallCount = 0
    var onContentSelected: (() -> Void)? { didSet { onContentSelectedSetCallCount += 1 } }

    private let startState = MockoloMutex(MockoloHandlerState<URL?, @Sendable (URL?) async throws -> Void>())
    var startCallCount: Int {
        return startState.withLock(\.callCount)
    }

    var startArgValues: [URL?] {
        return startState.withLock(\.argValues).map(\.value)
    }

    var startHandler: (@Sendable (URL?) async throws -> Void)? {
        get { startState.withLock(\.handler) }
        set { startState.withLock { $0.handler = newValue } }
    }

    func start(outputURL: URL?) async throws {
        warnIfNotSendable(outputURL)
        let startHandler = startState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(outputURL))
            return state.handler
        }
        if let startHandler = startHandler {
            try await startHandler(outputURL)
        }
    }

    private let stopState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> Void>())
    var stopCallCount: Int {
        return stopState.withLock(\.callCount)
    }

    var stopHandler: (@Sendable () async -> Void)? {
        get { stopState.withLock(\.handler) }
        set { stopState.withLock { $0.handler = newValue } }
    }

    func stop() async {
        let stopHandler = stopState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let stopHandler = stopHandler {
            await stopHandler()
        }
    }

    private let teardownState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var teardownCallCount: Int {
        return teardownState.withLock(\.callCount)
    }

    var teardownHandler: (@Sendable () -> Void)? {
        get { teardownState.withLock(\.handler) }
        set { teardownState.withLock { $0.handler = newValue } }
    }

    func teardown() {
        let teardownHandler = teardownState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let teardownHandler = teardownHandler {
            teardownHandler()
        }
    }

    private let updateContentFilterState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> Void>())
    var updateContentFilterCallCount: Int {
        return updateContentFilterState.withLock(\.callCount)
    }

    var updateContentFilterHandler: (@Sendable () async -> Void)? {
        get { updateContentFilterState.withLock(\.handler) }
        set { updateContentFilterState.withLock { $0.handler = newValue } }
    }

    func updateContentFilter() async {
        let updateContentFilterHandler = updateContentFilterState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let updateContentFilterHandler = updateContentFilterHandler {
            await updateContentFilterHandler()
        }
    }

    private let handleContentSelectedState = MockoloMutex(MockoloHandlerState<SCContentFilter, @Sendable (SCContentFilter) async -> Void>())
    var handleContentSelectedCallCount: Int {
        return handleContentSelectedState.withLock(\.callCount)
    }

    var handleContentSelectedArgValues: [SCContentFilter] {
        return handleContentSelectedState.withLock(\.argValues).map(\.value)
    }

    var handleContentSelectedHandler: (@Sendable (SCContentFilter) async -> Void)? {
        get { handleContentSelectedState.withLock(\.handler) }
        set { handleContentSelectedState.withLock { $0.handler = newValue } }
    }

    func handleContentSelected(filter: SCContentFilter) async {
        warnIfNotSendable(filter)
        let handleContentSelectedHandler = handleContentSelectedState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(filter))
            return state.handler
        }
        if let handleContentSelectedHandler = handleContentSelectedHandler {
            await handleContentSelectedHandler(filter)
        }
    }
}

final class TranscriptionCoordinatorProtocolMock: TranscriptionCoordinatorProtocol, @unchecked Sendable {
    init() {}
    init(selectedEngine: TranscriptionEngine, shouldSuggestWhisperKit: Bool = false) {
        _selectedEngine = selectedEngine
        self.shouldSuggestWhisperKit = shouldSuggestWhisperKit
    }

    private(set) var selectedEngineSetCallCount = 0
    private var _selectedEngine: TranscriptionEngine! { didSet { selectedEngineSetCallCount += 1 } }
    var selectedEngine: TranscriptionEngine {
        get { return _selectedEngine }
        set { _selectedEngine = newValue }
    }

    var shouldSuggestWhisperKit: Bool = false

    private let generateCaptionsState = MockoloMutex(MockoloHandlerState<URL, @Sendable (URL, (@Sendable (Int, Int, Int) -> Void)?) async throws -> [Caption]>())
    var generateCaptionsCallCount: Int {
        return generateCaptionsState.withLock(\.callCount)
    }

    var generateCaptionsArgValues: [URL] {
        return generateCaptionsState.withLock(\.argValues).map(\.value)
    }

    var generateCaptionsHandler: (@Sendable (URL, (@Sendable (Int, Int, Int) -> Void)?) async throws -> [Caption])? {
        get { generateCaptionsState.withLock(\.handler) }
        set { generateCaptionsState.withLock { $0.handler = newValue } }
    }

    func generateCaptions(for videoURL: URL, progressHandler: (@Sendable (Int, Int, Int) -> Void)?) async throws -> [Caption] {
        warnIfNotSendable(videoURL)
        let generateCaptionsHandler = generateCaptionsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(videoURL))
            return state.handler
        }
        if let generateCaptionsHandler = generateCaptionsHandler {
            return try await generateCaptionsHandler(videoURL, progressHandler)
        }
        return [Caption]()
    }

    private let resetFailureCountsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var resetFailureCountsCallCount: Int {
        return resetFailureCountsState.withLock(\.callCount)
    }

    var resetFailureCountsHandler: (@Sendable () -> Void)? {
        get { resetFailureCountsState.withLock(\.handler) }
        set { resetFailureCountsState.withLock { $0.handler = newValue } }
    }

    func resetFailureCounts() {
        let resetFailureCountsHandler = resetFailureCountsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let resetFailureCountsHandler = resetFailureCountsHandler {
            resetFailureCountsHandler()
        }
    }

    private let setEngineState = MockoloMutex(MockoloHandlerState<TranscriptionEngine, @Sendable (TranscriptionEngine) -> Void>())
    var setEngineCallCount: Int {
        return setEngineState.withLock(\.callCount)
    }

    var setEngineArgValues: [TranscriptionEngine] {
        return setEngineState.withLock(\.argValues).map(\.value)
    }

    var setEngineHandler: (@Sendable (TranscriptionEngine) -> Void)? {
        get { setEngineState.withLock(\.handler) }
        set { setEngineState.withLock { $0.handler = newValue } }
    }

    func setEngine(_ engine: TranscriptionEngine) {
        warnIfNotSendable(engine)
        let setEngineHandler = setEngineState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(engine))
            return state.handler
        }
        if let setEngineHandler = setEngineHandler {
            setEngineHandler(engine)
        }
    }
}

final class SoundAnalysisServiceProtocolMock: SoundAnalysisServiceProtocol, @unchecked Sendable {
    init() {}

    private(set) var onSoundDetectedSetCallCount = 0
    var onSoundDetected: ((AudioClassification) -> Void)? { didSet { onSoundDetectedSetCallCount += 1 } }

    private let analyzeState = MockoloMutex(MockoloHandlerState<CMSampleBuffer, @Sendable (CMSampleBuffer) -> Void>())
    var analyzeCallCount: Int {
        return analyzeState.withLock(\.callCount)
    }

    var analyzeArgValues: [CMSampleBuffer] {
        return analyzeState.withLock(\.argValues).map(\.value)
    }

    var analyzeHandler: (@Sendable (CMSampleBuffer) -> Void)? {
        get { analyzeState.withLock(\.handler) }
        set { analyzeState.withLock { $0.handler = newValue } }
    }

    func analyze(sampleBuffer: CMSampleBuffer) {
        warnIfNotSendable(sampleBuffer)
        let analyzeHandler = analyzeState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(sampleBuffer))
            return state.handler
        }
        if let analyzeHandler = analyzeHandler {
            analyzeHandler(sampleBuffer)
        }
    }

    private let startRealTimeAnalysisState = MockoloMutex(MockoloHandlerState<AVAudioFormat, @Sendable (AVAudioFormat) -> Void>())
    var startRealTimeAnalysisCallCount: Int {
        return startRealTimeAnalysisState.withLock(\.callCount)
    }

    var startRealTimeAnalysisArgValues: [AVAudioFormat] {
        return startRealTimeAnalysisState.withLock(\.argValues).map(\.value)
    }

    var startRealTimeAnalysisHandler: (@Sendable (AVAudioFormat) -> Void)? {
        get { startRealTimeAnalysisState.withLock(\.handler) }
        set { startRealTimeAnalysisState.withLock { $0.handler = newValue } }
    }

    func startRealTimeAnalysis(format: AVAudioFormat) {
        warnIfNotSendable(format)
        let startRealTimeAnalysisHandler = startRealTimeAnalysisState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(format))
            return state.handler
        }
        if let startRealTimeAnalysisHandler = startRealTimeAnalysisHandler {
            startRealTimeAnalysisHandler(format)
        }
    }

    private let stopRealTimeAnalysisState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var stopRealTimeAnalysisCallCount: Int {
        return stopRealTimeAnalysisState.withLock(\.callCount)
    }

    var stopRealTimeAnalysisHandler: (@Sendable () -> Void)? {
        get { stopRealTimeAnalysisState.withLock(\.handler) }
        set { stopRealTimeAnalysisState.withLock { $0.handler = newValue } }
    }

    func stopRealTimeAnalysis() {
        let stopRealTimeAnalysisHandler = stopRealTimeAnalysisState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let stopRealTimeAnalysisHandler = stopRealTimeAnalysisHandler {
            stopRealTimeAnalysisHandler()
        }
    }
}

final class SaliencyServiceProtocolMock: SaliencyServiceProtocol, @unchecked Sendable {
    init() {}

    private let detectAttentionState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> SaliencyResult>())
    var detectAttentionCallCount: Int {
        return detectAttentionState.withLock(\.callCount)
    }

    var detectAttentionArgValues: [CIImage] {
        return detectAttentionState.withLock(\.argValues).map(\.value)
    }

    var detectAttentionHandler: (@Sendable (CIImage) async throws -> SaliencyResult)? {
        get { detectAttentionState.withLock(\.handler) }
        set { detectAttentionState.withLock { $0.handler = newValue } }
    }

    func detectAttention(in image: CIImage) async throws -> SaliencyResult {
        warnIfNotSendable(image)
        let detectAttentionHandler = detectAttentionState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectAttentionHandler = detectAttentionHandler {
            return try await detectAttentionHandler(image)
        }
        fatalError("detectAttentionHandler returns can't have a default value thus its handler must be set")
    }

    private let detectObjectsState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> [CGRect]>())
    var detectObjectsCallCount: Int {
        return detectObjectsState.withLock(\.callCount)
    }

    var detectObjectsArgValues: [CIImage] {
        return detectObjectsState.withLock(\.argValues).map(\.value)
    }

    var detectObjectsHandler: (@Sendable (CIImage) async throws -> [CGRect])? {
        get { detectObjectsState.withLock(\.handler) }
        set { detectObjectsState.withLock { $0.handler = newValue } }
    }

    func detectObjects(in image: CIImage) async throws -> [CGRect] {
        warnIfNotSendable(image)
        let detectObjectsHandler = detectObjectsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectObjectsHandler = detectObjectsHandler {
            return try await detectObjectsHandler(image)
        }
        return [CGRect]()
    }

    private let calculateSmartCropState = MockoloMutex(MockoloHandlerState<(image: CIImage, targetAspectRatio: CGFloat, padding: CGFloat), @Sendable (CIImage, CGFloat, CGFloat) async throws -> CGRect>())
    var calculateSmartCropCallCount: Int {
        return calculateSmartCropState.withLock(\.callCount)
    }

    var calculateSmartCropArgValues: [(image: CIImage, targetAspectRatio: CGFloat, padding: CGFloat)] {
        return calculateSmartCropState.withLock(\.argValues).map(\.value)
    }

    var calculateSmartCropHandler: (@Sendable (CIImage, CGFloat, CGFloat) async throws -> CGRect)? {
        get { calculateSmartCropState.withLock(\.handler) }
        set { calculateSmartCropState.withLock { $0.handler = newValue } }
    }

    func calculateSmartCrop(for image: CIImage, targetAspectRatio: CGFloat, padding: CGFloat) async throws -> CGRect {
        warnIfNotSendable(image, targetAspectRatio, padding)
        let calculateSmartCropHandler = calculateSmartCropState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, targetAspectRatio, padding)))
            return state.handler
        }
        if let calculateSmartCropHandler = calculateSmartCropHandler {
            return try await calculateSmartCropHandler(image, targetAspectRatio, padding)
        }
        return .zero
    }

    private let analyzeVideoForReframeState = MockoloMutex(MockoloHandlerState<(videoURL: URL, sampleInterval: TimeInterval), @Sendable (URL, TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [CMTime: SaliencyResult]>())
    var analyzeVideoForReframeCallCount: Int {
        return analyzeVideoForReframeState.withLock(\.callCount)
    }

    var analyzeVideoForReframeArgValues: [(videoURL: URL, sampleInterval: TimeInterval)] {
        return analyzeVideoForReframeState.withLock(\.argValues).map(\.value)
    }

    var analyzeVideoForReframeHandler: (@Sendable (URL, TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [CMTime: SaliencyResult])? {
        get { analyzeVideoForReframeState.withLock(\.handler) }
        set { analyzeVideoForReframeState.withLock { $0.handler = newValue } }
    }

    func analyzeVideoForReframe(videoURL: URL, sampleInterval: TimeInterval, progressHandler: (@Sendable (Int, Int) -> Void)?) async throws -> [CMTime: SaliencyResult] {
        warnIfNotSendable(videoURL, sampleInterval)
        let analyzeVideoForReframeHandler = analyzeVideoForReframeState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((videoURL, sampleInterval)))
            return state.handler
        }
        if let analyzeVideoForReframeHandler = analyzeVideoForReframeHandler {
            return try await analyzeVideoForReframeHandler(videoURL, sampleInterval, progressHandler)
        }
        return [CMTime: SaliencyResult]()
    }
}

final class PersonSegmentationServiceProtocolMock: PersonSegmentationServiceProtocol, @unchecked Sendable {
    init() {}

    private let generateMaskState = MockoloMutex(MockoloHandlerState<(image: CIImage, quality: VNGeneratePersonSegmentationRequest.QualityLevel, reuseRequest: Bool), @Sendable (CIImage, VNGeneratePersonSegmentationRequest.QualityLevel, Bool) async throws -> CIImage>())
    var generateMaskCallCount: Int {
        return generateMaskState.withLock(\.callCount)
    }

    var generateMaskArgValues: [(image: CIImage, quality: VNGeneratePersonSegmentationRequest.QualityLevel, reuseRequest: Bool)] {
        return generateMaskState.withLock(\.argValues).map(\.value)
    }

    var generateMaskHandler: (@Sendable (CIImage, VNGeneratePersonSegmentationRequest.QualityLevel, Bool) async throws -> CIImage)? {
        get { generateMaskState.withLock(\.handler) }
        set { generateMaskState.withLock { $0.handler = newValue } }
    }

    func generateMask(for image: CIImage, quality: VNGeneratePersonSegmentationRequest.QualityLevel, reuseRequest: Bool) async throws -> CIImage {
        warnIfNotSendable(image, quality, reuseRequest)
        let generateMaskHandler = generateMaskState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, quality, reuseRequest)))
            return state.handler
        }
        if let generateMaskHandler = generateMaskHandler {
            return try await generateMaskHandler(image, quality, reuseRequest)
        }
        fatalError("generateMaskHandler returns can't have a default value thus its handler must be set")
    }

    private let clearCacheState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> Void>())
    var clearCacheCallCount: Int {
        return clearCacheState.withLock(\.callCount)
    }

    var clearCacheHandler: (@Sendable () async -> Void)? {
        get { clearCacheState.withLock(\.handler) }
        set { clearCacheState.withLock { $0.handler = newValue } }
    }

    func clearCache() async {
        let clearCacheHandler = clearCacheState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let clearCacheHandler = clearCacheHandler {
            await clearCacheHandler()
        }
    }

    private let applyBackgroundBlurState = MockoloMutex(MockoloHandlerState<(image: CIImage, blurRadius: Float, reuseRequest: Bool), @Sendable (CIImage, Float, Bool) async throws -> CIImage>())
    var applyBackgroundBlurCallCount: Int {
        return applyBackgroundBlurState.withLock(\.callCount)
    }

    var applyBackgroundBlurArgValues: [(image: CIImage, blurRadius: Float, reuseRequest: Bool)] {
        return applyBackgroundBlurState.withLock(\.argValues).map(\.value)
    }

    var applyBackgroundBlurHandler: (@Sendable (CIImage, Float, Bool) async throws -> CIImage)? {
        get { applyBackgroundBlurState.withLock(\.handler) }
        set { applyBackgroundBlurState.withLock { $0.handler = newValue } }
    }

    func applyBackgroundBlur(to image: CIImage, blurRadius: Float, reuseRequest: Bool) async throws -> CIImage {
        warnIfNotSendable(image, blurRadius, reuseRequest)
        let applyBackgroundBlurHandler = applyBackgroundBlurState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, blurRadius, reuseRequest)))
            return state.handler
        }
        if let applyBackgroundBlurHandler = applyBackgroundBlurHandler {
            return try await applyBackgroundBlurHandler(image, blurRadius, reuseRequest)
        }
        fatalError("applyBackgroundBlurHandler returns can't have a default value thus its handler must be set")
    }

    private let replaceBackgroundState = MockoloMutex(MockoloHandlerState<(image: CIImage, color: NSColor, reuseRequest: Bool), @Sendable (CIImage, NSColor, Bool) async throws -> CIImage>())
    var replaceBackgroundCallCount: Int {
        return replaceBackgroundState.withLock(\.callCount)
    }

    var replaceBackgroundArgValues: [(image: CIImage, color: NSColor, reuseRequest: Bool)] {
        return replaceBackgroundState.withLock(\.argValues).map(\.value)
    }

    var replaceBackgroundHandler: (@Sendable (CIImage, NSColor, Bool) async throws -> CIImage)? {
        get { replaceBackgroundState.withLock(\.handler) }
        set { replaceBackgroundState.withLock { $0.handler = newValue } }
    }

    func replaceBackground(in image: CIImage, with color: NSColor, reuseRequest: Bool) async throws -> CIImage {
        warnIfNotSendable(image, color, reuseRequest)
        let replaceBackgroundHandler = replaceBackgroundState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, color, reuseRequest)))
            return state.handler
        }
        if let replaceBackgroundHandler = replaceBackgroundHandler {
            return try await replaceBackgroundHandler(image, color, reuseRequest)
        }
        fatalError("replaceBackgroundHandler returns can't have a default value thus its handler must be set")
    }

    private let replaceBackgroundInState = MockoloMutex(MockoloHandlerState<(image: CIImage, backgroundImage: CIImage, reuseRequest: Bool), @Sendable (CIImage, CIImage, Bool) async throws -> CIImage>())
    var replaceBackgroundInCallCount: Int {
        return replaceBackgroundInState.withLock(\.callCount)
    }

    var replaceBackgroundInArgValues: [(image: CIImage, backgroundImage: CIImage, reuseRequest: Bool)] {
        return replaceBackgroundInState.withLock(\.argValues).map(\.value)
    }

    var replaceBackgroundInHandler: (@Sendable (CIImage, CIImage, Bool) async throws -> CIImage)? {
        get { replaceBackgroundInState.withLock(\.handler) }
        set { replaceBackgroundInState.withLock { $0.handler = newValue } }
    }

    func replaceBackground(in image: CIImage, with backgroundImage: CIImage, reuseRequest: Bool) async throws -> CIImage {
        warnIfNotSendable(image, backgroundImage, reuseRequest)
        let replaceBackgroundInHandler = replaceBackgroundInState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, backgroundImage, reuseRequest)))
            return state.handler
        }
        if let replaceBackgroundInHandler = replaceBackgroundInHandler {
            return try await replaceBackgroundInHandler(image, backgroundImage, reuseRequest)
        }
        fatalError("replaceBackgroundInHandler returns can't have a default value thus its handler must be set")
    }
}

final class TextRecognitionServiceProtocolMock: TextRecognitionServiceProtocol, @unchecked Sendable {
    init() {}

    private let recognizeTextState = MockoloMutex(MockoloHandlerState<(image: CIImage, time: CMTime), @Sendable (CIImage, CMTime) async throws -> [SaneVideo.RecognizedText]>())
    var recognizeTextCallCount: Int {
        return recognizeTextState.withLock(\.callCount)
    }

    var recognizeTextArgValues: [(image: CIImage, time: CMTime)] {
        return recognizeTextState.withLock(\.argValues).map(\.value)
    }

    var recognizeTextHandler: (@Sendable (CIImage, CMTime) async throws -> [SaneVideo.RecognizedText])? {
        get { recognizeTextState.withLock(\.handler) }
        set { recognizeTextState.withLock { $0.handler = newValue } }
    }

    func recognizeText(in image: CIImage, at time: CMTime) async throws -> [SaneVideo.RecognizedText] {
        warnIfNotSendable(image, time)
        let recognizeTextHandler = recognizeTextState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, time)))
            return state.handler
        }
        if let recognizeTextHandler = recognizeTextHandler {
            return try await recognizeTextHandler(image, time)
        }
        return [SaneVideo.RecognizedText]()
    }

    private let scanVideoForTextState = MockoloMutex(MockoloHandlerState<(videoURL: URL, sampleInterval: TimeInterval), @Sendable (URL, TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [SaneVideo.RecognizedText]>())
    var scanVideoForTextCallCount: Int {
        return scanVideoForTextState.withLock(\.callCount)
    }

    var scanVideoForTextArgValues: [(videoURL: URL, sampleInterval: TimeInterval)] {
        return scanVideoForTextState.withLock(\.argValues).map(\.value)
    }

    var scanVideoForTextHandler: (@Sendable (URL, TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [SaneVideo.RecognizedText])? {
        get { scanVideoForTextState.withLock(\.handler) }
        set { scanVideoForTextState.withLock { $0.handler = newValue } }
    }

    func scanVideoForText(videoURL: URL, sampleInterval: TimeInterval, progressHandler: (@Sendable (Int, Int) -> Void)?) async throws -> [SaneVideo.RecognizedText] {
        warnIfNotSendable(videoURL, sampleInterval)
        let scanVideoForTextHandler = scanVideoForTextState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((videoURL, sampleInterval)))
            return state.handler
        }
        if let scanVideoForTextHandler = scanVideoForTextHandler {
            return try await scanVideoForTextHandler(videoURL, sampleInterval, progressHandler)
        }
        return [SaneVideo.RecognizedText]()
    }

    private let findSensitiveTextState = MockoloMutex(MockoloHandlerState<(image: CIImage, types: [TextType], time: CMTime), @Sendable (CIImage, [TextType], CMTime) async throws -> [SaneVideo.RecognizedText]>())
    var findSensitiveTextCallCount: Int {
        return findSensitiveTextState.withLock(\.callCount)
    }

    var findSensitiveTextArgValues: [(image: CIImage, types: [TextType], time: CMTime)] {
        return findSensitiveTextState.withLock(\.argValues).map(\.value)
    }

    var findSensitiveTextHandler: (@Sendable (CIImage, [TextType], CMTime) async throws -> [SaneVideo.RecognizedText])? {
        get { findSensitiveTextState.withLock(\.handler) }
        set { findSensitiveTextState.withLock { $0.handler = newValue } }
    }

    func findSensitiveText(in image: CIImage, types: [TextType], at time: CMTime) async throws -> [SaneVideo.RecognizedText] {
        warnIfNotSendable(image, types, time)
        let findSensitiveTextHandler = findSensitiveTextState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((image, types, time)))
            return state.handler
        }
        if let findSensitiveTextHandler = findSensitiveTextHandler {
            return try await findSensitiveTextHandler(image, types, time)
        }
        return [SaneVideo.RecognizedText]()
    }
}

final class BodyPoseServiceProtocolMock: BodyPoseServiceProtocol, @unchecked Sendable {
    init() {}

    private let detectBodyPosesState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> [BodyPose]>())
    var detectBodyPosesCallCount: Int {
        return detectBodyPosesState.withLock(\.callCount)
    }

    var detectBodyPosesArgValues: [CIImage] {
        return detectBodyPosesState.withLock(\.argValues).map(\.value)
    }

    var detectBodyPosesHandler: (@Sendable (CIImage) async throws -> [BodyPose])? {
        get { detectBodyPosesState.withLock(\.handler) }
        set { detectBodyPosesState.withLock { $0.handler = newValue } }
    }

    func detectBodyPoses(in image: CIImage) async throws -> [BodyPose] {
        warnIfNotSendable(image)
        let detectBodyPosesHandler = detectBodyPosesState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectBodyPosesHandler = detectBodyPosesHandler {
            return try await detectBodyPosesHandler(image)
        }
        return [BodyPose]()
    }

    private let detectHandPosesState = MockoloMutex(MockoloHandlerState<CIImage, @Sendable (CIImage) async throws -> [HandPose]>())
    var detectHandPosesCallCount: Int {
        return detectHandPosesState.withLock(\.callCount)
    }

    var detectHandPosesArgValues: [CIImage] {
        return detectHandPosesState.withLock(\.argValues).map(\.value)
    }

    var detectHandPosesHandler: (@Sendable (CIImage) async throws -> [HandPose])? {
        get { detectHandPosesState.withLock(\.handler) }
        set { detectHandPosesState.withLock { $0.handler = newValue } }
    }

    func detectHandPoses(in image: CIImage) async throws -> [HandPose] {
        warnIfNotSendable(image)
        let detectHandPosesHandler = detectHandPosesState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(image))
            return state.handler
        }
        if let detectHandPosesHandler = detectHandPosesHandler {
            return try await detectHandPosesHandler(image)
        }
        return [HandPose]()
    }

    private let detectGesturesState = MockoloMutex(MockoloHandlerState<(videoURL: URL, gestures: [BodyGesture], sampleInterval: TimeInterval), @Sendable (URL, [BodyGesture], TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [(gesture: BodyGesture, time: CMTime)]>())
    var detectGesturesCallCount: Int {
        return detectGesturesState.withLock(\.callCount)
    }

    var detectGesturesArgValues: [(videoURL: URL, gestures: [BodyGesture], sampleInterval: TimeInterval)] {
        return detectGesturesState.withLock(\.argValues).map(\.value)
    }

    var detectGesturesHandler: (@Sendable (URL, [BodyGesture], TimeInterval, (@Sendable (Int, Int) -> Void)?) async throws -> [(gesture: BodyGesture, time: CMTime)])? {
        get { detectGesturesState.withLock(\.handler) }
        set { detectGesturesState.withLock { $0.handler = newValue } }
    }

    func detectGestures(in videoURL: URL, gestures: [BodyGesture], sampleInterval: TimeInterval, progressHandler: (@Sendable (Int, Int) -> Void)?) async throws -> [(gesture: BodyGesture, time: CMTime)] {
        warnIfNotSendable(videoURL, gestures, sampleInterval)
        let detectGesturesHandler = detectGesturesState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((videoURL, gestures, sampleInterval)))
            return state.handler
        }
        if let detectGesturesHandler = detectGesturesHandler {
            return try await detectGesturesHandler(videoURL, gestures, sampleInterval, progressHandler)
        }
        return [(gesture: BodyGesture, time: CMTime)]()
    }
}

final class VisionOrchestratorProtocolMock: VisionOrchestratorProtocol, @unchecked Sendable {
    init() {}

    private let analyzeState = MockoloMutex(MockoloHandlerState<(videoURL: URL, config: VisionAnalysisConfig), @Sendable (URL, VisionAnalysisConfig, ((Double) -> Void)?) async throws -> VisionAnalysisResult>())
    var analyzeCallCount: Int {
        return analyzeState.withLock(\.callCount)
    }

    var analyzeArgValues: [(videoURL: URL, config: VisionAnalysisConfig)] {
        return analyzeState.withLock(\.argValues).map(\.value)
    }

    var analyzeHandler: (@Sendable (URL, VisionAnalysisConfig, ((Double) -> Void)?) async throws -> VisionAnalysisResult)? {
        get { analyzeState.withLock(\.handler) }
        set { analyzeState.withLock { $0.handler = newValue } }
    }

    func analyze(videoURL: URL, config: VisionAnalysisConfig, progressHandler: ((Double) -> Void)?) async throws -> VisionAnalysisResult {
        warnIfNotSendable(videoURL, config)
        let analyzeHandler = analyzeState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((videoURL, config)))
            return state.handler
        }
        if let analyzeHandler = analyzeHandler {
            return try await analyzeHandler(videoURL, config, progressHandler)
        }
        fatalError("analyzeHandler returns can't have a default value thus its handler must be set")
    }

    private let warmupState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())
    var warmupCallCount: Int {
        return warmupState.withLock(\.callCount)
    }

    var warmupHandler: (@Sendable () -> Void)? {
        get { warmupState.withLock(\.handler) }
        set { warmupState.withLock { $0.handler = newValue } }
    }

    func warmup() {
        let warmupHandler = warmupState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let warmupHandler = warmupHandler {
            warmupHandler()
        }
    }
}

private func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

private func warnIfNotSendable<each T: Sendable>(function _: String = #function, _: repeat each T) {}

/// Will be replaced to `Synchronization.Mutex` in future.
private final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        value = initialValue
    }

    #if compiler(>=6.0)
        borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
            lock.lock()
            defer { lock.unlock() }
            return try body(&value)
        }
    #else
        func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
            lock.lock()
            defer { lock.unlock() }
            return try body(&value)
        }
    #endif
}

private struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

private struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler?
    var callCount: Int = 0
}
